import { Plug, Settings2 } from 'lucide-react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import type { IntegrationSession, NormalizedResource } from '@/integration-sdk/contracts'
import { IntegrationIcon } from '@/components/settings/integration-icons'

export interface ConnectorResource { readonly integrationId: string; readonly resource: NormalizedResource }
import { connectorCatalog } from './connector-catalog'
export interface ConnectorMenuProps { readonly sessions?: readonly IntegrationSession[]; readonly resources?: readonly ConnectorResource[]; readonly onSelectResource?: (resource: ConnectorResource) => void; readonly onManage?: () => void; readonly disabled?: boolean; readonly triggerClassName?: string }

export function ConnectorMenu({ sessions = [], resources = [], onSelectResource, onManage, disabled, triggerClassName }: ConnectorMenuProps) {
  const [managementOpen,setManagementOpen]=useState(false)
  return <><DropdownMenu><DropdownMenuTrigger asChild><Button type="button" variant="ghost" size="icon-sm" className={triggerClassName} aria-label="Connectors" disabled={disabled}><Plug className="size-4" /></Button></DropdownMenuTrigger><DropdownMenuContent align="start" className="w-72"><DropdownMenuLabel>Connectors</DropdownMenuLabel>{connectorCatalog.map((connector) => {
    const session = sessions.find((item) => item.integrationId === connector.id && (!item.expiresAt || Date.parse(item.expiresAt) > Date.now()) && (item.authMode === 'none' || item.secretHandle))
    const connectedResources = session ? resources.filter((item) => item.integrationId === connector.id) : []
    const status = session ? 'Connected' : connector.availability === 'host-required' ? 'Host required' : connector.availability === 'adapter-required' ? 'Coming soon' : 'Connect'
    return <div key={connector.id}><DropdownMenuItem disabled={!session || connectedResources.length === 0} onSelect={() => connectedResources[0] && onSelectResource?.(connectedResources[0])}><span className={`flex shrink-0 self-stretch items-center ${session?'':'opacity-45 grayscale'}`}><IntegrationIcon id={connector.id} name={connector.product.name} size="compact"/></span><span className="min-w-0 flex-1 truncate">{connector.product.name}</span><span className="text-[10px] text-muted-foreground">{status}</span></DropdownMenuItem>{connectedResources.map((item) => <DropdownMenuItem key={item.resource.id} className="pl-9" onSelect={() => onSelectResource?.(item)}>{item.resource.title}</DropdownMenuItem>)}</div>
  })}<DropdownMenuSeparator /><DropdownMenuItem onSelect={() => { setManagementOpen(true); onManage?.() }}><Settings2 className="size-4" />Add connectors</DropdownMenuItem></DropdownMenuContent></DropdownMenu><Dialog open={managementOpen} onOpenChange={setManagementOpen}><DialogContent className="max-w-md"><DialogHeader><DialogTitle>Manage connectors</DialogTitle><DialogDescription>Accounts are connected only by an authorized desktop or integration host. Credentials remain opaque SecretHandles.</DialogDescription></DialogHeader><div className="divide-y divide-border rounded-md border border-border">{connectorCatalog.map((connector)=>{const connected=sessions.some((session)=>session.integrationId===connector.id&&(session.authMode==='none'||session.secretHandle));const status=connected?'Connected':connector.availability==='host-required'?'Host required':connector.availability==='adapter-required'?'Coming soon':'Connect';return <div key={connector.id} className="flex items-center justify-between gap-3 px-3 py-2"><span className={connected?'':'opacity-45 grayscale'}><IntegrationIcon id={connector.id} name={connector.product.name}/></span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{connector.product.name}</p><p className="text-xs text-muted-foreground">{connector.unavailableReason??'Authorized host connection available.'}</p></div><span className="shrink-0 text-xs text-muted-foreground">{status}</span></div>})}</div></DialogContent></Dialog></>
}
