import { ShieldAlert, ShieldCheck, Wrench } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import type { GovernanceReceipt, GovernanceScenario } from '@/design-governance'

export interface GovernanceSummaryProps { readonly receipt:GovernanceReceipt; readonly scenarios?:readonly GovernanceScenario[]; readonly onRequestRepair?:(input:{receiptId:string;failedFindingIds:readonly string[];requiresApproval:boolean})=>void }
export function GovernanceSummary({receipt,scenarios=[],onRequestRepair}:GovernanceSummaryProps){
 const failed=receipt.findings.filter((finding)=>finding.status==='failed'),hard=failed.filter((finding)=>finding.severity==='hard'),advisories=failed.filter((finding)=>finding.severity==='advisory'),byId=new Map(scenarios.map((scenario)=>[scenario.scenarioId,scenario]));const requiresApproval=hard.some((finding)=>{const scenario=byId.get(finding.scenarioId);return Boolean(scenario&&(scenario.lockedTokenIds.includes(scenario.foregroundTokenId)||scenario.lockedTokenIds.includes(scenario.backgroundTokenId)))})
 return <section className="space-y-2 rounded-md border border-border p-3" data-slot="governance-summary" aria-label="Design governance">
  <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2">{hard.length?<ShieldAlert className="size-4 text-destructive"/>:<ShieldCheck className="size-4 text-emerald-600"/>}<span className="text-sm font-medium">Design governance</span></div><div className="flex gap-1"><Badge variant={hard.length?'destructive':'secondary'}>{hard.length} blockers</Badge><Badge variant="outline">{advisories.length} advisories</Badge></div></div>
  {hard.length?<p className="text-xs text-muted-foreground">Promotion is paused until the measured blockers are repaired.</p>:<p className="text-xs text-muted-foreground">No measured hard blockers. Advisories remain reviewable.</p>}
  {failed.length?<ul className="space-y-1">{failed.slice(0,3).map((finding)=>{const scenario=byId.get(finding.scenarioId);return <li key={finding.id} className="text-xs"><span className="font-medium">{finding.summary}</span>{scenario?<span className="ml-1 text-muted-foreground">{scenario.mode} · {scenario.state}</span>:null}</li>})}</ul>:null}
  <div className="flex flex-wrap items-center gap-2">{hard.length&&onRequestRepair?<Button size="sm" variant="outline" onClick={()=>onRequestRepair({receiptId:receipt.receiptId,failedFindingIds:hard.map((finding)=>finding.id),requiresApproval})}><Wrench/> Request repair</Button>:null}{requiresApproval?<span className="text-xs text-amber-700 dark:text-amber-300">Brand-locked values require human approval.</span>:null}</div>
  <details className="text-xs"><summary className="cursor-pointer text-muted-foreground">Details and evidence</summary><div className="mt-2 space-y-2">{failed.map((finding)=>{const scenario=byId.get(finding.scenarioId);return <article key={finding.id} className="rounded-md border border-border p-2"><div className="flex flex-wrap gap-1"><Badge variant="outline">{finding.severity}</Badge>{scenario?<><Badge variant="outline">{scenario.mode}</Badge><Badge variant="outline">{scenario.state}</Badge></>:null}</div><p className="mt-1 font-medium">{finding.rule}</p><p className="text-muted-foreground">{finding.summary}</p>{scenario?<p className="mt-1 font-mono text-[10px]">{scenario.selector} · {scenario.foregroundTokenId} / {scenario.backgroundTokenId}</p>:null}<pre className="mt-1 overflow-auto whitespace-pre-wrap text-[10px]">{JSON.stringify(finding.evidence,null,2)}</pre></article>})}<p className="font-mono text-[10px]">Receipt {receipt.receiptId} · evidence {receipt.evidenceHash}</p></div></details>
 </section>
}
