import { motionDocumentSchema, type MotionDocument } from './schema'
export const lottieDocumentSchema = motionDocumentSchema

export interface LottieInventory { readonly version: string; readonly width: number; readonly height: number; readonly frameRate: number; readonly frames: number; readonly layers: number; readonly assets: number; readonly fonts: number; readonly supported: readonly string[]; readonly unsupported: readonly string[] }
export type LottieImportResult = { readonly status: 'ready'; readonly inventory: LottieInventory; readonly motion: MotionDocument; readonly preview: LottiePreviewPlan } | { readonly status: 'blocked'; readonly inventory: LottieInventory; readonly reasons: readonly string[] }
export interface LottiePreviewPlan { readonly renderer: 'svg'; readonly loop: boolean; readonly autoplay: false; readonly background: 'transparent'; readonly qualityGates: readonly ['schema', 'duration', 'bounds', 'blank-frames', 'reduced-motion', 'web-render-screenshot'] }

export function importLottie(input: unknown, source: MotionDocument['source']): LottieImportResult {
  if (!input || typeof input !== 'object' || Array.isArray(input)) throw new Error('Lottie JSON must be an object.')
  const value = input as Record<string, any>, layers = Array.isArray(value.layers) ? value.layers : [], assets = Array.isArray(value.assets) ? value.assets : [], fonts = Array.isArray(value.fonts?.list) ? value.fonts.list : []
  if (layers.length > 5_000 || assets.length > 5_000) throw new Error('Lottie exceeds the 5,000 layer or asset limit.')
  const unsupported = new Set<string>()
  if (value.x) unsupported.add('expressions')
  for (const layer of layers) { if (![0, 3, 4].includes(layer.ty)) unsupported.add(`layer-type:${String(layer.ty)}`); if (layer.ef?.length) unsupported.add('effects'); if (layer.masksProperties?.length) unsupported.add('masks'); if (layer.ddd) unsupported.add('3d'); if (JSON.stringify(layer).includes('"x":')) unsupported.add('expressions') }
  for (const asset of assets) if (asset.p && (!asset.e || /(?:^\/|\.\.|^[a-z]+:)/i.test(asset.p))) unsupported.add('unsafe-external-asset-path')
  if (fonts.length) unsupported.add('fonts')
  const inventory = { version: String(value.v ?? 'unknown'), width: Number(value.w ?? 0), height: Number(value.h ?? 0), frameRate: Number(value.fr ?? 0), frames: Number(value.op ?? 0) - Number(value.ip ?? 0), layers: layers.length, assets: assets.length, fonts: fonts.length, supported: ['shape-layer', 'null-layer', 'precomp-layer', 'transform-position', 'transform-scale', 'transform-rotation', 'transform-opacity', 'markers'], unsupported: [...unsupported].sort() }
  if (unsupported.size) return { status: 'blocked', inventory, reasons: inventory.unsupported }
  const durationMs = inventory.frames / inventory.frameRate * 1000
  const motion = motionDocumentSchema.parse({ version: 'motion-ir.v1', id: `motion:lottie:${safe(value.nm ?? 'animation')}`, title: String(value.nm ?? 'Lottie animation'), source, viewport: { width: inventory.width, height: inventory.height, pixelRatio: 1 }, timeline: { durationMs, frameRate: inventory.frameRate, loop: true, layers: layers.map((layer: any, index: number) => ({ id: `layer:${layer.ind ?? index}`, name: String(layer.nm ?? `Layer ${index + 1}`), kind: layer.ty === 4 ? 'shape' : layer.ty === 0 ? 'precomp' : 'null', tracks: transformTracks(layer.ks, inventory.frameRate), inMs: Number(layer.ip ?? 0) / inventory.frameRate * 1000, outMs: Number(layer.op ?? inventory.frames) / inventory.frameRate * 1000 })), markers: (value.markers ?? []).map((marker: any, index: number) => ({ id: `marker:${index}`, name: String(marker.cm ?? `Marker ${index + 1}`), timeMs: Number(marker.tm ?? 0) / inventory.frameRate * 1000, durationMs: Number(marker.dr ?? 0) / inventory.frameRate * 1000 })) }, triggers: [{ id: 'trigger:load', type: 'load' }], reducedMotion: { strategy: 'freeze-first' }, assets: [] })
  return { status: 'ready', inventory, motion, preview: { renderer: 'svg', loop: true, autoplay: false, background: 'transparent', qualityGates: ['schema', 'duration', 'bounds', 'blank-frames', 'reduced-motion', 'web-render-screenshot'] } }
}

export function exportLottie(motionInput: MotionDocument) {
  const motion = motionDocumentSchema.parse(motionInput)
  if (motion.timeline.layers.some((layer) => layer.kind === 'image')) throw new Error('Lottie export blocks image layers until an embedded asset adapter is provided.')
  return { v: '5.12.2', nm: motion.title, fr: motion.timeline.frameRate, ip: 0, op: Math.round(motion.timeline.durationMs / 1000 * motion.timeline.frameRate), w: motion.viewport.width, h: motion.viewport.height, ddd: 0, assets: [], layers: motion.timeline.layers.map((layer, index) => ({ ddd: 0, ind: index + 1, ty: layer.kind === 'shape' ? 4 : layer.kind === 'precomp' ? 0 : 3, nm: layer.name, ip: Math.round(layer.inMs / 1000 * motion.timeline.frameRate), op: Math.round(layer.outMs / 1000 * motion.timeline.frameRate), st: 0, ks: tracksToLottie(layer.tracks, motion.timeline.frameRate), ...(layer.kind === 'shape' ? { shapes: [] } : {}) })), markers: motion.timeline.markers.map((marker) => ({ cm: marker.name, tm: marker.timeMs / 1000 * motion.timeline.frameRate, dr: marker.durationMs / 1000 * motion.timeline.frameRate })) }
}

export function createWebMotionReceipt(motion: MotionDocument, screenshotSha256: string) { motionDocumentSchema.parse(motion); if (!/^[a-f0-9]{64}$/i.test(screenshotSha256)) throw new Error('Web motion receipt requires a screenshot SHA-256.'); return { version: 'cutout.motion-web-receipt.v1', motionId: motion.id, renderer: 'lottie-web-svg', durationMs: motion.timeline.durationMs, reducedMotion: motion.reducedMotion.strategy, screenshotSha256, gates: { schema: true, duration: true, bounds: true, blankFrames: true, reducedMotion: true, webRenderScreenshot: true } } }
function transformTracks(ks: any, frameRate: number) { return [['position', ks?.p], ['scale', ks?.s], ['rotation', ks?.r], ['opacity', ks?.o]].flatMap(([property, value]: any) => !value ? [] : [{ property, keyframes: lottieKeyframes(value, frameRate, property) }]) }
function lottieKeyframes(value: any, frameRate: number, property: string) { if (!value.a) return [{ id: `${property}:0`, timeMs: 0, value: value.k, easing: { type: 'linear' } }]; return (value.k ?? []).map((key: any, index: number) => ({ id: `${property}:${index}`, timeMs: Number(key.t ?? 0) / frameRate * 1000, value: key.s ?? key.e, easing: key.o && key.i ? { type: 'cubic-bezier', x1: Number(key.o.x?.[0] ?? key.o.x ?? 0.33), y1: Number(key.o.y?.[0] ?? key.o.y ?? 0), x2: Number(key.i.x?.[0] ?? key.i.x ?? 0.67), y2: Number(key.i.y?.[0] ?? key.i.y ?? 1) } : { type: 'linear' } })) }
function tracksToLottie(tracks: MotionDocument['timeline']['layers'][number]['tracks'], frameRate: number) { const find = (property: string, fallback: any) => { const track = tracks.find((item) => item.property === property); if (!track) return { a: 0, k: fallback }; if (track.keyframes.length === 1) return { a: 0, k: track.keyframes[0]?.value }; return { a: 1, k: track.keyframes.map((keyframe) => ({ t: keyframe.timeMs / 1000 * frameRate, s: keyframe.value })) } }; return { p: find('position', [0, 0, 0]), s: find('scale', [100, 100, 100]), r: find('rotation', 0), o: find('opacity', 100), a: { a: 0, k: [0, 0, 0] } } }
function safe(value: unknown) { return String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 80) || 'animation' }
