import { describe,expect,it } from 'vitest'
import { correlateTrace,createDiagnosticBundle,createRecoverySnapshot,diagnosticBundleBytes,doctorProviderConnection,LOCAL_DATA_CONTRACT,LocalRecoveryService,markCleanExit,redactDiagnosticValue,resetUiState,startCrashSession,type CrashMarker,type CrashMarkerStore,type RecoveryBackend,type RecoveryBlob,type RecoverySnapshot } from '.'

function memory(input:{available?:number;projection?:boolean}={}){
  const snapshots:RecoverySnapshot[]=[],blobs:RecoveryBlob[]=[],rebuilt:Uint8Array[]=[];let projection=input.projection??false
  const backend:RecoveryBackend={listSnapshots:async(projectId)=>snapshots.filter((item)=>item.projectId===projectId),putSnapshot:async(item)=>{snapshots.push(item)},removeSnapshot:async(id)=>{const index=snapshots.findIndex((item)=>item.id===id);if(index>=0)snapshots.splice(index,1)},listBlobs:async()=>blobs,removeBlob:async(id)=>{const index=blobs.findIndex((item)=>item.id===id);if(index>=0)blobs.splice(index,1)},projectionExists:async()=>projection,rebuildProjection:async(_id,bytes)=>{projection=true;rebuilt.push(bytes)},availableBytes:async()=>input.available??1_000_000}
  return{backend,snapshots,blobs,rebuilt,setProjection:(value:boolean)=>{projection=value}}
}

describe('local recovery service',()=>{
  it('declares .cutout authoritative and IndexedDB as a rebuildable local projection',()=>{expect(LOCAL_DATA_CONTRACT).toEqual({authoritative:'.cutout',projection:'indexeddb',projectionRebuildable:true,remoteSync:false})})
  it('retains verified snapshots and rejects low disk before partial writes',async()=>{const host=memory({available:30}),service=new LocalRecoveryService(host.backend,2),one=await createRecoverySnapshot({projectId:'p',revision:1,value:{a:1},createdAt:'2026-01-01T00:00:00Z'});await service.checkpoint(one);const tooLarge=await createRecoverySnapshot({projectId:'p',revision:2,value:{large:'x'.repeat(100)},createdAt:'2026-01-02T00:00:00Z'});await expect(service.checkpoint(tooLarge)).rejects.toThrow('Insufficient');expect(host.snapshots).toEqual([one])})
  it('removes corrupt snapshots and orphan blobs then rebuilds only from verified canonical bytes',async()=>{const host=memory(),service=new LocalRecoveryService(host.backend),good=await createRecoverySnapshot({projectId:'p',revision:1,value:{ok:true},createdAt:'2026-01-01T00:00:00Z'}),bad={...good,id:'bad',revision:2,bytes:new Uint8Array([9])};host.snapshots.push(good,bad);host.blobs.push({id:'live',bytes:new Uint8Array([1]),referencedBy:[good.id]},{id:'orphan',bytes:new Uint8Array([2]),referencedBy:['missing']});expect(await service.repair('p')).toEqual({removedCorruptSnapshots:['bad'],removedOrphanBlobs:['orphan'],rebuiltProjection:true});expect(host.rebuilt).toHaveLength(1);expect(host.blobs.map((item)=>item.id)).toEqual(['live'])})
  it('rejects restore collisions and corrupt blobs without overwriting a projection',async()=>{const host=memory({projection:true}),service=new LocalRecoveryService(host.backend),snapshot=await createRecoverySnapshot({projectId:'p',revision:1,value:{ok:true},createdAt:'2026-01-01T00:00:00Z'});host.snapshots.push(snapshot);await expect(service.restore('p')).rejects.toThrow('collision');host.setProjection(false);host.snapshots[0]={...snapshot,bytes:new Uint8Array([0])};await expect(service.restore('p')).rejects.toThrow('corrupt');expect(host.rebuilt).toHaveLength(0)})
  it('does not publish a partial migration when transform or quota fails',async()=>{const host=memory(),service=new LocalRecoveryService(host.backend),snapshot=await createRecoverySnapshot({projectId:'p',revision:1,value:{version:1},createdAt:'2026-01-01T00:00:00Z'});host.snapshots.push(snapshot);await expect(service.migrate('p',()=>{throw new Error('partial')})).rejects.toThrow('partial');expect(host.snapshots).toHaveLength(1);const low=memory({available:1}),lowService=new LocalRecoveryService(low.backend);low.snapshots.push(snapshot);await expect(lowService.migrate('p',()=>({version:2}))).rejects.toThrow('Insufficient');expect(low.snapshots).toHaveLength(1)})
})

describe('crash recovery and diagnostics',()=>{
  function markerStore(){let value:CrashMarker|undefined;return{store:{read:()=>value,write:(next)=>{value=next},clear:()=>{value=undefined}}satisfies CrashMarkerStore,read:()=>value}}
  it('detects repeated unclean startup, enters safe mode, and clears risk after clean exit',()=>{const host=markerStore();expect(startCrashSession(host.store,{sessionId:'1',now:'2026-01-01T00:00:00Z'})).toMatchObject({crashed:false,safeMode:false});expect(startCrashSession(host.store,{sessionId:'2',now:'2026-01-01T00:01:00Z'})).toMatchObject({crashed:true,safeMode:false});expect(startCrashSession(host.store,{sessionId:'3',now:'2026-01-01T00:02:00Z'})).toMatchObject({crashed:true,safeMode:true});markCleanExit(host.store);expect(host.read()?.cleanExit).toBe(true)})
  it('redacts prompt, content, paths and secrets and emits deterministic bundles',()=>{const input={prompt:'private',nested:{token:'sk-supersecret',safe:'Bearer abcdefghijklmnop',message:'/Users/alice/private/file'}};expect(JSON.stringify(redactDiagnosticValue(input))).not.toMatch(/private|sk-|Bearer|\/Users/);const event={at:'2026-01-01T00:00:00Z',level:'error' as const,scope:'provider' as const,code:'failed',correlationId:'c1',details:input},bundle=createDiagnosticBundle({generatedAt:'2026-01-01T00:01:00Z',version:'1.0.0',safeMode:true,events:[event]});expect(diagnosticBundleBytes(bundle)).toEqual(diagnosticBundleBytes(createDiagnosticBundle({generatedAt:'2026-01-01T00:01:00Z',version:'1.0.0',safeMode:true,events:[event]})));expect(new TextDecoder().decode(diagnosticBundleBytes(bundle))).not.toMatch(/private|sk-|Bearer|\/Users/)})
  it('reports provider capability failures without leaking adapter secrets',()=>{expect(doctorProviderConnection({configured:true,model:'text-only',visionRequired:true,visionCapable:false,lastError:'Bearer abcdefghijklmnop'})).toEqual({ok:false,issues:['The assigned model does not provide required vision capability.','<redacted>']})})
  it('correlates UI, Tauri and host evidence and resets only explicit UI keys',()=>{expect(correlateTrace({correlationId:'run.1',ui:{ok:true},tauri:{ok:true},host:{ok:true}}).map((item)=>item.scope)).toEqual(['ui','tauri','host']);const removed:string[]=[];resetUiState({removeItem:(key)=>removed.push(key)},['navigation','theme']);expect(removed).toEqual(['navigation','theme'])})
})
