import{z}from'zod'
const id=z.string().regex(/^[a-z0-9][a-z0-9._-]*$/).max(160),at=z.string().datetime()
export const teamRoleSchema=z.enum(['viewer','reviewer','editor','admin'])
export const orgPolicySchema=z.object({protocol:z.literal('cutout.org-policy.v1'),orgId:id,privateNamespaces:z.array(id),defaultRole:teamRoleSchema,requireApprovedQuality:z.boolean(),allowRemoteSync:z.boolean(),allowedLicenses:z.array(z.string().min(1)),updatedAt:at}).strict()
export const reviewBranchSchema=z.object({protocol:z.literal('cutout.review-branch.v1'),id,projectId:id,baseRevisionId:id,headRevisionId:id,authorId:id,status:z.enum(['open','approved','changes-requested','merged','closed']),comments:z.array(z.object({id,authorId:id,body:z.string().min(1).max(5000),materialId:id.optional(),revisionId:id.optional(),createdAt:at,resolvedAt:at.optional()}).strict()),approvals:z.array(z.object({id,reviewerId:id,revisionId:id,decision:z.enum(['approved','changes-requested']),createdAt:at}).strict()),createdAt:at,updatedAt:at}).strict().superRefine((branch,ctx)=>{if(branch.status==='approved'&&!branch.approvals.some(a=>a.revisionId===branch.headRevisionId&&a.decision==='approved'))ctx.addIssue({code:'custom',message:'Approved branch requires a head-revision approval.'})})
export const shareLinkSchema=z.object({protocol:z.literal('cutout.readonly-share.v1'),id,projectId:id,revisionId:id,createdBy:id,permission:z.literal('view'),expiresAt:at.optional(),revokedAt:at.optional(),createdAt:at}).strict()
export interface CollaborationHost{saveBranch(branch:z.infer<typeof reviewBranchSchema>):Promise<void>;loadBranch(id:string):Promise<unknown>;createShare(link:z.infer<typeof shareLinkSchema>):Promise<void>}
export class CollaborationService{readonly host?:CollaborationHost;constructor(host?:CollaborationHost){this.host=host}capabilities(){return{local:Boolean(this.host),remoteSync:false,comments:Boolean(this.host),reviewBranches:Boolean(this.host),readOnlyShare:Boolean(this.host)}}async saveBranch(input:unknown){if(!this.host)throw new Error('Collaboration host capability is required.');const branch=reviewBranchSchema.parse(input);await this.host.saveBranch(branch);return branch}async createShare(input:unknown){if(!this.host)throw new Error('Collaboration host capability is required.');const link=shareLinkSchema.parse(input);await this.host.createShare(link);return link}}
export function can(role:z.infer<typeof teamRoleSchema>,action:'view'|'comment'|'edit'|'approve'|'admin'){const rank={viewer:0,reviewer:1,editor:2,admin:3}[role];return rank>=({view:0,comment:1,approve:1,edit:2,admin:3}[action])}
