import { z } from 'zod'

const id = z.string().regex(/^[a-z0-9][a-z0-9._-]*$/).max(160)
const semver = z.string().regex(/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/)
export const workflowPackSchema = z.object({ protocol:z.literal('cutout.workflow-pack.v1'), id, version:semver, title:z.string().min(1).max(160), description:z.string().min(1).max(1000), cutoutRange:z.string().min(1).max(80), capabilities:z.array(id).min(1), skillRefs:z.array(z.object({id,version:semver}).strict()).default([]), steps:z.array(z.object({id,operation:id,dependsOn:z.array(id).default([]),effect:z.enum(['none','project-state','managed-export','provider-required']),approval:z.enum(['none','policy','explicit'])}).strict()).min(1), evalCard:z.object({datasetId:id,metrics:z.array(z.object({id,threshold:z.number().min(0).max(1),weight:z.number().positive()}).strict()).min(1), minimumScore:z.number().min(0).max(1)}).strict(), provenance:z.object({producer:id,capturedAt:z.string().datetime(),contentSha256:z.string().regex(/^[a-f0-9]{64}$/)}).strict() }).strict().superRefine((pack,ctx)=>{const steps=new Set(pack.steps.map(s=>s.id));for(const step of pack.steps)for(const dep of step.dependsOn)if(!steps.has(dep))ctx.addIssue({code:'custom',message:`Unknown workflow dependency ${dep}.`});if(hasCycle(pack.steps))ctx.addIssue({code:'custom',message:'Workflow pack contains a dependency cycle.'})})
export type WorkflowPack=z.infer<typeof workflowPackSchema>
export function migrateWorkflowPack(input:unknown):WorkflowPack{if(input&&typeof input==='object'&&(input as {protocol?:unknown}).protocol==='cutout.workflow-pack.v1')return workflowPackSchema.parse(input);const legacy=input as Record<string,unknown>;return workflowPackSchema.parse({...legacy,protocol:'cutout.workflow-pack.v1',skillRefs:Array.isArray(legacy?.skillRefs)?legacy.skillRefs:[]})}
export function previewWorkflowPackDowngrade(input:unknown){const pack=workflowPackSchema.parse(input);return{target:'cutout.workflow-pack.v0' as const,data:Object.fromEntries(Object.entries(pack).filter(([key])=>!['protocol','skillRefs'].includes(key))),losses:pack.skillRefs.length?[{path:'skillRefs',count:pack.skillRefs.length,reason:'Workflow Pack v0 cannot preserve progressive Skill disclosure.'}]:[]}}
export const workflowEvalResultSchema=z.object({protocol:z.literal('cutout.workflow-eval.v1'),packId:id,packVersion:semver,datasetId:id,metrics:z.array(z.object({id,score:z.number().min(0).max(1),evidenceIds:z.array(id)}).strict()),weightedScore:z.number().min(0).max(1),status:z.enum(['passed','failed']),evaluatedAt:z.string().datetime()}).strict()
export function evaluateWorkflowPack(packInput:unknown,scores:Readonly<Record<string,{score:number;evidenceIds:readonly string[]}>>,at:string){const pack=workflowPackSchema.parse(packInput);let total=0,weights=0;const metrics=pack.evalCard.metrics.map(metric=>{const actual=scores[metric.id];if(!actual)throw new Error(`Missing workflow eval metric ${metric.id}.`);total+=actual.score*metric.weight;weights+=metric.weight;return{id:metric.id,score:actual.score,evidenceIds:[...actual.evidenceIds]}});const weightedScore=total/weights;const thresholds=pack.evalCard.metrics.every(metric=>(scores[metric.id]?.score??0)>=metric.threshold);return workflowEvalResultSchema.parse({protocol:'cutout.workflow-eval.v1',packId:pack.id,packVersion:pack.version,datasetId:pack.evalCard.datasetId,metrics,weightedScore,status:thresholds&&weightedScore>=pack.evalCard.minimumScore?'passed':'failed',evaluatedAt:at})}
export function workflowPackCompatibility(pack:WorkflowPack,input:{cutoutVersion:string;capabilities:readonly string[]}){const major=(v:string)=>Number(v.split('.')[0]);const required=Number(pack.cutoutRange.match(/\d+/)?.[0]??NaN);const missing=pack.capabilities.filter(cap=>!input.capabilities.includes(cap));return{compatible:major(input.cutoutVersion)===required&&missing.length===0,missingCapabilities:missing,reason:major(input.cutoutVersion)!==required?'Cutout major version is outside the pack range.':missing.length?'Required capabilities are unavailable.':undefined}}
function hasCycle(steps:readonly {id:string;dependsOn:readonly string[]}[]){const map=new Map(steps.map(s=>[s.id,s.dependsOn]));const visiting=new Set<string>(),done=new Set<string>();const visit=(id:string):boolean=>{if(visiting.has(id))return true;if(done.has(id))return false;visiting.add(id);for(const dep of map.get(id)??[])if(visit(dep))return true;visiting.delete(id);done.add(id);return false};return steps.some(s=>visit(s.id))}
