import{mkdtemp,readFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{describe,expect,it}from'vitest';import{createNodeFileHostStore,DurableAgentHost}from'.'
function clock(at=1000,random=.5){let now=at;return{now:()=>now,random:()=>random,advance:(ms:number)=>{now+=ms}}}
async function host(path:string,id:string,c=clock()){const value=new DurableAgentHost({store:createNodeFileHostStore(path),instanceId:id,clock:c});await value.start();return value}
describe('durable Agent Host',()=>{
 it('persists runs and deterministically recovers crash/restart without repeating completed nodes',async()=>{const dir=await mkdtemp(join(tmpdir(),'cutout-host-')),path=join(dir,'host.json'),c=clock(),first=await host(path,'host-1',c);await first.startRun('run-1',[{id:'done'},{id:'active'}]);await first.claim('run-1','done',{leaseMs:100,maxAttempts:3});await first.complete('run-1','done');await first.claim('run-1','active',{leaseMs:100,maxAttempts:3});const restarted=await host(path,'host-2',c),run=restarted.status().runs['run-1']!;expect(run.status).toBe('recovering');expect(run.nodes.done.status).toBe('succeeded');expect(run.nodes.active).toMatchObject({status:'queued',attempts:[{number:1}]});expect(await restarted.claim('run-1','done',{leaseMs:100,maxAttempts:3})).toBeUndefined();expect(await restarted.claim('run-1','active',{leaseMs:100,maxAttempts:3})).toMatchObject({attempt:2})})
 it('recovers queued work as paused until explicitly resumed',async()=>{const path=join(await mkdtemp(join(tmpdir(),'cutout-host-')),'host.json'),first=await host(path,'one');await first.startRun('queued',[{id:'node'}]);const second=await host(path,'two');expect(second.status().runs.queued.status).toBe('paused');await second.resume('queued');expect(second.status().runs.queued.status).toBe('queued')})
 it('takes over stale leases but not live leases and detects sleep beyond heartbeat',async()=>{const path=join(await mkdtemp(join(tmpdir(),'cutout-host-')),'host.json'),c=clock(),one=await host(path,'one',c);await one.startRun('lease',[{id:'node'}]);await one.claim('lease','node',{leaseMs:100,maxAttempts:3});expect(await one.claim('lease','node',{leaseMs:100,maxAttempts:3})).toBeUndefined();expect(await one.heartbeat('lease','node',200)).toBe(true);c.advance(201);expect(await one.heartbeat('lease','node',200)).toBe(false);expect(await one.claim('lease','node',{leaseMs:100,maxAttempts:3})).toMatchObject({attempt:2})})
 it('rejects completion and failure at the exact lease expiry boundary',async()=>{const path=join(await mkdtemp(join(tmpdir(),'cutout-host-')),'host.json'),c=clock(),value=await host(path,'one',c);await value.startRun('expired',[{id:'complete'},{id:'fail'}]);await value.claim('expired','complete',{leaseMs:100,maxAttempts:2});await value.claim('expired','fail',{leaseMs:100,maxAttempts:2});c.advance(100);await expect(value.complete('expired','complete')).rejects.toThrow('live active lease');await expect(value.fail('expired','fail','late',{maxAttempts:2,baseDelayMs:10,maxDelayMs:100,jitter:0})).rejects.toThrow('live active lease');expect(value.status().runs.expired.nodes.complete.status).toBe('running');expect(value.status().runs.expired.nodes.fail.status).toBe('running')})
 it('commits side-effect receipts exactly once and rejects conflicting duplicate completion',async()=>{const path=join(await mkdtemp(join(tmpdir(),'cutout-host-')),'host.json'),value=await host(path,'one');await value.startRun('effects',[{id:'publish',effectKey:'effect:publish'}]);await value.claim('effects','publish',{leaseMs:100,maxAttempts:2});expect(await value.complete('effects','publish','receipt:1')).toMatchObject({status:'committed'});expect(await value.complete('effects','publish','receipt:1')).toMatchObject({status:'duplicate'});await expect(value.complete('effects','publish','receipt:2')).rejects.toThrow('receipt conflict');const persisted=JSON.parse(await readFile(path,'utf8'));expect(Object.keys(persisted.receipts)).toEqual(['effect:publish']);expect(persisted.runs.effects.nodes.publish.attempts).toHaveLength(1)})
 it('uses bounded exponential retry with jitter and stops at exhaustion',async()=>{const path=join(await mkdtemp(join(tmpdir(),'cutout-host-')),'host.json'),c=clock(1000,1),value=await host(path,'one',c);await value.startRun('retry',[{id:'node'}]);await value.claim('retry','node',{leaseMs:100,maxAttempts:2});expect(await value.fail('retry','node','first',{maxAttempts:2,baseDelayMs:100,maxDelayMs:1000,jitter:.2})).toBe('retry');expect(value.status().runs.retry.nodes.node.nextAttemptAt).toBe(1120);expect(await value.claim('retry','node',{leaseMs:100,maxAttempts:2})).toBeUndefined();c.advance(120);await value.claim('retry','node',{leaseMs:100,maxAttempts:2});expect(await value.fail('retry','node','second',{maxAttempts:2,baseDelayMs:100,maxDelayMs:1000,jitter:.2})).toBe('exhausted');expect(value.status().runs.retry).toMatchObject({status:'failed',nodes:{node:{status:'failed',attempts:[{},{}]}}})})
 it('makes cancellation win a completion race and persists terminal state',async()=>{const path=join(await mkdtemp(join(tmpdir(),'cutout-host-')),'host.json'),value=await host(path,'one');await value.startRun('cancel',[{id:'node',effectKey:'effect:node'}]);await value.claim('cancel','node',{leaseMs:100,maxAttempts:2});await value.cancel('cancel','user changed direction');expect(await value.complete('cancel','node','receipt:late')).toEqual({status:'cancelled'});expect(value.status().receipts['effect:node']).toBeUndefined();expect((await host(path,'two')).status().runs.cancel.status).toBe('cancelled')})
})
