export type HostStatus='stopped'|'running'|'recovering'
export type DurableRunStatus='queued'|'running'|'recovering'|'paused'|'cancelled'|'completed'|'failed'
export type DurableNodeStatus='queued'|'running'|'retry-wait'|'succeeded'|'failed'|'cancelled'
export interface HostLease{readonly owner:string;readonly acquiredAt:number;readonly heartbeatAt:number;readonly expiresAt:number}
export interface NodeAttempt{readonly number:number;readonly startedAt:number;readonly completedAt?:number;readonly error?:string}
export interface DurableNode{readonly id:string;readonly effectKey?:string;readonly status:DurableNodeStatus;readonly attempts:readonly NodeAttempt[];readonly nextAttemptAt?:number;readonly lease?:HostLease;readonly receiptId?:string}
export interface DurableRun{readonly id:string;readonly status:DurableRunStatus;readonly createdAt:number;readonly updatedAt:number;readonly nodes:Readonly<Record<string,DurableNode>>;readonly cancelReason?:string}
export interface DurableHostState{readonly version:1;readonly host:{readonly status:HostStatus;readonly instanceId?:string;readonly heartbeatAt?:number};readonly runs:Readonly<Record<string,DurableRun>>;readonly receipts:Readonly<Record<string,{readonly receiptId:string;readonly runId:string;readonly nodeId:string;readonly committedAt:number}>>}
export interface DurableHostStore{load():Promise<DurableHostState|undefined>;save(state:DurableHostState):Promise<void>;exclusive?<T>(action:()=>Promise<T>):Promise<T>}
export interface HostClock{now():number;random():number}
export const emptyDurableHostState=():DurableHostState=>({version:1,host:{status:'stopped'},runs:{},receipts:{}})
const clone=<T>(v:T):T=>structuredClone(v)

export class DurableAgentHost{
  readonly store:DurableHostStore;readonly clock:HostClock;readonly instanceId:string;#state:DurableHostState=emptyDurableHostState()
  constructor(input:{store:DurableHostStore;clock?:HostClock;instanceId:string}){this.store=input.store;this.clock=input.clock??{now:()=>Date.now(),random:()=>Math.random()};this.instanceId=input.instanceId}
  async start(){return this.#exclusive(async()=>{this.#state=(await this.store.load())??emptyDurableHostState();this.#state=this.#recover(this.#state);this.#state={...this.#state,host:{status:'running',instanceId:this.instanceId,heartbeatAt:this.clock.now()}};await this.store.save(this.#state);return this.status()})}
  async shutdown(){return this.#transaction(async()=>{this.#requireStarted();this.#state={...this.#state,host:{status:'stopped'}};await this.store.save(this.#state);return this.status()})}
  status(){return clone(this.#state)}
  async recover(){return this.#transaction(async()=>{this.#state=this.#recover(this.#state);await this.store.save(this.#state);return this.status()})}
  async startRun(runId:string,nodeIds:readonly{readonly id:string;readonly effectKey?:string}[]){return this.#transaction(async()=>{this.#requireStarted();if(this.#state.runs[runId])return clone(this.#state.runs[runId]);const now=this.clock.now(),nodes=Object.fromEntries(nodeIds.map(n=>[n.id,{id:n.id,...(n.effectKey?{effectKey:n.effectKey}:{}),status:'queued' as const,attempts:[]}])) as Record<string,DurableNode>;const run:DurableRun={id:runId,status:'queued',createdAt:now,updatedAt:now,nodes};await this.#commitRun(run);return clone(run)})}
  async claim(runId:string,nodeId:string,options:{leaseMs:number;maxAttempts:number}){return this.#transaction(async()=>{const run=this.#run(runId),node=this.#node(run,nodeId),now=this.clock.now();if(run.status==='cancelled'||run.status==='completed'||run.status==='failed')return undefined;if(node.status==='succeeded'||node.status==='failed'||node.status==='cancelled')return undefined;if(node.nextAttemptAt&&node.nextAttemptAt>now)return undefined;if(node.lease&&node.lease.expiresAt>now)return undefined;if(node.attempts.length>=options.maxAttempts){await this.#replaceNode(run,{...node,status:'failed',lease:undefined});return undefined}const attempt={number:node.attempts.length+1,startedAt:now},lease={owner:this.instanceId,acquiredAt:now,heartbeatAt:now,expiresAt:now+options.leaseMs};await this.#replaceNode({...run,status:'running'}, {...node,status:'running',attempts:[...node.attempts,attempt],lease,nextAttemptAt:undefined});return{runId,nodeId,attempt:attempt.number,lease:clone(lease)}})}
  async heartbeat(runId:string,nodeId:string,leaseMs:number){return this.#transaction(async()=>{const run=this.#run(runId),node=this.#node(run,nodeId);if(node.status!=='running'||node.lease?.owner!==this.instanceId)return false;const now=this.clock.now();if(node.lease.expiresAt<=now)return false;await this.#replaceNode(run,{...node,lease:{...node.lease,heartbeatAt:now,expiresAt:now+leaseMs}});return true})}
  async complete(runId:string,nodeId:string,receiptId?:string){return this.#transaction(async()=>{const run=this.#run(runId),node=this.#node(run,nodeId),now=this.clock.now();if(run.status==='cancelled')return{status:'cancelled' as const};if(node.status==='succeeded'){if(node.receiptId&&receiptId!==node.receiptId)throw new Error('Side-effect receipt conflict.');return{status:'duplicate' as const,receiptId:node.receiptId}}if(node.status!=='running'||node.lease?.owner!==this.instanceId||node.lease.expiresAt<=now)throw new Error('Node completion requires a live active lease.');let receipts=this.#state.receipts;if(node.effectKey){if(!receiptId)throw new Error('Side-effect completion requires a receipt.');const existing=receipts[node.effectKey];if(existing&&existing.receiptId!==receiptId)throw new Error('Side-effect receipt conflict.');receipts={...receipts,[node.effectKey]:existing??{receiptId,runId,nodeId,committedAt:now}}}const attempts=node.attempts.map((a,i)=>i===node.attempts.length-1?{...a,completedAt:now}:a);const nextNode={...node,status:'succeeded' as const,attempts,lease:undefined,...(receiptId?{receiptId}:{})};const nextRun=this.#withNode(run,nextNode);const complete=Object.values(nextRun.nodes).every(n=>n.status==='succeeded');this.#state={...this.#state,receipts};await this.#commitRun({...nextRun,status:complete?'completed':nextRun.status});return{status:'committed' as const,receiptId}})}
  async fail(runId:string,nodeId:string,error:string,options:{maxAttempts:number;baseDelayMs:number;maxDelayMs:number;jitter:number}){return this.#transaction(async()=>{const run=this.#run(runId),node=this.#node(run,nodeId),now=this.clock.now();if(run.status==='cancelled')return'cancelled';if(node.status!=='running'||node.lease?.owner!==this.instanceId||node.lease.expiresAt<=now)throw new Error('Node failure requires a live active lease.');const attempts=node.attempts.map((a,i)=>i===node.attempts.length-1?{...a,completedAt:now,error}:a);if(attempts.length>=options.maxAttempts){await this.#replaceNode({...run,status:'failed'},{...node,status:'failed',attempts,lease:undefined});return'exhausted'}const exponential=Math.min(options.maxDelayMs,options.baseDelayMs*2**(attempts.length-1)),factor=1+(this.clock.random()*2-1)*options.jitter,nextAttemptAt=now+Math.max(0,Math.round(exponential*factor));await this.#replaceNode(run,{...node,status:'retry-wait',attempts,lease:undefined,nextAttemptAt});return'retry'})}
  async cancel(runId:string,reason:string){return this.#transaction(async()=>{const run=this.#run(runId);if(run.status==='completed'||run.status==='failed')return clone(run);const nodes=Object.fromEntries(Object.entries(run.nodes).map(([id,node])=>[id,node.status==='succeeded'?node:{...node,status:'cancelled' as const,lease:undefined}]));const next={...run,status:'cancelled' as const,cancelReason:reason,nodes,updatedAt:this.clock.now()};await this.#commitRun(next);return clone(next)})}
  async pause(runId:string){return this.#transaction(async()=>{const run=this.#run(runId);if(run.status==='completed'||run.status==='cancelled'||run.status==='failed')return clone(run);const next={...run,status:'paused' as const,updatedAt:this.clock.now()};await this.#commitRun(next);return clone(next)})}
  async resume(runId:string){return this.#transaction(async()=>{const run=this.#run(runId);if(run.status!=='paused'&&run.status!=='recovering')return clone(run);const next={...run,status:'queued' as const,updatedAt:this.clock.now()};await this.#commitRun(next);return clone(next)})}
  #recover(state:DurableHostState){const now=this.clock.now(),runs=Object.fromEntries(Object.entries(state.runs).map(([id,run])=>{if(run.status==='queued')return[id,{...run,status:'paused' as const,updatedAt:now}];if(run.status!=='running')return[id,run];let recovered=false;const nodes=Object.fromEntries(Object.entries(run.nodes).map(([nodeId,node])=>{if(node.status!=='running'||!node.lease||node.lease.expiresAt>now)return[nodeId,node];recovered=true;return[nodeId,{...node,status:'queued' as const,lease:undefined}]}));return[id,recovered?{...run,status:'recovering' as const,nodes,updatedAt:now}:{...run,nodes}]}));return{...state,host:{status:'recovering' as const,instanceId:this.instanceId,heartbeatAt:now},runs}}
  async #exclusive<T>(action:()=>Promise<T>){return this.store.exclusive?this.store.exclusive(action):action()}
  async #transaction<T>(action:()=>Promise<T>){return this.#exclusive(async()=>{this.#state=(await this.store.load())??this.#state;return action()})}
  #requireStarted(){if(this.#state.host.status!=='running')throw new Error('Agent Host is not running.')}
  #run(id:string){const run=this.#state.runs[id];if(!run)throw new Error(`Unknown run ${id}.`);return run}
  #node(run:DurableRun,id:string){const node=run.nodes[id];if(!node)throw new Error(`Unknown node ${id}.`);return node}
  #withNode(run:DurableRun,node:DurableNode):DurableRun{return{...run,updatedAt:this.clock.now(),nodes:{...run.nodes,[node.id]:node}}}
  async #replaceNode(run:DurableRun,node:DurableNode){await this.#commitRun(this.#withNode(run,node))}
  async #commitRun(run:DurableRun){this.#state={...this.#state,runs:{...this.#state.runs,[run.id]:run},host:{status:'running',instanceId:this.instanceId,heartbeatAt:this.clock.now()}};await this.store.save(this.#state)}
}
