import { describe, expect, it, vi } from 'vitest'
import { assertGovernancePromotion, contrastRatio, createGovernanceRepairTask, enumerateGovernanceScenarios, evaluateGovernance, rerunGovernanceRepair } from './governance'

const bindings = [{ id:'button-label', selector:'#button', foregroundTokenId:'fg', backgroundTokenId:'bg', kind:'text' as const, modes:['light','dark','high-contrast'] as const, states:['default','focus'] as const, lockedTokenIds:['fg'] }]
describe('design governance', () => {
  it('enumerates explicit token usage without guessing', () => { expect(enumerateGovernanceScenarios(bindings, new Set(['fg','bg']))).toHaveLength(6); expect(() => enumerateGovernanceScenarios(bindings, new Set(['fg']))).toThrow('Unknown Design IR token') })
  it('composites transparency and applies typography thresholds', () => { expect(contrastRatio('rgba(0,0,0,.5)', ['rgba(255,255,255,.5)','rgb(255,255,255)'])).toBeGreaterThan(1); const scenarios = enumerateGovernanceScenarios([bindings[0]], new Set(['fg','bg'])).slice(0,1); const receipt = evaluateGovernance(scenarios, [{ scenarioId:scenarios[0].scenarioId, viewport:'desktop', foreground:'rgb(119,119,119)', backgroundLayers:['rgb(255,255,255)'], fontSizePx:16, fontWeight:400, outlineWidthPx:0, nonColorCue:false, axeViolations:[] }], 1); expect(receipt.status).toBe('blocked'); expect(() => assertGovernancePromotion(receipt, 'starter')).toThrow('blocked') })
  it('allows advisory axe evidence but blocks serious axe evidence', () => { const scenario = enumerateGovernanceScenarios(bindings, new Set(['fg','bg']))[0]; const fact = { scenarioId:scenario.scenarioId, viewport:'mobile', foreground:'rgb(0,0,0)', backgroundLayers:['rgb(255,255,255)'], fontSizePx:16, fontWeight:400, outlineWidthPx:0, nonColorCue:true, axeViolations:[{id:'region',impact:'moderate' as const}] }; expect(evaluateGovernance([scenario],[fact],1).status).toBe('advisory'); expect(evaluateGovernance([scenario],[{...fact,axeViolations:[{id:'name',impact:'serious' as const}]}],1).status).toBe('blocked') })
  it('requires approval before a brand-lock repair and emits rerun receipt', async () => { const scenario = enumerateGovernanceScenarios(bindings, new Set(['fg','bg']))[0]; const blocked = evaluateGovernance([scenario],[],1); const task = createGovernanceRepairTask(blocked,[scenario]); expect(task.requiresHumanApproval).toBe(true); const repair = vi.fn(); expect((await rerunGovernanceRepair(task,{repair,rerun:async()=>blocked})).status).toBe('approval-required'); const passed = evaluateGovernance([scenario],[{scenarioId:scenario.scenarioId,viewport:'desktop',foreground:'rgb(0,0,0)',backgroundLayers:['rgb(255,255,255)'],fontSizePx:16,fontWeight:400,outlineWidthPx:0,nonColorCue:true,axeViolations:[]}],2); const result = await rerunGovernanceRepair(task,{approvalId:'approval:1',repair:async()=>({receiptRef:'repair:receipt'}),rerun:async()=>passed}); expect(result.status).toBe('repaired'); expect(result.repairReceiptRef).toBe('repair:receipt') })
  it.each(['brand-kit','design-system-kit','component','starter','figma','delivery'] as const)('guards %s promotion', (target) => { const scenario = enumerateGovernanceScenarios(bindings,new Set(['fg','bg']))[0]; expect(()=>assertGovernancePromotion(evaluateGovernance([scenario],[],1),target)).toThrow() })
})
