import{describe,expect,it}from'vitest';import type{DesignDocument}from'@/design-ir';import{governDesignDocument,runDesignGovernance,type StandardGovernancePolicy,type StandardGovernanceToken}from'.';import{composite,contrastRatio,deltaE,normalizeSrgb,parseCssColor}from'./color'
const at='2026-07-12T00:00:00.000Z',loc={entityId:'component.button',path:'styles.default'}
const policy:StandardGovernancePolicy={version:'design-governance-policy.v1',id:'policy.default',standards:{wcag:'2.2',dtcg:'2025.10',cssColor:'4'},severity:{},thresholds:{perceptualDeltaE:5,spacingBase:4,maxMotionMs:500,minFocusArea:4}}
describe('governance measurement harness',()=>{
 it('parses CSS Color 4, composites alpha and preserves measurement invariants',()=>{expect(normalizeSrgb(parseCssColor('color(display-p3 1 0 0)'))).toMatch(/^rgb\(/);expect(normalizeSrgb(parseCssColor('oklch(62.8% 0.258 29.23)'))).toMatch(/^rgb\(/);expect(composite(parseCssColor('rgb(255 0 0 / 0.5)'),parseCssColor('#000')).r).toBeCloseTo(.5);expect(contrastRatio(parseCssColor('#000'),parseCssColor('#fff'))).toBeCloseTo(21,5);expect(deltaE(parseCssColor('#000'),parseCssColor('#000'))).toBe(0)})
 it('matches CSS Color 4 known neutral values and normalizes equivalent hue angles',()=>{const p3White=parseCssColor('color(display-p3 1 1 1)');expect(p3White.r).toBeCloseTo(1,3);expect(p3White.g).toBeCloseTo(1,3);expect(p3White.b).toBeCloseTo(1,3);expect(normalizeSrgb(parseCssColor('oklch(100% 0 0)'))).toBe('rgb(255 255 255)');expect(deltaE(parseCssColor('oklch(60% 0.2 -30deg)'),parseCssColor('oklch(60% 0.2 330deg)'))).toBeCloseTo(0,8);expect(deltaE(parseCssColor('oklch(60% 0.2 0.5turn)'),parseCssColor('oklch(60% 0.2 180deg)'))).toBeCloseTo(0,8)})
 it('validates explicit token graph tiers, cycles and approved brand locks',()=>{const tokens:StandardGovernanceToken[]=[{id:'primitive.brand',name:'Brand',type:'color',tier:'primitive',value:'#f00',mode:'light',brandLock:{approvedValue:'#00f',approvalId:'approval.brand'},location:loc},{id:'semantic.action',name:'Action',type:'color',tier:'semantic',alias:'component.button',mode:'light',location:loc},{id:'component.button',name:'Button',type:'color',tier:'component',alias:'semantic.action',mode:'light',location:loc}];const report=runDesignGovernance({documentId:'d',revisionId:'r',tokens,samples:[],completedAt:at},policy);expect(report.findings.map((f)=>f.ruleId)).toEqual(expect.arrayContaining(['brand.approved-lock','dtcg.alias.direction','dtcg.alias.cycle']))})
 it('keeps aesthetic and perceptual scoring advisory while WCAG measurements block',()=>{const report=runDesignGovernance({documentId:'d',revisionId:'r',tokens:[],samples:[{kind:'text',id:'t',foreground:'#777',background:'#fff',fontSizePx:16,fontWeight:400,location:loc},{kind:'harmony',id:'h',score:.1,rationale:'Needs human review.',location:loc}],completedAt:at},policy);expect(report.summary.blocking).toBe(true);expect(report.findings.find((f)=>f.ruleId==='aesthetic.harmony')).toMatchObject({severity:'advisory',blocking:false});expect(report.findings.every((f)=>f.evidence.length&&f.repairSuggestions.length)).toBe(true)})
 it('adapts authoritative Design IR only through explicit declarations',()=>{const document:DesignDocument={version:'design-ir.v1',meta:{id:'design.one',title:'Design',createdAt:at,updatedAt:at},revision:{id:'revision.one',number:1,createdAt:at,author:{kind:'human',id:'user.one'}},needs:[],sources:[],brands:[],tokens:[{id:'token.brand',name:'Brand',kind:'color',value:'#f00'}],components:[],materials:[],provenance:[],relations:[]};expect(governDesignDocument(document,[{tokenId:'token.brand',type:'color',tier:'primitive',location:loc}],[],policy,at)).toMatchObject({documentId:'design.one',revisionId:'revision.one'});expect(()=>governDesignDocument(document,[{tokenId:'missing',type:'color',tier:'primitive',location:loc}],[],policy,at)).toThrow('unknown Design IR token')})
})
