import{describe,expect,it,vi}from'vitest'
import{ExternalSurfaceBridge,surfaceAvailability,surfaceHandshakeSchema,type ExternalSurfaceHost,type SurfaceHandshake,type SurfacePlan}from'./external-surfaces'
const at='2026-07-12T00:00:00.000Z',later='2026-07-13T00:00:00.000Z',hash='a'.repeat(64)
function handshake(kind:SurfaceHandshake['kind'],capabilities:SurfaceHandshake['capabilities']=['preview','write']):SurfaceHandshake{return{protocol:'cutout.surface-handshake.v1',hostId:'host.one',kind,sessionId:'session.one',foreground:!['pencil-cli','canva-connect-api'].includes(kind),capabilities,expiresAt:later,hostVersion:'1.0.0'}}
function plan(kind:SurfaceHandshake['kind']):SurfacePlan{const base={protocol:'cutout.surface-plan.v1' as const,id:'plan.one',baseRevision:'base.one',requiresApproval:true as const};if(kind==='obsidian-vault-plugin')return{...base,kind,files:[{path:'Design/guide.md',sha256:hash,operation:'create'}]};if(kind==='pencil-mcp'||kind==='pencil-cli')return{...base,kind,penSchemaVersion:'2026.1',targetSchemaVersion:'2026.2',migrationRequired:true,operations:[{tool:'batch_design',inputHash:hash}]};if(kind==='paper-desktop-mcp')return{...base,kind,documentRef:'paper.open',operations:[{tool:'paper.write',inputHash:hash}]};if(kind==='framer-editor-plugin')return{...base,kind,stagingId:'stage.one',operations:[{nodeRef:'node.one',operation:'update',payloadHash:hash}],publish:{requested:true,siteRef:'site.one'}};if(kind==='canva-apps-sdk')return{...base,kind,designRef:'design.one',operations:[{pageRef:'page.one',operation:'add',payloadHash:hash}]};return{...base,kind:'canva-connect-api',designRef:'design.one',operation:'export',userInteractionRequired:true}}
function host(session:SurfaceHandshake):ExternalSurfaceHost{const make=(p:SurfacePlan,approvalId?:string)=>({protocol:'cutout.surface-receipt.v1' as const,planId:p.id,hostId:session.hostId,sessionId:session.sessionId,kind:p.kind,status:approvalId?'succeeded' as const:'no-op' as const,baseRevision:p.baseRevision,...(approvalId?{resultRevision:'revision.two',approvalId}:{}),evidence:[],completedAt:at});return{handshake:vi.fn(async()=>session),preview:vi.fn(async(p)=>make(p)),apply:vi.fn(async(p,a)=>make(p,a))}}
describe('official external surface bridges',()=>{
 it('keeps foreground plugin surfaces unavailable until a matching handshake',async()=>{const session=handshake('obsidian-vault-plugin'),bridge=new ExternalSurfaceBridge(host(session),()=>at);expect(surfaceAvailability(session.kind)).toBe('host-required');await expect(bridge.preview(plan(session.kind))).rejects.toThrow('handshake');expect(surfaceAvailability(session.kind,await bridge.connect())).toBe('available');expect((await bridge.apply(plan(session.kind),'approval.one')).status).toBe('succeeded')})
 it('rejects non-foreground Obsidian, Paper, Framer and Canva Apps SDK hosts',()=>{for(const kind of ['obsidian-vault-plugin','paper-desktop-mcp','framer-editor-plugin','canva-apps-sdk']as const)expect(()=>surfaceHandshakeSchema.parse({...handshake(kind),foreground:false})).toThrow('foreground')})
 it('requires explicit .pen migration capability before Pencil writes',async()=>{const session=handshake('pencil-cli',['preview','write']),bridge=new ExternalSurfaceBridge(host(session),()=>at);await bridge.connect();await expect(bridge.apply(plan('pencil-cli'),'approval.one')).rejects.toThrow('migration')})
 it('separates Canva foreground Apps SDK from Connect API publishing',()=>{expect(()=>surfaceHandshakeSchema.parse({...handshake('canva-apps-sdk'),capabilities:['preview','write','publish']})).toThrow('impersonate Connect API')})
 it('requires Framer staging publish capability and approval',async()=>{const session=handshake('framer-editor-plugin',['preview','write']),bridge=new ExternalSurfaceBridge(host(session),()=>at);await bridge.connect();await expect(bridge.apply(plan('framer-editor-plugin'),'approval.one')).rejects.toThrow('adapter-required');await expect(bridge.apply(plan('framer-editor-plugin'),'')).rejects.toThrow('approval')})
})
