import { z } from 'zod'

const safe=z.string().min(1).max(240).refine((v)=>!/(?:token|secret|api[-_]?key|authorization)\s*[:=]/i.test(v)), path=z.string().min(1).max(512).refine((v)=>!v.startsWith('/')&&!v.includes('\\')&&v.split('/').every((p)=>p&&p!=='.'&&p!=='..')), sha=z.string().regex(/^[a-f0-9]{64}$/)
export const externalSurfaceKindSchema=z.enum(['obsidian-vault-plugin','pencil-mcp','pencil-cli','paper-desktop-mcp','framer-editor-plugin','canva-apps-sdk','canva-connect-api'])
export const surfaceHandshakeSchema=z.object({protocol:z.literal('cutout.surface-handshake.v1'),hostId:safe,kind:externalSurfaceKindSchema,sessionId:safe,foreground:z.boolean(),capabilities:z.array(z.enum(['read','preview','write','export','stage','publish','migrate'])),expiresAt:z.string().datetime(),hostVersion:safe}).strict().superRefine((v,ctx)=>{if(['obsidian-vault-plugin','paper-desktop-mcp','framer-editor-plugin','canva-apps-sdk'].includes(v.kind)&&!v.foreground)ctx.addIssue({code:'custom',message:`${v.kind} requires a foreground host.`});if(v.kind==='canva-apps-sdk'&&v.capabilities.includes('publish'))ctx.addIssue({code:'custom',message:'Canva Apps SDK editor sessions must not impersonate Connect API publishing.'})})
export type SurfaceHandshake=z.infer<typeof surfaceHandshakeSchema>
export const surfacePlanSchema=z.discriminatedUnion('kind',[
 z.object({protocol:z.literal('cutout.surface-plan.v1'),id:safe,kind:z.literal('obsidian-vault-plugin'),baseRevision:safe,files:z.array(z.object({path,sha256:sha,operation:z.enum(['create','update'])}).strict()),requiresApproval:z.literal(true)}).strict(),
 z.object({protocol:z.literal('cutout.surface-plan.v1'),id:safe,kind:z.enum(['pencil-mcp','pencil-cli']),baseRevision:safe,penSchemaVersion:safe,targetSchemaVersion:safe,migrationRequired:z.boolean(),operations:z.array(z.object({tool:safe,inputHash:sha}).strict()),requiresApproval:z.literal(true)}).strict(),
 z.object({protocol:z.literal('cutout.surface-plan.v1'),id:safe,kind:z.literal('paper-desktop-mcp'),baseRevision:safe,documentRef:safe,operations:z.array(z.object({tool:safe,inputHash:sha}).strict()),requiresApproval:z.literal(true)}).strict(),
 z.object({protocol:z.literal('cutout.surface-plan.v1'),id:safe,kind:z.literal('framer-editor-plugin'),baseRevision:safe,stagingId:safe,operations:z.array(z.object({nodeRef:safe,operation:z.enum(['create','update','delete']),payloadHash:sha}).strict()),publish:z.object({requested:z.boolean(),siteRef:safe.optional()}).strict(),requiresApproval:z.literal(true)}).strict(),
 z.object({protocol:z.literal('cutout.surface-plan.v1'),id:safe,kind:z.literal('canva-apps-sdk'),baseRevision:safe,designRef:safe,operations:z.array(z.object({pageRef:safe,operation:z.enum(['add','update','remove']),payloadHash:sha}).strict()),requiresApproval:z.literal(true)}).strict(),
 z.object({protocol:z.literal('cutout.surface-plan.v1'),id:safe,kind:z.literal('canva-connect-api'),baseRevision:safe,designRef:safe,operation:z.enum(['import','export','publish']),userInteractionRequired:z.boolean(),requiresApproval:z.literal(true)}).strict(),
])
export type SurfacePlan=z.infer<typeof surfacePlanSchema>
export const surfaceReceiptSchema=z.object({protocol:z.literal('cutout.surface-receipt.v1'),planId:safe,hostId:safe,sessionId:safe,kind:externalSurfaceKindSchema,status:z.enum(['succeeded','no-op','conflict','capability-required']),baseRevision:safe,resultRevision:safe.optional(),approvalId:safe.optional(),evidence:z.array(z.object({id:safe,sha256:sha.optional(),summary:z.string().max(1000)}).strict()),completedAt:z.string().datetime()}).strict().superRefine((v,ctx)=>{if(v.status==='succeeded'&&(!v.approvalId||!v.resultRevision))ctx.addIssue({code:'custom',message:'Successful writes require approval and result revision evidence.'})})
export type SurfaceReceipt=z.infer<typeof surfaceReceiptSchema>
export interface ExternalSurfaceHost{handshake(signal:AbortSignal):Promise<SurfaceHandshake>;preview(plan:SurfacePlan,signal:AbortSignal):Promise<SurfaceReceipt>;apply(plan:SurfacePlan,approvalId:string,signal:AbortSignal):Promise<SurfaceReceipt>}
export class ExternalSurfaceBridge{
 readonly host:ExternalSurfaceHost;readonly now:()=>string;#session?:SurfaceHandshake
 constructor(host:ExternalSurfaceHost,now:()=>string=()=>new Date().toISOString()){this.host=host;this.now=now}
 async connect(signal=new AbortController().signal){this.#session=surfaceHandshakeSchema.parse(await this.host.handshake(signal));return this.#session}
 async preview(input:unknown,signal=new AbortController().signal){const plan=surfacePlanSchema.parse(input),session=this.require(plan.kind,'preview');const receipt=surfaceReceiptSchema.parse(await this.host.preview(plan,signal));verify(receipt,plan,session,false);return receipt}
 async apply(input:unknown,approvalId:string,signal=new AbortController().signal){const plan=surfacePlanSchema.parse(input);if(!approvalId.trim())throw new Error('Explicit approval id is required.');const session=this.require(plan.kind,plan.kind==='framer-editor-plugin'&&plan.publish.requested?'publish':'write');if(plan.kind==='pencil-mcp'||plan.kind==='pencil-cli')if(plan.migrationRequired&&!session.capabilities.includes('migrate'))throw new Error('Pencil host requires a versioned .pen migration capability.');if(plan.kind==='canva-connect-api'&&plan.userInteractionRequired&&!session.foreground)throw new Error('Canva operation requires user interaction in an authorized foreground flow.');const receipt=surfaceReceiptSchema.parse(await this.host.apply(plan,approvalId,signal));verify(receipt,plan,session,true);return receipt}
 private require(kind:SurfaceHandshake['kind'],capability:SurfaceHandshake['capabilities'][number]){const session=this.#session;if(!session||session.kind!==kind||session.expiresAt<=this.now())throw new Error('A current matching host handshake is required.');if(!session.capabilities.includes(capability))throw new Error(`${kind} capability is adapter-required: ${capability}.`);return session}
}
function verify(receipt:SurfaceReceipt,plan:SurfacePlan,session:SurfaceHandshake,applied:boolean){if(receipt.planId!==plan.id||receipt.kind!==plan.kind||receipt.hostId!==session.hostId||receipt.sessionId!==session.sessionId||receipt.baseRevision!==plan.baseRevision)throw new Error('Surface host returned a receipt for another plan or session.');if(applied&&receipt.status==='succeeded'&&!receipt.approvalId)throw new Error('Surface apply receipt lacks approval evidence.')}
export function surfaceAvailability(kind:SurfaceHandshake['kind'],handshake?:SurfaceHandshake){return handshake?.kind===kind?'available' as const:'host-required' as const}
