import{z}from'zod'
const safe=z.string().min(1).max(240),sha=z.string().regex(/^[a-f0-9]{64}$/),relative=z.string().min(1).refine((v)=>!v.startsWith('/')&&!v.includes('\\')&&v.split('/').every((p)=>p&&p!=='.'&&p!=='..'))
export const figmaPluginManifest={name:'Cutout Bridge',id:'cutout-bridge',api:'1.0.0',editorType:['figma'],main:'dist/code.js',ui:'dist/ui.html',documentAccess:'dynamic-page',networkAccess:{allowedDomains:['none']}}as const
const layout=z.object({layoutMode:z.enum(['NONE','HORIZONTAL','VERTICAL','GRID']).optional(),paddingTop:z.number().nonnegative().optional(),paddingRight:z.number().nonnegative().optional(),paddingBottom:z.number().nonnegative().optional(),paddingLeft:z.number().nonnegative().optional(),itemSpacing:z.number().optional(),primaryAxisSizingMode:z.enum(['FIXED','AUTO']).optional(),counterAxisSizingMode:z.enum(['FIXED','AUTO']).optional(),layoutGrow:z.number().nonnegative().optional(),layoutAlign:z.enum(['INHERIT','STRETCH']).optional()}).strict()
export const figmaNodeOperationSchema=z.discriminatedUnion('operation',[
 z.object({operation:z.literal('set-auto-layout'),nodeId:safe,expectedType:z.enum(['FRAME','COMPONENT','COMPONENT_SET','INSTANCE']),beforeHash:sha,layout}).strict(),
 z.object({operation:z.literal('set-properties'),nodeId:safe,expectedType:z.enum(['FRAME','TEXT','RECTANGLE','COMPONENT','COMPONENT_SET','INSTANCE']),beforeHash:sha,properties:z.record(z.string(),z.union([z.string(),z.number(),z.boolean()]))}).strict(),
 z.object({operation:z.literal('combine-variants'),nodeIds:z.array(safe).min(2),parentId:safe,beforeHashes:z.array(sha).min(2),name:safe}).strict(),
])
export const figmaPatchPlanSchema=z.object({protocol:z.literal('cutout.figma-plugin-plan.v1'),id:safe,fileKeyHash:sha,pageIds:z.array(safe).min(1).max(1_000),operations:z.array(figmaNodeOperationSchema).min(1).max(5_000),createdAt:z.string().datetime(),requiresApproval:z.literal(true)}).strict()
export type FigmaPatchPlan=z.infer<typeof figmaPatchPlanSchema>
export const figmaPreflightSchema=z.object({protocol:z.literal('cutout.figma-plugin-preflight.v1'),planId:safe,sessionId:safe,status:z.enum(['ready','conflict']),loadedPageIds:z.array(safe),fonts:z.array(z.object({family:safe,style:safe,status:z.enum(['loaded','missing'])}).strict()),nodes:z.array(z.object({nodeId:safe,expectedType:safe,actualType:safe,currentHash:sha,status:z.enum(['ready','missing','type-conflict','revision-conflict'])}).strict()),warnings:z.array(z.string()),previewHash:sha}).strict()
export type FigmaPreflight=z.infer<typeof figmaPreflightSchema>
export const figmaApplyReceiptSchema=z.object({protocol:z.literal('cutout.figma-plugin-receipt.v1'),planId:safe,sessionId:safe,previewHash:sha,approvalId:safe,status:z.enum(['succeeded','conflict','cancelled']),resultNodes:z.array(z.object({nodeId:safe,beforeHash:sha,afterHash:sha,operation:safe}).strict()),conflicts:z.array(z.object({nodeId:safe,kind:z.enum(['missing','type','revision','font','variant-parent']),summary:z.string()}).strict()),undoBoundaryCommitted:z.boolean(),completedAt:z.string().datetime()}).strict().superRefine((v,ctx)=>{if(v.status==='succeeded'&&(v.conflicts.length||!v.undoBoundaryCommitted))ctx.addIssue({code:'custom',message:'Successful Figma apply requires an undo boundary and no conflicts.'})})
export interface FigmaForegroundHost{handshake(signal:AbortSignal):Promise<{sessionId:string;foreground:true;expiresAt:string;editorType:'figma'}>;preflight(plan:FigmaPatchPlan,signal:AbortSignal):Promise<FigmaPreflight>;apply(plan:FigmaPatchPlan,previewHash:string,approvalId:string,signal:AbortSignal):Promise<z.infer<typeof figmaApplyReceiptSchema>>;close(message:string):Promise<void>}
export class FigmaPluginBridge{#session?:Awaited<ReturnType<FigmaForegroundHost['handshake']>>;#previews=new Map<string,FigmaPreflight>();readonly host:FigmaForegroundHost;readonly now:()=>string;constructor(host:FigmaForegroundHost,now:()=>string=()=>new Date().toISOString()){this.host=host;this.now=now}async connect(signal=new AbortController().signal){const session=await this.host.handshake(signal);if(!session.foreground||session.editorType!=='figma')throw new Error('Figma bridge requires a foreground Figma Design plugin session.');this.#session=session;return session}async preview(input:unknown,signal=new AbortController().signal){const plan=figmaPatchPlanSchema.parse(input),session=this.require();const preview=figmaPreflightSchema.parse(await this.host.preflight(plan,signal));if(preview.planId!==plan.id||preview.sessionId!==session.sessionId)throw new Error('Figma preflight belongs to another plan or session.');this.#previews.set(plan.id,preview);return preview}async apply(input:unknown,approvalId:string,signal=new AbortController().signal){const plan=figmaPatchPlanSchema.parse(input),session=this.require(),preview=this.#previews.get(plan.id);if(!approvalId.trim())throw new Error('Explicit approval id is required.');if(!preview||preview.status!=='ready')throw new Error('A conflict-free Figma preflight is required.');const receipt=figmaApplyReceiptSchema.parse(await this.host.apply(plan,preview.previewHash,approvalId,signal));if(receipt.planId!==plan.id||receipt.sessionId!==session.sessionId||receipt.previewHash!==preview.previewHash||receipt.approvalId!==approvalId)throw new Error('Figma apply receipt does not match the approved preflight.');await this.host.close(receipt.status==='succeeded'?'Cutout changes applied.':'Cutout changes were not applied.');this.#session=undefined;return receipt}private require(){if(!this.#session||this.#session.expiresAt<=this.now())throw new Error('A current user-invoked Figma plugin session is required.');return this.#session}}
export const codeConnectPlanSchema=z.object({protocol:z.literal('cutout.code-connect-plan.v1'),id:safe,figmaFileUrl:z.string().url(),componentMappings:z.array(z.object({figmaNodeUrl:z.string().url(),sourcePath:relative,exportName:safe,props:z.record(z.string(),z.string())}).strict()).min(1),files:z.array(z.object({path:relative.regex(/\.figma\.[jt]sx?$/),sha256:sha}).strict()).min(1),command:z.object({executable:z.literal('npx'),args:z.array(z.string()).refine((a)=>a[0]==='figma'&&a[1]==='connect'&&a[2]==='publish')}).strict(),requiresUserSeat:z.literal(true),requiresApproval:z.literal(true)}).strict()
export type CodeConnectPlan=z.infer<typeof codeConnectPlanSchema>
