import{describe,expect,it,vi}from'vitest'
import{codeConnectPlanSchema,FigmaPluginBridge,figmaPluginManifest,type FigmaForegroundHost,type FigmaPatchPlan}from'./figma-plugin'
const at='2026-07-12T00:00:00.000Z',later='2026-07-13T00:00:00.000Z',hash='a'.repeat(64),after='b'.repeat(64)
const plan:FigmaPatchPlan={protocol:'cutout.figma-plugin-plan.v1',id:'plan.one',fileKeyHash:hash,pageIds:['page.one'],operations:[{operation:'set-auto-layout',nodeId:'1:2',expectedType:'FRAME',beforeHash:hash,layout:{layoutMode:'HORIZONTAL',itemSpacing:12}}],createdAt:at,requiresApproval:true}
function host(status:'ready'|'conflict'='ready'):FigmaForegroundHost{return{handshake:vi.fn(async()=>({sessionId:'session.one',foreground:true as const,expiresAt:later,editorType:'figma' as const})),preflight:vi.fn(async()=>({protocol:'cutout.figma-plugin-preflight.v1' as const,planId:plan.id,sessionId:'session.one',status,loadedPageIds:['page.one'],fonts:[],nodes:[{nodeId:'1:2',expectedType:'FRAME',actualType:'FRAME',currentHash:hash,status:status==='ready'?'ready' as const:'revision-conflict' as const}],warnings:[],previewHash:hash})),apply:vi.fn(async(_p,previewHash,approvalId)=>({protocol:'cutout.figma-plugin-receipt.v1' as const,planId:plan.id,sessionId:'session.one',previewHash,approvalId,status:'succeeded' as const,resultNodes:[{nodeId:'1:2',beforeHash:hash,afterHash:after,operation:'set-auto-layout'}],conflicts:[],undoBoundaryCommitted:true,completedAt:at})),close:vi.fn()}}
describe('Figma foreground plugin bridge',()=>{
 it('ships a dynamic-page, network-disabled foreground plugin manifest',()=>{expect(figmaPluginManifest).toMatchObject({editorType:['figma'],documentAccess:'dynamic-page',networkAccess:{allowedDomains:['none']}})})
 it('binds apply to the approved preflight and closes the short-lived plugin session',async()=>{const adapter=host(),bridge=new FigmaPluginBridge(adapter,()=>at);await bridge.connect();expect((await bridge.preview(plan)).status).toBe('ready');expect((await bridge.apply(plan,'approval.one')).status).toBe('succeeded');expect(adapter.close).toHaveBeenCalledOnce();await expect(bridge.preview(plan)).rejects.toThrow('user-invoked')})
 it('blocks apply when node revision/type/font preflight has conflicts',async()=>{const bridge=new FigmaPluginBridge(host('conflict'),()=>at);await bridge.connect();await bridge.preview(plan);await expect(bridge.apply(plan,'approval.one')).rejects.toThrow('conflict-free')})
 it('models Code Connect as an approved CLI mapping publish plan, not node publication',()=>{const parsed=codeConnectPlanSchema.parse({protocol:'cutout.code-connect-plan.v1',id:'cc.one',figmaFileUrl:'https://www.figma.com/design/file',componentMappings:[{figmaNodeUrl:'https://www.figma.com/design/file?node-id=1-2',sourcePath:'src/Button.tsx',exportName:'Button',props:{disabled:'disabled'}}],files:[{path:'src/Button.figma.tsx',sha256:hash}],command:{executable:'npx',args:['figma','connect','publish']},requiresUserSeat:true,requiresApproval:true});expect(parsed.command.args).toEqual(['figma','connect','publish']);expect(JSON.stringify(parsed)).not.toContain('publish-node')})
})
