import{describe,expect,it,vi}from'vitest';import{OAuthConnectionController,type OAuthDesktopHost}from'./oauth'
const at='2026-07-12T00:00:00.000Z',later='2026-07-13T00:00:00.000Z'
function session(provider='github'){return{id:'session.one',integrationId:`cutout.${provider}`,surface:'desktop' as const,authMode:'oauth2' as const,secretHandle:{kind:'secret-handle' as const,id:'opaque.one',provider,sessionId:'session.one'},scopes:['read'],createdAt:at,expiresAt:later}}
function host(overrides:Partial<OAuthDesktopHost>={}):OAuthDesktopHost{return{begin:vi.fn(async()=>({requestId:'request.one',authorizationUrl:'https://github.com/login/oauth/authorize',callbackScheme:'cutout://oauth/callback',expiresAt:later})),complete:vi.fn(async()=>session()),refresh:vi.fn(async()=>session()),revoke:vi.fn(),...overrides}}
describe('desktop OAuth connection E2E',()=>{
 it('runs begin, callback, refresh and revoke with only opaque session state',async()=>{const fake=host(),controller=new OAuthConnectionController(fake,()=>at);expect(controller.state('cutout.github','github').status).toBe('disconnected');expect((await controller.begin('cutout.github','github',['read'])).status).toBe('authorizing');expect((await controller.callback('cutout.github','cutout://oauth/callback?code=host-owned')).status).toBe('connected');expect((await controller.refresh('cutout.github')).status).toBe('connected');expect((await controller.disconnect('cutout.github')).status).toBe('disconnected');expect(JSON.stringify(controller.state('cutout.github','github'))).not.toContain('host-owned');expect(fake.revoke).toHaveBeenCalledWith('session.one',expect.any(AbortSignal))})
 it('is production-disabled without an injected desktop provider',async()=>{const controller=new OAuthConnectionController();expect(controller.state('cutout.github','github').status).toBe('disabled');await expect(controller.begin('cutout.github','github',[])).rejects.toThrow('disabled')})
 it('rejects callback scheme and provider/session substitution',async()=>{const controller=new OAuthConnectionController(host({complete:vi.fn(async()=>session('notion'))}),()=>at);await controller.begin('cutout.github','github',[]);await expect(controller.callback('cutout.github','https://attacker.invalid/callback')).rejects.toThrow('scheme');expect((await controller.callback('cutout.github','cutout://oauth/callback?code=opaque')).status).toBe('error')})
 it('rejects refresh that changes session identity',async()=>{const controller=new OAuthConnectionController(host({refresh:vi.fn(async()=>({...session(),id:'session.two',secretHandle:{...session().secretHandle,sessionId:'session.two'}}))}),()=>at);await controller.begin('cutout.github','github',[]);await controller.callback('cutout.github','cutout://oauth/callback');expect((await controller.refresh('cutout.github')).status).toBe('error')})
})
