import{describe,expect,it,vi}from'vitest'
import{IntegrationSessionBroker,hostSessionSchema,type DesktopSessionHost}from'./sessions'
const at='2026-07-12T00:00:00.000Z'
function session(overrides={}){return{id:'session.one',integrationId:'cutout.github',surface:'desktop' as const,authMode:'oauth2' as const,secretHandle:{kind:'secret-handle' as const,id:'opaque.7f3c',provider:'github',sessionId:'session.one'},scopes:['contents:read'],createdAt:at,...overrides}}
describe('host-owned integration sessions',()=>{
 it('accepts only opaque provider-bound handles and never credential-shaped values',()=>{expect(hostSessionSchema.parse(session()).secretHandle?.id).toBe('opaque.7f3c');expect(()=>hostSessionSchema.parse(session({secretHandle:{kind:'secret-handle',id:'token=real-secret-value',provider:'github',sessionId:'session.one'}}))).toThrow('Credential-shaped')})
 it('binds host sessions to integration, provider and surface',async()=>{const host={authorize:vi.fn(async()=>session()),revoke:vi.fn()}satisfies DesktopSessionHost;const broker=new IntegrationSessionBroker(host,()=>at);const connected=await broker.connect({integrationId:'cutout.github',provider:'github',authMode:'oauth2',scopes:['contents:read'],surface:'desktop'});expect(broker.resolve(connected.id,'cutout.github','desktop').secretHandle?.id).toBe('opaque.7f3c');expect(()=>broker.resolve(connected.id,'cutout.notion','desktop')).toThrow('boundary')})
 it('rejects expired and revoked sessions without exposing secret material',async()=>{const host={authorize:vi.fn(async()=>session({expiresAt:'2026-07-13T00:00:00.000Z'})),revoke:vi.fn()}satisfies DesktopSessionHost;let now=at;const broker=new IntegrationSessionBroker(host,()=>now);await broker.connect({integrationId:'cutout.github',provider:'github',authMode:'oauth2',scopes:[],surface:'desktop'});now='2026-07-14T00:00:00.000Z';expect(()=>broker.resolve('session.one','cutout.github','desktop')).toThrow('expired');now=at;await broker.disconnect('session.one');expect(()=>broker.resolve('session.one','cutout.github','desktop')).toThrow('revoked')})
})
