import {describe,expect,it,vi} from 'vitest'
import type {RegistryItem} from '@/registry'
import {ComponentLibrary,componentLibraryProfileSchema,type ComponentLibraryProfile,type RegistryInstallerHost} from '.'
const at='2026-07-12T00:00:00.000Z',hash='a'.repeat(64)
const item:RegistryItem={schemaVersion:'cutout.registry-item.v1',id:'cutout.button',version:'1.0.0',kind:'component',metadata:{name:'Button',description:'Action control.',tags:['button']},files:[{path:'Button.tsx',mediaType:'text/typescript',size:1,sha256:hash,role:'source'}],designIrRefs:[],tokenRefs:['color.action'],dependencies:[],frameworks:[{id:'vite-react',role:'target'}],provenance:[{id:'source.one',source:'generated',capturedAt:at,actor:'agent'}],license:{kind:'spdx',identifier:'MIT'},qualityReceipts:[],previewAssets:[]}
function profile(overrides:Partial<ComponentLibraryProfile>={}):ComponentLibraryProfile{return{protocol:'cutout.component-library.v1',item,stories:[{id:'story.default',name:'Default',exampleIds:['example.default'],stateIds:['state.default']}],examples:[{id:'example.default',title:'Default',sourcePath:'Button.story.tsx',sourceSha256:hash}],variants:[{name:'size',values:['sm','md'],defaultValue:'md'}],states:[{id:'state.default',label:'Default',variantValues:{size:'md'},pseudo:'none',interactive:true}],props:[{name:'disabled',type:'boolean',required:false,defaultValue:'false',description:'Disables activation.'}],slots:[{name:'default',required:true,description:'Button label.',accepts:['text']}],accessibility:{roles:['button'],keyboard:[{key:'Enter',action:'activate'}],requirements:['Visible focus'],evidenceIds:['a11y.button']},tokenBindings:[{property:'background',tokenRef:'color.action',required:true}],frameworkCompatibility:[{framework:'vite-react',range:'>=5',status:'verified',evidenceIds:['test.consumer']}],lifecycle:{status:'active'},collections:['actions'],updatedAt:at,...overrides}}
describe('ComponentLibrary',()=>{
 it('validates stories, examples, state matrix and exact installed origin',()=>{expect(componentLibraryProfileSchema.parse(profile()).states).toHaveLength(1);expect(()=>componentLibraryProfileSchema.parse(profile({states:[{id:'state.bad',label:'Bad',variantValues:{size:'xl'},pseudo:'none',interactive:true}]}))).toThrow('unknown variant');expect(()=>componentLibraryProfileSchema.parse(profile({installedOrigin:{projectId:'p',itemId:item.id,version:'2.0.0',installedAt:at,files:[]}}))).toThrow('exact Registry')})
 it('searches by collection, verified framework, lifecycle and installed state',()=>{const library=new ComponentLibrary();library.upsert(profile({installedOrigin:{projectId:'p',itemId:item.id,version:item.version,installedAt:at,files:[{path:'Button.tsx',baseHash:hash}]}}));expect(library.search({text:'button',collection:'actions',framework:'vite-react',status:'active',installed:true})).toHaveLength(1);expect(library.search({framework:'next'})).toHaveLength(0)})
 it('requires replacement for deprecation and blocks installation of non-active versions',async()=>{expect(()=>componentLibraryProfileSchema.parse(profile({lifecycle:{status:'deprecated',reason:'Use Button2'}}))).toThrow('replacement');const library=new ComponentLibrary();library.upsert(profile({lifecycle:{status:'deprecated',reason:'Renamed',replacement:{itemId:'cutout.button2',version:'2.0.0'}}}));const installer={plan:vi.fn()} as unknown as RegistryInstallerHost;await expect(library.planInstall(installer,{item,files:[]},'vite-react')).rejects.toThrow('use cutout.button2@2.0.0');expect(library.replacement(item)).toEqual({itemId:'cutout.button2',version:'2.0.0'})})
 it('delegates three-way install planning to the injected Registry host and reports browser capability absence',async()=>{const library=new ComponentLibrary();library.upsert(profile());const plan={protocol:'cutout.registry-install-plan.v1',id:'install.one',itemId:item.id,itemVersion:item.version,targetFramework:'vite-react',files:[],conflicts:['Button.tsx'],requiresApproval:true} as const;const installer={plan:vi.fn(async()=>plan)} satisfies RegistryInstallerHost;expect(await library.planInstall(installer,{item,files:[]},'vite-react')).toBe(plan);expect(installer.plan).toHaveBeenCalledOnce();await expect(library.planInstall(undefined,{item,files:[]},'vite-react')).rejects.toThrow('capability is required');await expect(library.planInstall(installer,{item,files:[]},'next')).rejects.toThrow('not verified')})
})
