import { describe,expect,it } from 'vitest'
import { IDBFactory } from 'fake-indexeddb'
import type { GlobalLibraryCatalog,GlobalLibraryItem } from './contracts'
import { createIndexedDbGlobalLibraryBackend } from './indexeddb'
import { computeLibraryContentHash,GlobalLibraryStore,migrateGlobalLibraryCatalog,type GlobalLibraryBackend } from './store'
const at='2026-07-12T00:00:00.000Z';const later='2026-07-13T00:00:00.000Z'
async function item(id='kit.alpha',version='1.0.0',overrides:Partial<GlobalLibraryItem>={}):Promise<GlobalLibraryItem>{const digest=version==='1.0.0'?'a'.repeat(64):'b'.repeat(64);const content={manifestPath:'manifest.json',manifestSha256:digest,artifacts:[{path:'manifest.json',sha256:digest,mediaType:'application/json',size:12}]};const hash=await computeLibraryContentHash(content);return{protocol:'cutout.global-library.v1',id,version,kind:'design-system-kit',name:'Alpha system',description:'Verified design system.',contentSha256:hash,content,origin:{kind:'generated',producer:'cutout.compiler',projectId:'project.alpha',runId:'run.alpha',sourceRevision:'revision.alpha'},license:{kind:'spdx',identifier:'Apache-2.0'},tags:['system'],collections:[],favorite:false,pinned:false,dependencies:[],compatibility:[{target:'vite-react',versionRange:'>=1',role:'framework',status:'verified',evidenceIds:[]}],qualityReceipts:[{id:'quality.schema',gate:'schema',status:'passed',checkedAt:at,tool:'cutout',evidence:[]}],lineage:{root:{itemId:id,version,contentSha256:hash},depth:0},createdAt:at,updatedAt:at,...overrides}}
class MemoryBackend implements GlobalLibraryBackend{value:unknown;fail=false;async load(){return this.value}async compareAndSwap(expected:number,next:GlobalLibraryCatalog){if(this.fail)return false;const revision=(this.value as {revision?:number}|undefined)?.revision??0;if(revision!==expected)return false;this.value=next;return true}}
describe('GlobalLibraryStore',()=>{
 it('saves only approved content-addressed deliverables and persists through IndexedDB restart',async()=>{const backend=createIndexedDbGlobalLibraryBackend(new IDBFactory());const store=new GlobalLibraryStore(backend,()=>at);const alpha=await item();await expect(store.saveApproved(alpha,{status:'succeeded',approvalId:'approval.one',contentSha256:'b'.repeat(64)})).rejects.toThrow('Approved deliverable hash');await store.saveApproved(alpha,{status:'succeeded',approvalId:'approval.one',contentSha256:alpha.contentSha256});const restarted=new GlobalLibraryStore(backend,()=>later);expect(await restarted.search()).toEqual([expect.objectContaining({id:'kit.alpha',contentSha256:alpha.contentSha256})])})
 it('supports metadata search/filter and rejects stale CAS writes',async()=>{const backend=new MemoryBackend();const store=new GlobalLibraryStore(backend,()=>at);const alpha=await item();await store.saveApproved(alpha,{status:'succeeded',approvalId:'approval.one',contentSha256:alpha.contentSha256});await store.setMetadata(alpha.id,alpha.version,{favorite:true,pinned:true,tags:['featured','system']});expect(await store.search({text:'alpha',tags:['featured'],favorite:true,pinned:true,compatibleTarget:'vite-react'})).toHaveLength(1);backend.fail=true;await expect(store.setMetadata(alpha.id,alpha.version,{favorite:false})).rejects.toThrow('concurrently')})
 it('updates batch metadata in one catalog revision',async()=>{const store=new GlobalLibraryStore(new MemoryBackend(),()=>at);const alpha=await item();const beta=await item('kit.beta');await store.saveApproved(alpha,{status:'succeeded',approvalId:'approval.one',contentSha256:alpha.contentSha256});await store.saveApproved(beta,{status:'succeeded',approvalId:'approval.two',contentSha256:beta.contentSha256});const result=await store.setMetadataBatch([{id:alpha.id,version:alpha.version},{id:beta.id,version:beta.version}],{favorite:true,tags:['mood'],collectionId:'missing'}).catch(error=>error);expect(result).toBeInstanceOf(Error);await store.createCollection({protocol:'cutout.global-library.v1',id:'moodboard',name:'Moodboard',itemIds:[],pinned:false,createdAt:at,updatedAt:at});const updated=await store.setMetadataBatch([{id:alpha.id,version:alpha.version},{id:beta.id,version:beta.version}],{favorite:true,tags:['mood'],collectionId:'moodboard'});expect(updated.items.every(entry=>entry.favorite&&entry.tags.includes('mood')&&entry.collections.includes('moodboard'))).toBe(true)})
 it('locks cross-project references and reports updates without mutating the lock',async()=>{let now=at;const store=new GlobalLibraryStore(new MemoryBackend(),()=>now);const alpha=await item();await store.saveApproved(alpha,{status:'succeeded',approvalId:'approval.one',contentSha256:alpha.contentSha256});const attached=await store.attachProject({projectId:'project.consumer',itemId:alpha.id,version:alpha.version,updatePolicy:'notify'});const reference=attached.projectReferences[0]!;const nextBase=await item(alpha.id,'1.1.0');const updated={...nextBase,origin:{kind:'updated' as const,itemId:alpha.id,version:alpha.version,contentSha256:alpha.contentSha256},lineage:{root:alpha.lineage.root,parent:{itemId:alpha.id,version:alpha.version,contentSha256:alpha.contentSha256},depth:1},createdAt:later,updatedAt:later};now=later;await store.updateItem(alpha.id,alpha.version,updated,{status:'succeeded',approvalId:'approval.two',contentSha256:updated.contentSha256});await store.refreshUpdates('project.consumer');const resolved=await store.resolveReference(reference.id);expect(resolved.item?.version).toBe('1.0.0');expect(resolved.reference).toMatchObject({status:'update-available',locked:{version:'1.0.0'},availableUpdate:{version:'1.1.0'}})})
 it('forks with lineage instead of producing an untraced copy',async()=>{const store=new GlobalLibraryStore(new MemoryBackend(),()=>at);const alpha=await item();await store.saveApproved(alpha,{status:'succeeded',approvalId:'approval.one',contentSha256:alpha.contentSha256});const base=await item('kit.beta','1.0.0');const fork={...base,origin:{kind:'forked' as const,itemId:alpha.id,version:alpha.version,contentSha256:alpha.contentSha256},lineage:{root:alpha.lineage.root,parent:{itemId:alpha.id,version:alpha.version,contentSha256:alpha.contentSha256},depth:1}};await store.forkItem(alpha.id,alpha.version,fork,{status:'succeeded',approvalId:'approval.fork',contentSha256:fork.contentSha256});expect((await store.search({text:'beta'}))[0]).toMatchObject({origin:{kind:'forked',itemId:'kit.alpha'},lineage:{depth:1}})})
 it('migrates an empty legacy local catalog deterministically',()=>{expect(migrateGlobalLibraryCatalog({items:[],collections:[],projectReferences:[],revision:3,updatedAt:at},later)).toEqual({protocol:'cutout.global-library.v1',items:[],collections:[],projectReferences:[],revision:3,updatedAt:at})})
})
