import { GLOBAL_LIBRARY_PROTOCOL, globalLibraryCatalogSchema, globalLibraryItemSchema, libraryCollectionSchema, projectLibraryReferenceSchema, type GlobalLibraryCatalog, type GlobalLibraryItem, type LibraryItemKind, type ProjectLibraryReference } from './contracts'

export interface GlobalLibraryBackend {
  load(): Promise<unknown | undefined>
  compareAndSwap(expectedRevision: number, next: GlobalLibraryCatalog): Promise<boolean>
}
export interface ApprovedDeliverable { readonly status:'succeeded'; readonly approvalId:string; readonly contentSha256:string }
export interface LibrarySearchQuery { readonly text?:string; readonly kinds?:readonly LibraryItemKind[]; readonly tags?:readonly string[]; readonly collections?:readonly string[]; readonly favorite?:boolean; readonly pinned?:boolean; readonly archived?:boolean; readonly compatibleTarget?:string }

export class GlobalLibraryStore {
  readonly backend:GlobalLibraryBackend
  readonly now:()=>string
  constructor(backend:GlobalLibraryBackend,now:()=>string=()=>new Date().toISOString()){this.backend=backend;this.now=now}
  async catalog(){ return migrateGlobalLibraryCatalog(await this.backend.load(),this.now()) }
  async saveApproved(itemInput:unknown,approval:ApprovedDeliverable){ const item=globalLibraryItemSchema.parse(itemInput); if(!approval.approvalId.trim()) throw new Error('An opaque approval id is required.'); if(approval.contentSha256!==item.contentSha256) throw new Error('Approved deliverable hash does not match the library item.'); if(await computeLibraryContentHash(item.content)!==item.contentSha256) throw new Error('Library content hash does not match its manifest and artifacts.'); return this.mutate((catalog)=>{ const duplicate=catalog.items.find((entry)=>entry.id===item.id&&entry.version===item.version); if(duplicate){ if(duplicate.contentSha256!==item.contentSha256) throw new Error('Library item version already exists with different content.'); return catalog } return {...catalog,items:[...catalog.items,item]} }) }
  async createCollection(input:unknown){ const collection=libraryCollectionSchema.parse(input); return this.mutate((catalog)=>{ if(catalog.collections.some((entry)=>entry.id===collection.id)) throw new Error(`Library collection already exists: ${collection.id}.`); return {...catalog,collections:[...catalog.collections,collection]} }) }
  async setMetadata(id:string,version:string,patch:{readonly favorite?:boolean;readonly pinned?:boolean;readonly archived?:boolean;readonly tags?:readonly string[];readonly collections?:readonly string[]}){ return this.mutate((catalog)=>{ let found=false; const updatedAt=this.now(); const items=catalog.items.map((item)=>{ if(item.id!==id||item.version!==version)return item; found=true; return globalLibraryItemSchema.parse({...item,...('favorite'in patch?{favorite:patch.favorite}:{}),...('pinned'in patch?{pinned:patch.pinned}:{}),...('archived'in patch?{archivedAt:patch.archived?updatedAt:undefined}:{}),...(patch.tags?{tags:[...new Set(patch.tags)].sort()}:{}),...(patch.collections?{collections:[...new Set(patch.collections)].sort()}:{}),updatedAt}) }); if(!found)throw new Error('Library item was not found.'); return {...catalog,items} }) }
  async setMetadataBatch(keys:readonly {readonly id:string;readonly version:string}[],patch:{readonly favorite?:boolean;readonly tags?:readonly string[];readonly collectionId?:string}){if(!keys.length)return this.catalog();return this.mutate((catalog)=>{const requested=new Set(keys.map(({id,version})=>`${id}\0${version}`));const found=new Set<string>();const updatedAt=this.now();const items=catalog.items.map((item)=>{const key=`${item.id}\0${item.version}`;if(!requested.has(key))return item;found.add(key);return globalLibraryItemSchema.parse({...item,...('favorite'in patch?{favorite:patch.favorite}:{}),...(patch.tags?{tags:[...new Set([...item.tags,...patch.tags])].sort()}:{}),...(patch.collectionId?{collections:[...new Set([...item.collections,patch.collectionId])].sort()}:{}),updatedAt})});if(found.size!==requested.size)throw new Error('One or more library items were not found.');return{...catalog,items}})}
  async attachProject(input:{readonly projectId:string;readonly itemId:string;readonly version:string;readonly updatePolicy:ProjectLibraryReference['updatePolicy']}){ return this.mutate((catalog)=>{ const item=select(catalog,input.itemId,input.version); const at=this.now(); const reference=projectLibraryReferenceSchema.parse({protocol:GLOBAL_LIBRARY_PROTOCOL,id:`ref.${stable(input.projectId,input.itemId)}`,projectId:input.projectId,itemId:item.id,kind:item.kind,locked:{version:item.version,contentSha256:item.contentSha256},updatePolicy:input.updatePolicy,status:'current',attachedAt:at,updatedAt:at}); return {...catalog,projectReferences:[...catalog.projectReferences.filter((entry)=>entry.id!==reference.id),reference]} }) }
  async refreshUpdates(projectId:string){
    return this.mutate((catalog)=>({
      ...catalog,
      projectReferences:catalog.projectReferences.map((reference)=>{
        if(reference.projectId!==projectId)return reference
        const newer=latest(catalog.items.filter((item)=>item.id===reference.itemId&&item.contentSha256!==reference.locked.contentSha256))
        if(!newer)return {...reference,status:'current' as const,availableUpdate:undefined,updatedAt:this.now()}
        return projectLibraryReferenceSchema.parse({...reference,status:'update-available',availableUpdate:{version:newer.version,contentSha256:newer.contentSha256,compatibility:compatibility(newer)},updatedAt:this.now()})
      }),
    }))
  }
  async updateItem(parentId:string,parentVersion:string,nextInput:unknown,approval:ApprovedDeliverable){ const parent=select(await this.catalog(),parentId,parentVersion); const next=globalLibraryItemSchema.parse(nextInput); if(next.id!==parent.id||next.version===parent.version||next.contentSha256===parent.contentSha256||!hasParentLineage(next,parent,'updated'))throw new Error('Library update must retain item identity and exact parent lineage while creating a new version and content hash.'); return this.saveApproved(next,approval) }
  async forkItem(parentId:string,parentVersion:string,nextInput:unknown,approval:ApprovedDeliverable){ const parent=select(await this.catalog(),parentId,parentVersion); const next=globalLibraryItemSchema.parse(nextInput); if(next.id===parent.id||!hasParentLineage(next,parent,'forked'))throw new Error('Library fork must use a new identity and retain exact parent lineage.'); return this.saveApproved(next,approval) }
  async search(query:LibrarySearchQuery={}){ const catalog=await this.catalog(); const text=query.text?.trim().toLowerCase(); return catalog.items.filter((item)=>(query.archived===true?Boolean(item.archivedAt):query.archived===false?!item.archivedAt:!item.archivedAt)&&(!query.kinds||query.kinds.includes(item.kind))&&(!query.tags||query.tags.every((tag)=>item.tags.includes(tag)))&&(!query.collections||query.collections.every((id)=>item.collections.includes(id)))&&(query.favorite===undefined||item.favorite===query.favorite)&&(query.pinned===undefined||item.pinned===query.pinned)&&(!query.compatibleTarget||item.compatibility.some((entry)=>entry.target===query.compatibleTarget&&entry.status==='verified'))&&(!text||`${item.id} ${item.name} ${item.description} ${item.tags.join(' ')}`.toLowerCase().includes(text))).sort((a,b)=>Number(b.pinned)-Number(a.pinned)||Number(b.favorite)-Number(a.favorite)||b.updatedAt.localeCompare(a.updatedAt)) }
  async resolveReference(referenceId:string){ const catalog=await this.catalog(); const reference=catalog.projectReferences.find((entry)=>entry.id===referenceId); if(!reference)throw new Error('Project library reference was not found.'); const item=catalog.items.find((entry)=>entry.id===reference.itemId&&entry.version===reference.locked.version&&entry.contentSha256===reference.locked.contentSha256); return {reference,item:item??null} }
  private async mutate(change:(catalog:GlobalLibraryCatalog)=>GlobalLibraryCatalog){ const current=await this.catalog(); const changed=change(current); if(changed===current)return current; const next=globalLibraryCatalogSchema.parse({...changed,revision:current.revision+1,updatedAt:this.now()}); if(!await this.backend.compareAndSwap(current.revision,next))throw new Error('Global library changed concurrently; reload and retry.'); return next }
}

export function migrateGlobalLibraryCatalog(input:unknown,now:string):GlobalLibraryCatalog{ if(input&&typeof input==='object'&&(input as {protocol?:unknown}).protocol===GLOBAL_LIBRARY_PROTOCOL)return globalLibraryCatalogSchema.parse(input); const legacy=input&&typeof input==='object'?input as Record<string,unknown>:{}; return globalLibraryCatalogSchema.parse({protocol:GLOBAL_LIBRARY_PROTOCOL,revision:typeof legacy.revision==='number'?legacy.revision:0,items:Array.isArray(legacy.items)?legacy.items:[],collections:Array.isArray(legacy.collections)?legacy.collections:[],projectReferences:Array.isArray(legacy.projectReferences)?legacy.projectReferences:[],updatedAt:typeof legacy.updatedAt==='string'?legacy.updatedAt:now}) }
export function previewGlobalLibraryDowngrade(input:unknown){const catalog=globalLibraryCatalogSchema.parse(input);return{target:'legacy-global-library.v0' as const,data:{revision:catalog.revision,items:catalog.items,collections:catalog.collections,updatedAt:catalog.updatedAt},losses:catalog.projectReferences.length?[{path:'projectReferences',count:catalog.projectReferences.length,reason:'Legacy catalogs cannot preserve immutable project locks.'}]:[]}}
export async function computeLibraryContentHash(content:GlobalLibraryItem['content']){ const canonical=JSON.stringify({manifestPath:content.manifestPath,manifestSha256:content.manifestSha256,artifacts:[...content.artifacts].sort((a,b)=>a.path.localeCompare(b.path)).map(({path,sha256,mediaType,size})=>({path,sha256,mediaType,size}))}); const bytes=new TextEncoder().encode(canonical); const digest=await crypto.subtle.digest('SHA-256',Uint8Array.from(bytes).buffer); return [...new Uint8Array(digest)].map((value)=>value.toString(16).padStart(2,'0')).join('') }
function select(catalog:GlobalLibraryCatalog,id:string,version:string){ const item=catalog.items.find((entry)=>entry.id===id&&entry.version===version); if(!item)throw new Error(`Library item not found: ${id}@${version}.`); return item }
function latest(items:readonly GlobalLibraryItem[]){ return [...items].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)||compareVersion(b.version,a.version))[0] }
function compareVersion(left:string,right:string){const a=left.split(/[.-]/);const b=right.split(/[.-]/);for(let i=0;i<Math.max(a.length,b.length);i++){const x=a[i]??'';const y=b[i]??'';const xn=Number(x);const yn=Number(y);const comparison=Number.isFinite(xn)&&Number.isFinite(yn)?xn-yn:x.localeCompare(y);if(comparison)return comparison}return 0}
function hasParentLineage(next:GlobalLibraryItem,parent:GlobalLibraryItem,kind:'updated'|'forked'){const reference={itemId:parent.id,version:parent.version,contentSha256:parent.contentSha256};return next.origin.kind===kind&&next.origin.itemId===reference.itemId&&next.origin.version===reference.version&&next.origin.contentSha256===reference.contentSha256&&next.lineage.parent?.itemId===reference.itemId&&next.lineage.parent.version===reference.version&&next.lineage.parent.contentSha256===reference.contentSha256&&next.lineage.root.itemId===parent.lineage.root.itemId&&next.lineage.root.version===parent.lineage.root.version&&next.lineage.root.contentSha256===parent.lineage.root.contentSha256&&next.lineage.depth===parent.lineage.depth+1}
function compatibility(item:GlobalLibraryItem):'compatible'|'breaking'|'unknown'{ return item.compatibility.some((entry)=>entry.status==='incompatible')?'breaking':item.compatibility.some((entry)=>entry.status==='verified')?'compatible':'unknown' }
function stable(...parts:string[]){let hash=2166136261;for(const char of parts.join('\0'))hash=Math.imul(hash^char.charCodeAt(0),16777619);return (hash>>>0).toString(16).padStart(8,'0')}
