/**
 * Vision QA gate — accept/reject generated images with lesson feedback.
 *
 * Competitor analysis (staged re-skin pipelines) showed two mechanisms cutout
 * lacked: a HARD accept/reject gate after each image generation, and failure
 * reasons fed back into the retry prompt ("lessons"). This module provides
 * both as pure, dependency-injected pieces in the `region-deconstruct.ts`
 * style: checklist builders are deterministic functions of the plan, the
 * review is one injected structured-output vision call, and `generateWithQa`
 * is a bounded reject/re-roll loop that NEVER blocks the pipeline — after the
 * retry budget it returns the last attempt with its verdict attached so the
 * caller can surface (not swallow) residual failures.
 */
import { z } from 'zod'
import type { PromptPart } from '@/prompts/types'
import type { GenerationService } from '@/services/ai/types'
import type { ReasoningEffort } from '@/services/ai/reasoning'
import { isErr } from '@/services/types'
import type { PrototypePage, PrototypePlan, PrototypeRegion } from './prototype-plan'

/** Structured-output contract for the `ui-generation-qa` vision call. */
export const qaVerdictSchema = z.object({
  pass: z.boolean(),
  failures: z.array(z.string().min(1)).default([]),
})

export interface QaVerdict {
  readonly pass: boolean
  /** Retry-ready corrections, phrased as instructions for the next attempt. */
  readonly failures: readonly string[]
  /** The reviewer could not produce a verdict. This is a review blocker, never a pass. */
  readonly unavailable?: boolean
}

/** Deterministic acceptance rules for one generated prototype page. */
export function buildPageChecklist(plan: PrototypePlan, page: PrototypePage): string[] {
  const regionRules = page.regions.map(
    (region, index) =>
      `${index + 1}. The "${region.name}" region (${region.role}) is present exactly once: ${region.summary}`,
  )
  const next = regionRules.length
  return [
    ...regionRules,
    `${next + 1}. Exactly one screen is rendered: no adjacent frames, no device bezel, no annotations, no measurement lines, no asset sheet, no design-tool chrome.`,
    `${next + 2}. No garbled, melted, duplicated, or lorem/pseudo text anywhere; long copy appears as clean placeholder bars, and any real labels are short and crisply legible.`,
    `${next + 3}. The page uses one coherent visual system consistent with a ${plan.designSystem.styleSummary} direction (palette: ${plan.designSystem.palette.join(', ')}).`,
    `${next + 4}. No extra invented sections beyond the listed regions, and no region is duplicated.`,
  ]
}

/** Deterministic acceptance rules for one region's flat asset board. */
export function buildBoardChecklist(page: PrototypePage, region: PrototypeRegion): string[] {
  const assets =
    region.assetOpportunities.length > 0
      ? `expected asset types: ${region.assetOpportunities.join(', ')}`
      : 'the assets described by the region summary'
  return [
    `1. The board contains only assets belonging to the "${region.name}" region of the "${page.name}" page (${assets}); no other region's assets, no page chrome, no containers.`,
    `2. The background is a single flat pure-white canvas that flows continuously between all assets; nothing bleeds to or touches the canvas edge.`,
    `3. No two assets touch, overlap, connect, or share a bounding box; every asset has clear white margin on all four sides.`,
    `4. No text is baked into any asset: no labels, headings, numerals, UI copy, or isolated glyphs.`,
    `5. Every white or very light asset has a visible closed non-white contour or internal contrast separating it from the canvas.`,
  ]
}

/** Append rejected-attempt lessons to a base prompt as binding corrections. */
export function qaRetryPrompt(basePrompt: string, failures: readonly string[]): string {
  if (failures.length === 0) return basePrompt
  return [
    basePrompt,
    '',
    'The previous attempt was REJECTED by visual QA. You MUST fix every one of these problems this time:',
    ...failures.map((failure, index) => `${index + 1}. ${failure}`),
  ].join('\n')
}

/** The model slot used for review (the Settings chat/vision assignment). */
export interface QaReviewSlot {
  readonly providerId: string
  readonly model: string
  readonly effort?: ReasoningEffort
}

/**
 * One structured-output vision review of a generated image against a
 * checklist. A transport/model failure is returned as an unavailable rejection
 * so callers can persist a review blocker without discarding generated bytes.
 */
export async function reviewGeneratedImage(
  generation: Pick<GenerationService, 'generateObject'>,
  slot: QaReviewSlot,
  imageBytes: Uint8Array,
  checklist: readonly string[],
  signal?: AbortSignal,
  onReviewError?: (message: string) => void,
): Promise<QaVerdict> {
  const parts: PromptPart[] = [
    { type: 'image', image: imageBytes },
    { type: 'text', text: `Checklist:\n${checklist.join('\n')}` },
  ]
  const result = await generation.generateObject(
    {
      providerId: slot.providerId,
      model: slot.model,
      promptRef: { id: 'ui-generation-qa' },
      input: parts,
      reasoningEffort: slot.effort,
      signal,
    },
    qaVerdictSchema,
  )
  if (isErr(result)) {
    onReviewError?.(result.error)
    return {
      pass: false,
      failures: [`Visual QA unavailable: ${result.error}`],
      unavailable: true,
    }
  }
  // A pass with leftover failure text (or vice versa) is normalized to the
  // stricter reading: any reported failure means rejection.
  const failures = result.data.failures.slice(0, 8)
  return { pass: result.data.pass && failures.length === 0, failures }
}

export interface GenerateWithQaParams {
  readonly basePrompt: string
  /** Generation attempt: prompt in, image bytes out (throws on failure). */
  readonly generate: (prompt: string, signal?: AbortSignal) => Promise<Uint8Array>
  /** Review attempt: image in, verdict out. */
  readonly review: (bytes: Uint8Array, signal?: AbortSignal) => Promise<QaVerdict>
  /** Extra paid re-rolls after the first attempt. Default 2, clamp >= 0. */
  readonly maxRetries?: number
  /** Observability: called once per attempt with its verdict. */
  readonly onVerdict?: (attempt: number, verdict: QaVerdict) => void
  readonly signal?: AbortSignal
}

export interface GenerateWithQaResult {
  readonly bytes: Uint8Array
  /** Verdict of the LAST attempt; `pass: false` means it shipped rejected. */
  readonly verdict: QaVerdict
  readonly attempts: number
}

/**
 * Bounded reject/re-roll loop: generate → review → on rejection, regenerate
 * with the failures appended as corrections. Returns the first passing
 * attempt, or the final attempt (verdict attached) once the budget is spent.
 */
export async function generateWithQa(
  params: GenerateWithQaParams,
): Promise<GenerateWithQaResult> {
  const budget = Math.max(0, params.maxRetries ?? 2)
  let prompt = params.basePrompt
  let attempt = 0
  for (;;) {
    params.signal?.throwIfAborted()
    attempt += 1
    const bytes = await params.generate(prompt, params.signal)
    const verdict = await params.review(bytes, params.signal)
    params.onVerdict?.(attempt, verdict)
    if (verdict.pass || verdict.unavailable || attempt > budget) {
      return { bytes, verdict, attempts: attempt }
    }
    prompt = qaRetryPrompt(params.basePrompt, verdict.failures)
  }
}
