import { expect, test } from './local-state.fixture'

test('Global Library is a first-level responsive workspace with dense provenance', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(async () => {
    const opened = indexedDB.open('cutout-global-library', 2)
    const db = await new Promise<IDBDatabase>((resolve, reject) => { opened.onupgradeneeded = () => { if (!opened.result.objectStoreNames.contains('catalog')) opened.result.createObjectStore('catalog'); if (!opened.result.objectStoreNames.contains('content-blobs')) opened.result.createObjectStore('content-blobs', { keyPath: 'sha256' }) }; opened.onsuccess = () => resolve(opened.result); opened.onerror = () => reject(opened.error) })
    const hash = 'a'.repeat(64), now = '2026-07-12T00:00:00.000Z'
    const artifacts = ['logo.svg','fonts/typography.css','colors.json','photography.md','design-guidance.md','brand-guideline.pdf'].map((path) => ({ path, sha256: hash, mediaType: path.endsWith('.pdf') ? 'application/pdf' : 'text/plain', size: 12 }))
    const item = { protocol: 'cutout.global-library.v1', id: 'brand.alpha', version: '1.0.0', kind: 'brand-kit', name: 'Alpha Brand', description: 'Verified retail identity system.', contentSha256: hash, content: { manifestPath: 'manifest.json', manifestSha256: hash, artifacts }, origin: { kind: 'generated', producer: 'cutout.compiler', projectId: 'project.alpha', runId: 'run.alpha', sourceRevision: 'revision.alpha' }, license: { kind: 'spdx', identifier: 'Apache-2.0' }, tags: ['retail'], collections: [], favorite: false, pinned: false, dependencies: [], compatibility: [], qualityReceipts: [{ id: 'quality.schema', gate: 'schema', status: 'passed', checkedAt: now, tool: 'cutout', evidence: [] }], lineage: { root: { itemId: 'brand.alpha', version: '1.0.0', contentSha256: hash }, depth: 0 }, createdAt: now, updatedAt: now }
    const design = { ...item, id:'design.alpha', kind:'design-system-kit', name:'Alpha Design System', content:{ ...item.content, artifacts:['DESIGN.md','tailwind.config.ts','styles/variables.css','tokens/design.tokens.json','astryx/config.json'].map((path)=>({path,sha256:hash,mediaType:'text/plain',size:12})) }, lineage:{root:{itemId:'design.alpha',version:'1.0.0',contentSha256:hash},depth:0} }
    const visual = { ...item, id: 'asset.reference', kind: 'visual-asset', name: 'Campaign Reference', description: 'Approved image reference.', tags: ['reference'], content: { ...item.content, artifacts: [{ ...item.content.artifacts[0], path: 'reference.png', mediaType: 'image/png' }] }, lineage: { root: { itemId: 'asset.reference', version: '1.0.0', contentSha256: hash }, depth: 0 } }
    const video = { ...visual, id: 'asset.video', name: 'Campaign Film', tags: ['reference'], content: { ...visual.content, artifacts: [{ ...visual.content.artifacts[0], path: 'film.mp4', mediaType: 'video/mp4' }] }, lineage: { root: { itemId: 'asset.video', version: '1.0.0', contentSha256: hash }, depth: 0 } }
    const motion = { ...visual, id: 'asset.motion', name: 'Logo Reveal', tags: ['motion'], content: { ...visual.content, artifacts: [{ ...visual.content.artifacts[0], path: 'motion/timeline.json', mediaType: 'application/json' }] }, lineage: { root: { itemId: 'asset.motion', version: '1.0.0', contentSha256: hash }, depth: 0 } }
    const tx = db.transaction('catalog', 'readwrite'); tx.objectStore('catalog').put({ protocol: 'cutout.global-library.v1', revision: 1, items: [item, design, visual, video, motion], collections: [], projectReferences: [], updatedAt: now }, 'global'); await new Promise<void>((resolve, reject) => { tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error) }); db.close()
  })
  await page.reload()
  await page.getByRole('button', { name: 'Library' }).first().click()
  await expect(page.getByRole('region', { name: 'Global library' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Alpha Brand' })).toBeVisible()
  await expect(page.getByText('1 passed')).toBeVisible()
  await page.getByRole('heading', { name: 'Alpha Brand' }).click()
  await expect(page.getByRole('complementary', { name: 'Alpha Brand kit editor' })).toBeVisible()
  await expect(page.getByLabel('Kit audit')).toContainText('0Missing')
  await page.getByLabel('Import Brand Book candidates').setInputFiles({ name: 'brand-candidates.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify({ candidates: [{ id: 'candidate.color.1', kind: 'color', value: '#2255FF', confidence: 0.94, evidenceIds: ['evidence.page.1'], status: 'candidate' }] })) })
  await page.getByText('#2255FF').click()
  await page.getByRole('button', { name: 'Publish new version' }).click()
  await expect(page.getByRole('complementary', { name: 'Alpha Brand kit editor' })).toContainText('v1.0.1')
  await page.getByRole('button', { name: 'Close kit editor' }).click()
  await page.getByRole('tab', { name: 'Design Systems' }).click()
  await page.getByRole('heading', { name: 'Alpha Design System' }).click()
  await expect(page.getByRole('tab', { name: 'DESIGN.md' })).toBeVisible()
  await page.getByRole('tab', { name: 'Astryx' }).click()
  await expect(page.getByText('astryx/config.json')).toBeVisible()
  await page.getByRole('button', { name: 'Close kit editor' }).click()
  await page.getByRole('tab', { name: 'Brand Kits' }).click()
  await page.getByRole('button', { name: 'Use dense preview' }).click()
  await expect(page.getByRole('button', { name: 'Use masonry preview' })).toBeVisible()
  await page.getByRole('tab', { name: 'Visual Assets' }).click()
  await page.getByRole('button', { name: 'References' }).click()
  await expect(page.getByRole('heading', { name: 'Campaign Reference' })).toBeVisible()
  await page.getByRole('button', { name: 'Select Campaign Reference' }).click()
  await expect(page.getByRole('toolbar', { name: 'Bulk asset actions' })).toBeVisible()
  await page.getByRole('heading', { name: 'Campaign Reference' }).click()
  await expect(page.getByText('Verified local preview, provenance, and capability-aware asset actions.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Discover references' })).toBeDisabled()
  await page.getByText('Provenance and files').click()
  await expect(page.getByText(/project.alpha/)).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('heading', { name: 'Campaign Film' }).click()
  await expect(page.getByRole('button', { name: 'Analyze video' })).toBeDisabled()
  await expect(page.getByText('Video executor and reference provider hosts are not configured.')).toBeVisible()
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: 'All', exact: true }).click()
  await page.getByRole('heading', { name: 'Logo Reveal' }).click()
  await expect(page.getByLabel('Motion timeline')).toBeVisible()
  await page.getByRole('button', { name: 'Add keyframe' }).click()
  await expect(page.getByLabel(/keyframe\..* time/)).toHaveCount(3)
  await page.keyboard.press('Escape')
  await page.getByRole('tab', { name: 'Components' }).click()
  await expect(page.getByText('No components yet')).toBeVisible()
})
