import { z } from 'zod'

export const DELIVERY_CENTER_PROTOCOL = 'cutout.delivery-center.v1' as const
export const COMPOSITE_RECEIPT_PROTOCOL = 'cutout.delivery-receipt.v1' as const
export const deliveryTargetKindSchema = z.enum(['brand-kit','design-system','components','visual-assets','starter','registry','github','notion'])
export type DeliveryTargetKind = z.infer<typeof deliveryTargetKindSchema>
const sha = z.string().regex(/^[a-f0-9]{64}$/)
const safeId = z.string().min(1).max(200).refine((value) => !secretShaped(value), 'Secret-shaped values are forbidden.')
const safePath = z.string().min(1).max(512).refine((value) => !value.startsWith('/') && !value.includes('\\') && value.split('/').every((part) => part && part !== '.' && part !== '..'))

export const deliveryRevisionSchema = z.object({ documentId: safeId, revisionId: safeId, revisionNumber: z.number().int().nonnegative() }).strict()
export const qualityEvidenceSchema = z.object({ gate: z.enum(['build','accessibility','visual-regression','typecheck','unit-test','integration-test','provenance','license']), status: z.enum(['passed','failed','skipped']), evidenceIds: z.array(safeId).max(100), summary: z.string().max(1000).refine((value) => !secretShaped(value)).optional() }).strict()
export const deliveryArtifactSchema = z.object({ path: safePath, sha256: sha, mediaType: z.string().min(1).max(160) }).strict()
export const deliveryDestinationSchema = z.object({ kind: z.enum(['managed-export','controlled-repository','external-publish']), ref: safeId, baseRevision: safeId.optional() }).strict().superRefine((destination, ctx) => { if (destination.kind !== 'managed-export' && !destination.baseRevision) ctx.addIssue({ code:'custom', message:'Repository and external destinations require a base revision.' }) })
export const deliveryTargetRequestSchema = z.object({ id: safeId, kind: deliveryTargetKindSchema, destination: deliveryDestinationSchema, requiredGates: z.array(qualityEvidenceSchema.shape.gate).max(20), dependsOn: z.array(safeId).max(20).default([]), metadata: z.record(z.string(), z.unknown()).default({}) }).strict()
export const deliveryRequestSchema = z.object({ protocol: z.literal(DELIVERY_CENTER_PROTOCOL), id: safeId, outcomeId: safeId, outcomeRevision: safeId, designRevision: deliveryRevisionSchema, targets: z.array(deliveryTargetRequestSchema).min(1).max(50) }).strict().superRefine((request, ctx) => { const ids = new Set(request.targets.map((target) => target.id)); if (ids.size !== request.targets.length) ctx.addIssue({ code:'custom', path:['targets'], message:'Target ids must be unique.' }); for (const target of request.targets) for (const dependency of target.dependsOn) if (!ids.has(dependency) || dependency === target.id) ctx.addIssue({ code:'custom', path:['targets'], message:`Invalid dependency ${dependency}.` }); if (secretShaped(JSON.stringify(request))) ctx.addIssue({ code:'custom', message:'Delivery request contains credential-shaped data.' }) })

export const targetPreviewSchema = z.object({ targetId: safeId, kind: deliveryTargetKindSchema, destination: deliveryTargetRequestSchema.shape.destination, effects: z.array(z.enum(['managed-export','project-files','external-write','paid-provider'])).min(1), estimatedCostUsd: z.number().nonnegative(), currency: z.literal('USD'), files: z.array(z.object({ path: safePath, sha256: sha.optional() }).strict()).max(5000), warnings: z.array(z.string().max(1000)).max(100) }).strict()
export const deliveryPlanSchema = z.object({ protocol: z.literal(DELIVERY_CENTER_PROTOCOL), id: safeId, requestId: safeId, outcomeId: safeId, outcomeRevision: safeId, designRevision: deliveryRevisionSchema, targets: z.array(targetPreviewSchema), totalEstimatedCostUsd: z.number().nonnegative(), currency: z.literal('USD'), requiresApproval: z.literal(true), createdAt: z.string().datetime() }).strict()

export const targetExecutionReceiptSchema = z.object({ targetId: safeId, kind: deliveryTargetKindSchema, status: z.enum(['succeeded','failed','cancelled','capability-required','skipped']), destination: deliveryDestinationSchema, startedAt: z.string().datetime(), completedAt: z.string().datetime(), artifacts: z.array(deliveryArtifactSchema).max(5000), quality: z.array(qualityEvidenceSchema).max(100), kitManifests: z.array(z.object({ kind: z.enum(['brand-kit','design-system']), id: safeId, sha256: sha }).strict()).max(10), registry: z.object({ itemId: safeId, version: safeId, contentSha256: sha }).strict().optional(), targetRevision: z.object({ ref: safeId, baseRevision: safeId, resultRevision: safeId.optional() }).strict().optional(), externalPublish: z.object({ provider: z.enum(['github','notion']), remoteId: safeId, remoteUrl: z.string().url().refine((value) => !secretShaped(value)), baseRevision: safeId.optional() }).strict().optional(), error: z.object({ code: safeId, message: z.string().min(1).max(1200).refine((value) => !secretShaped(value)) }).strict().optional() }).strict().superRefine((receipt, ctx) => { if (receipt.status === 'succeeded' && receipt.error) ctx.addIssue({ code:'custom', message:'Successful target receipt cannot contain an error.' }); if (receipt.status !== 'succeeded' && !receipt.error && receipt.status !== 'skipped') ctx.addIssue({ code:'custom', message:'Unsuccessful target receipt requires a safe error.' }); if (receipt.status === 'succeeded') { if ((receipt.kind === 'brand-kit' || receipt.kind === 'design-system') && !receipt.kitManifests.some((manifest) => manifest.kind === receipt.kind)) ctx.addIssue({ code:'custom', message:'Successful Kit delivery requires its manifest.' }); if (receipt.kind === 'registry' && !receipt.registry) ctx.addIssue({ code:'custom', message:'Successful registry delivery requires item identity and hash.' }); if (receipt.kind === 'visual-assets' && receipt.artifacts.length === 0) ctx.addIssue({ code:'custom', message:'Successful visual delivery requires an artifact.' }); if ((receipt.kind === 'github' || receipt.kind === 'notion') && receipt.externalPublish?.provider !== receipt.kind) ctx.addIssue({ code:'custom', message:'Successful external delivery requires a matching publish receipt.' }); if (receipt.destination.kind !== 'managed-export' && (!receipt.targetRevision || receipt.targetRevision.baseRevision !== receipt.destination.baseRevision)) ctx.addIssue({ code:'custom', message:'Successful repository/external delivery requires matching target revision evidence.' }) } if (secretShaped(JSON.stringify(receipt))) ctx.addIssue({ code:'custom', message:'Target receipt contains credential-shaped data.' }) })
export const compositeDeliveryReceiptSchema = z.object({ protocol: z.literal(COMPOSITE_RECEIPT_PROTOCOL), id: safeId, planId: safeId, requestId: safeId, approvalId: safeId, outcome: z.object({ id: safeId, revision: safeId }).strict(), designRevision: deliveryRevisionSchema, status: z.enum(['succeeded','completed-with-failures','cancelled']), targets: z.array(targetExecutionReceiptSchema).min(1), artifactHashes: z.array(z.object({ targetId: safeId, path: safePath, sha256: sha }).strict()), completedAt: z.string().datetime() }).strict().superRefine((receipt, ctx) => {
  const allSucceeded = receipt.targets.every((target) => target.status === 'succeeded')
  if (receipt.status === 'succeeded' && !allSucceeded) ctx.addIssue({ code:'custom', message:'Composite success requires every selected target to succeed.' })
  if (receipt.status === 'completed-with-failures' && allSucceeded) ctx.addIssue({ code:'custom', message:'Failure status requires a non-success target.' })

  const targetIds = receipt.targets.map((target) => target.targetId)
  if (new Set(targetIds).size !== targetIds.length) ctx.addIssue({ code:'custom', path:['targets'], message:'Composite target ids must be unique.' })
  const expectedArtifacts = receipt.targets.flatMap((target) => target.artifacts.map((artifact) => artifactKey(target.targetId, artifact.path, artifact.sha256)))
  const claimedArtifacts = receipt.artifactHashes.map((artifact) => artifactKey(artifact.targetId, artifact.path, artifact.sha256))
  if (new Set(claimedArtifacts).size !== claimedArtifacts.length) ctx.addIssue({ code:'custom', path:['artifactHashes'], message:'Composite artifact hashes must be unique.' })
  if (expectedArtifacts.length !== claimedArtifacts.length || expectedArtifacts.some((artifact) => !claimedArtifacts.includes(artifact))) ctx.addIssue({ code:'custom', path:['artifactHashes'], message:'Composite artifact hashes must exactly match target receipt artifacts.' })
  if (secretShaped(JSON.stringify(receipt))) ctx.addIssue({ code:'custom', message:'Composite receipt contains credential-shaped data.' })
})

export type DeliveryRequest = z.infer<typeof deliveryRequestSchema>
export type DeliveryPlan = z.infer<typeof deliveryPlanSchema>
export type TargetPreview = z.infer<typeof targetPreviewSchema>
export type TargetExecutionReceipt = z.infer<typeof targetExecutionReceiptSchema>
export type CompositeDeliveryReceipt = z.infer<typeof compositeDeliveryReceiptSchema>

const SECRET = /(?:\b(?:sk|rk|pk)-[A-Za-z0-9_-]{8,}\b|\bBearer\s+[A-Za-z0-9._~+/-]+\b|(?:api[-_]?key|token|secret|authorization)\s*[:=]\s*[^\s,;]+)/i
export function secretShaped(value: string): boolean { return SECRET.test(value) }
function artifactKey(targetId: string, path: string, sha256: string): string { return `${targetId}\0${path}\0${sha256}` }
