import type { GitHubWritePlan, IntegrationRequest, IntegrationResult, IntegrationSession, PublishPlan } from '@/integration-sdk'
import { targetExecutionReceiptSchema } from './contracts'
import type { DeliveryExecutor } from './runtime'

export interface GitHubDeliveryAdapter{
  createWritePlan(request:IntegrationRequest,files:readonly {path:string;contentSha256:string;diff:string}[],checks:readonly {name:string;summary:string}[]):Promise<IntegrationResult<GitHubWritePlan>>
  applyApprovedPublish(request:IntegrationRequest,plan:GitHubWritePlan,approvalId:string):Promise<IntegrationResult<unknown>>
}
export interface NotionDeliveryAdapter{publish(request:IntegrationRequest,context:{session:IntegrationSession;now:()=>string;signal:AbortSignal}):Promise<IntegrationResult<PublishPlan>>}
export interface IntegrationDeliveryOptions{readonly github?:{adapter:GitHubDeliveryAdapter;session:IntegrationSession};readonly notion?:{adapter:NotionDeliveryAdapter;session:IntegrationSession};readonly now?:()=>string}

export function createIntegrationDeliveryExecutors(options:IntegrationDeliveryOptions):readonly DeliveryExecutor[]{const result:DeliveryExecutor[]=[];if(options.github)result.push(githubExecutor(options.github,options.now??(()=>new Date().toISOString())));if(options.notion)result.push(notionExecutor(options.notion,options.now??(()=>new Date().toISOString())));return result}
function githubExecutor(input:NonNullable<IntegrationDeliveryOptions['github']>,now:()=>string):DeliveryExecutor{const plans=new Map<string,GitHubWritePlan>();return{kind:'github',async preview(target,request){requireExternal(target);const integration=integrationRequest(target,request,input.session);const files=readFiles(target.metadata.files),checks=readChecks(target.metadata.checks);const planned=await input.adapter.createWritePlan(integration,files,checks);if(!planned.ok)throw new Error(planned.error.message);plans.set(target.id,planned.data);return{targetId:target.id,kind:'github',destination:target.destination,effects:['external-write'],estimatedCostUsd:0,currency:'USD',files:files.map(({path,contentSha256})=>({path,sha256:contentSha256})),warnings:['Creates a review branch and pull request; it never writes the default branch or merges automatically.'] }},async execute(target,context){const startedAt=now(),plan=plans.get(target.id);if(!plan)throw new Error('GitHub publish preview is missing or expired.');const request=integrationRequest(target,context.request,input.session,context.signal);const applied=await input.adapter.applyApprovedPublish(request,plan,context.approvalId);if(!applied.ok)return failed(target,startedAt,now(),applied.error.code,applied.error.message);const value=applied.data as{branch?:string;commitSha?:string;pullRequestUrl?:string};if(!value.pullRequestUrl||!value.commitSha)throw new Error('GitHub host did not return verifiable PR and commit evidence.');return targetExecutionReceiptSchema.parse({targetId:target.id,kind:'github',status:'succeeded',destination:target.destination,startedAt,completedAt:now(),artifacts:readFiles(target.metadata.files).map(({path,contentSha256})=>({path,sha256:contentSha256,mediaType:'application/octet-stream'})),quality:[],kitManifests:[],targetRevision:{ref:target.destination.ref,baseRevision:target.destination.baseRevision,resultRevision:value.commitSha},externalPublish:{provider:'github',remoteId:value.commitSha,remoteUrl:value.pullRequestUrl,baseRevision:target.destination.baseRevision}})}}}
function notionExecutor(input:NonNullable<IntegrationDeliveryOptions['notion']>,now:()=>string):DeliveryExecutor{return{kind:'notion',async preview(target){requireExternal(target);const markdown=target.metadata.markdown;return{targetId:target.id,kind:'notion',destination:target.destination,effects:['external-write'],estimatedCostUsd:0,currency:'USD',files:typeof markdown==='string'?[{path:'notion-delivery.md'}]:[],warnings:typeof markdown==='string'?[]:['Approved markdown is required before publish.']}},async execute(target,context){const startedAt=now(),request=integrationRequest(target,context.request,input.session,context.signal,{...target.metadata,approved:true});const published=await input.adapter.publish(request,{session:input.session,now,signal:context.signal});if(!published.ok)return failed(target,startedAt,now(),published.error.code,published.error.message);const url=published.data.targetRef;if(!/^https:\/\//.test(url))throw new Error('Notion host did not return a verifiable published page URL.');const remoteId=url.split('/').filter(Boolean).at(-1)!;return targetExecutionReceiptSchema.parse({targetId:target.id,kind:'notion',status:'succeeded',destination:target.destination,startedAt,completedAt:now(),artifacts:[],quality:[],kitManifests:[],targetRevision:{ref:target.destination.ref,baseRevision:target.destination.baseRevision,resultRevision:published.data.id},externalPublish:{provider:'notion',remoteId,remoteUrl:url,baseRevision:target.destination.baseRevision}})}}}
function integrationRequest(target:any,request:any,session:IntegrationSession,signal?:AbortSignal,metadata?:Record<string,unknown>):IntegrationRequest{return{operation:'publish',session,base:request.designRevision,current:request.designRevision,locator:String(target.metadata.locator??target.destination.ref),title:typeof target.metadata.title==='string'?target.metadata.title:undefined,metadata:metadata??target.metadata,conflictPolicy:'fail',signal}}
function requireExternal(target:any){if(target.destination.kind!=='external-publish'||!target.destination.baseRevision)throw new Error('Integration delivery requires an external destination with base revision.')}
function readFiles(value:unknown){return Array.isArray(value)?value.filter((v):v is{path:string;contentSha256:string;diff:string}=>v&&typeof v.path==='string'&&/^[a-f0-9]{64}$/.test(v.contentSha256)&&typeof v.diff==='string'):[]}
function readChecks(value:unknown){return Array.isArray(value)?value.filter((v):v is{name:string;summary:string}=>v&&typeof v.name==='string'&&typeof v.summary==='string'):[]}
function failed(target:any,startedAt:string,completedAt:string,code:string,message:string){return targetExecutionReceiptSchema.parse({targetId:target.id,kind:target.kind,status:code==='authorization-required'?'capability-required':'failed',destination:target.destination,startedAt,completedAt,artifacts:[],quality:[],kitManifests:[],error:{code,message}})}
