import { describe, expect, it, vi } from 'vitest'
import type { RegistryInstallReceipt, RegistryItem } from '@/registry'
import { createLocalDeliveryExecutors, UnifiedDeliveryCenter, type DeliveryRequest } from '.'

const at='2026-07-12T00:00:00.000Z', digest='a'.repeat(64)
const item:RegistryItem={schemaVersion:'cutout.registry-item.v1',id:'cutout.button',version:'1.0.0',kind:'component',metadata:{name:'Button',description:'Accessible button.',tags:['button']},files:[{path:'src/Button.tsx',mediaType:'text/typescript',size:4,sha256:digest,role:'source'}],designIrRefs:['component:button'],tokenRefs:['color.primary'],dependencies:[],frameworks:[{id:'vite-react',role:'target'}],provenance:[{id:'source.one',source:'generated',capturedAt:at,actor:'agent',contentSha256:digest}],license:{kind:'spdx',identifier:'Apache-2.0'},qualityReceipts:[{gate:'typecheck',status:'passed',checkedAt:at,evidence:[{sha256:digest,path:'src/Button.tsx',mediaType:'text/typescript'}]}],previewAssets:[]}
const request=(kind:'registry'|'github'='registry'):DeliveryRequest=>({protocol:'cutout.delivery-center.v1',id:'request.one',outcomeId:'outcome.one',outcomeRevision:'outcome.r1',designRevision:{documentId:'design.one',revisionId:'revision.one',revisionNumber:1},targets:[{id:'target.one',kind,destination:kind==='github'?{kind:'external-publish',ref:'github.target',baseRevision:'git.base'}:{kind:'managed-export',ref:'local.export'},requiredGates:kind==='registry'?['typecheck']:[],dependsOn:[],metadata:kind==='registry'?{ref:'button'}:{}}]})
function receipt(hash=digest):RegistryInstallReceipt{return{protocol:'cutout.registry-install-receipt.v1',planId:'install.one',itemId:item.id,itemVersion:item.version,status:'succeeded',fileHashes:[{path:'src/Button.tsx',baseHash:hash}],approvalId:'approval.one',completedAt:at}}
function hosts(result=receipt()){return{exportBrandKit:vi.fn(),exportStarter:vi.fn(),installRegistry:vi.fn(async()=>result)}}

describe('local Composite Delivery executors',()=>{
  it('previews and executes a real registry install receipt without claiming build or publish',async()=>{const host=hosts();const center=new UnifiedDeliveryCenter(createLocalDeliveryExecutors({registryItems:{button:item}},host,()=>at),()=>at);const plan=await center.preview(request());expect(plan.targets[0]).toMatchObject({effects:['managed-export'],files:[{path:'src/Button.tsx',sha256:digest}]});const completed=await center.execute(plan.id,'approval.one',request().designRevision);expect(completed).toMatchObject({status:'succeeded',targets:[{status:'succeeded',quality:[{gate:'typecheck',status:'passed'}],registry:{itemId:'cutout.button',version:'1.0.0'}}]});expect(completed.targets[0]?.quality.some(({gate})=>gate==='build')).toBe(false);expect(host.installRegistry).toHaveBeenCalledOnce()})
  it('rejects a local host receipt whose artifacts differ from the approved item',async()=>{const center=new UnifiedDeliveryCenter(createLocalDeliveryExecutors({registryItems:{button:item}},hosts(receipt('b'.repeat(64))),()=>at),()=>at);const plan=await center.preview(request());await expect(center.execute(plan.id,'approval.one',request().designRevision)).rejects.toThrow('hash mismatch')})
  it('keeps GitHub capability-required when no authorized host exists',async()=>{const center=new UnifiedDeliveryCenter(createLocalDeliveryExecutors({registryItems:{button:item}},hosts(),()=>at),()=>at);const plan=await center.preview(request('github'));expect(plan.targets[0]?.warnings).toContain('github executor is capability-required.');expect(await center.execute(plan.id,'approval.one',request('github').designRevision)).toMatchObject({status:'completed-with-failures',targets:[{status:'capability-required'}]})})
})
