import { describe, expect, it } from 'vitest'
import { UnifiedDeliveryCenter, compositeDeliveryReceiptSchema, type DeliveryExecutor, type DeliveryRequest, type TargetExecutionReceipt } from '.'

const revision = { documentId:'design.one', revisionId:'revision.7', revisionNumber:7 }
function request(targets: DeliveryRequest['targets']): DeliveryRequest { return { protocol:'cutout.delivery-center.v1', id:'request.one', outcomeId:'outcome.one', outcomeRevision:'outcome.r2', designRevision:revision, targets } }
function target(id:string, kind:DeliveryRequest['targets'][number]['kind'], options:Partial<DeliveryRequest['targets'][number]>={}): DeliveryRequest['targets'][number] { const external=kind==='github'||kind==='notion'; return { id, kind, destination:{kind:external?'external-publish':'managed-export',ref:`target.${id}`,...(external?{baseRevision:'remote.r1'}:{})}, requiredGates:[], dependsOn:[], metadata:{}, ...options } }
function executor(kind:DeliveryExecutor['kind'], result:Partial<TargetExecutionReceipt>={}):DeliveryExecutor {
  return {
    kind,
    async preview(value) { return { targetId:value.id,kind,destination:value.destination,effects:[value.destination.kind==='external-publish'?'external-write':'managed-export'],estimatedCostUsd:kind==='visual-assets'?1.25:0,currency:'USD',files:[],warnings:[] } },
    async execute(value) { return { targetId:value.id,kind,status:'succeeded',destination:value.destination,startedAt:'2026-07-12T00:00:00.000Z',completedAt:'2026-07-12T00:00:01.000Z',artifacts:[{path:`deliveries/${value.id}.json`,sha256:'a'.repeat(64),mediaType:'application/json'}],quality:[],kitManifests:[],...result } },
  }
}

describe('Unified Delivery Center',()=>{
  it('previews all effects/destinations/cost and executes one approved dependency graph',async()=>{ const center=new UnifiedDeliveryCenter([executor('design-system',{kitManifests:[{kind:'design-system',id:'kit.one',sha256:'b'.repeat(64)}]}),executor('registry',{registry:{itemId:'cutout.button',version:'1.0.0',contentSha256:'c'.repeat(64)}}),executor('notion',{targetRevision:{ref:'target.publish',baseRevision:'remote.r1',resultRevision:'remote.r2'},externalPublish:{provider:'notion',remoteId:'page.one',remoteUrl:'https://notion.so/page.one',baseRevision:'remote.r1'}})],()=> '2026-07-12T00:00:02.000Z'); const plan=await center.preview(request([target('kit','design-system'),target('item','registry',{dependsOn:['kit']}),target('publish','notion',{dependsOn:['item']})])); expect(plan).toMatchObject({requiresApproval:true,totalEstimatedCostUsd:0,targets:[{targetId:'kit'},{targetId:'item'},{targetId:'publish',effects:['external-write']}]}); const receipt=await center.execute(plan.id,'approval.delivery.one',revision); expect(receipt).toMatchObject({status:'succeeded',outcome:{id:'outcome.one',revision:'outcome.r2'},designRevision:revision,targets:[{kitManifests:[{id:'kit.one'}]},{registry:{itemId:'cutout.button'}},{externalPublish:{provider:'notion',remoteId:'page.one'}}]}); expect(compositeDeliveryReceiptSchema.safeParse(receipt).success).toBe(true); expect(receipt.artifactHashes).toHaveLength(3) })
  it('never marks missing executors, failed dependencies, or missing quality evidence successful',async()=>{ const center=new UnifiedDeliveryCenter([executor('starter')],()=> '2026-07-12T00:00:02.000Z'); const plan=await center.preview(request([target('starter','starter',{requiredGates:['build','accessibility']}),target('github','github',{dependsOn:['starter']})])); const receipt=await center.execute(plan.id,'approval.delivery.two',revision); expect(receipt).toMatchObject({status:'completed-with-failures',targets:[{targetId:'starter',status:'failed',error:{code:'quality-gate-failed'}},{targetId:'github',status:'skipped',error:{code:'dependency-failed'}}]}) })
  it('rejects stale revisions, cycles and secret-shaped plans/receipts',async()=>{ const center=new UnifiedDeliveryCenter([executor('starter')]); const plan=await center.preview(request([target('starter','starter')])); await expect(center.execute(plan.id,'approval', {...revision,revisionNumber:8})).rejects.toThrow('stale'); await expect(center.preview(request([target('a','starter',{dependsOn:['b']}),target('b','starter',{dependsOn:['a']})]))).rejects.toThrow('cycle'); expect(()=>compositeDeliveryReceiptSchema.parse({protocol:'cutout.delivery-receipt.v1',id:'receipt',planId:'plan',requestId:'req',approvalId:'token=super-secret-value',outcome:{id:'out',revision:'r1'},designRevision:revision,status:'succeeded',targets:[],artifactHashes:[],completedAt:'2026-07-12T00:00:00Z'})).toThrow() })
})
