import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'

describe('AppShell workspace surface routing', () => {
  const source = readFileSync(join(process.cwd(), 'src/components/AppShell.tsx'), 'utf8')
  const workspaceSource = readFileSync(join(process.cwd(), 'src/components/workspace/IntentWorkspace.tsx'), 'utf8')
  const workbenchSource = readFileSync(join(process.cwd(), 'src/components/design-os-workbench/DesignOsWorkbench.tsx'), 'utf8')

  it('keeps Workbench as optional inspection and forwards Profile launches to Canvas', () => {
    expect(source).toContain('workspaceSurface.surface === "inline-main"')
    expect(source).toContain('surfaceMode="deliver"')
    expect(source).toContain('<Dialog open={designOsOpen} onOpenChange={setDesignOsOpen}>')
    expect(source).toContain('<DialogTitle>Project workbench</DialogTitle>')
    expect(source).toContain('gameAssetLaunch={gameAssetLaunch}')
    expect(workbenchSource).toContain('<GameAssetProductionPanel launch={gameAssetLaunch} />')
    expect(source).not.toContain('designOsDefaultTab === "game-assets"')
    expect(source).not.toContain('<GameAssetProductionPanel')
    expect(source).not.toContain('openDesignOs("game-assets", {')
    expect(source).toContain('routeWorkspaceSubmission(brief)')
    expect(source).toContain('setPendingCanvasProfileLaunch({')
    expect(source).toContain('initialProfileLaunch={')
    expect(workspaceSource).toContain('setCanvasProfileLaunch({')
    expect(workspaceSource).toContain('<CanvasProfileStage')
    expect(workspaceSource).toContain('const CanvasProfileStage = lazy(() =>')
    expect(workspaceSource).toContain('import("./CanvasProfileStage")')
    expect(workspaceSource).not.toContain('import { CanvasProfileStage }')
    expect(workspaceSource).toContain('onInspectProject={() => onOpenDesignOs("overview")}')
    expect(workspaceSource).toContain('onOpenDeliveryDetails={() => onOpenDesignOs("delivery")}')
    expect(source).not.toContain('designOsOpen && workspaceSurface.surface === "canvas-inspector"')
    expect(workspaceSource).toContain('Open Product UI/UX')
    expect(workspaceSource).not.toContain('View specimen')
    expect(workspaceSource).toContain('label="Project"')
    expect(workspaceSource).not.toContain('label="Design"')
    expect(workspaceSource).not.toContain('label="Deliver"')
    expect(workspaceSource).not.toContain('<DeliveryWorkspaceDock')
    expect(source).not.toContain('DeveloperAuditDialog')
    expect(source).not.toContain('advancedAuditOpen')
    expect(source).toContain('data-slot="project-workspace-surface"')
    expect(source).toContain('inert={Boolean(inlineDeliveryTab)}')
    expect(source).toContain('returnFromDeliver({ current: workspaceNavigation')
    expect(source).toContain('state.workspaceSnapshot ?? createEmptyWorkspaceSnapshot()')
  })
})
