import { z } from 'zod'
export const motionEasingSchema=z.union([z.enum(['linear','ease','ease-in','ease-out','ease-in-out','step-start','step-end']),z.string().regex(/^cubic-bezier\((?:-?\d*\.?\d+,\s*){3}-?\d*\.?\d+\)$/)])
export const motionKeyframeSchema=z.object({id:z.string().min(1),atMs:z.number().nonnegative(),property:z.enum(['opacity','transform','color','filter','clip-path']),value:z.string().min(1),easing:motionEasingSchema}).strict()
export const motionTrackSchema=z.object({id:z.string().min(1),targetId:z.string().min(1),trigger:z.enum(['load','hover','press','focus','scroll','in-view','manual']),keyframes:z.array(motionKeyframeSchema).min(1),reducedMotion:z.enum(['preserve','simplify','disable'])}).strict().superRefine((track,context)=>{const sorted=[...track.keyframes].sort((a,b)=>a.atMs-b.atMs);if(sorted.some((frame,index)=>frame!==track.keyframes[index]))context.addIssue({code:'custom',message:'Keyframes must be ordered by time.'});const identities=new Set(track.keyframes.map((frame)=>`${frame.property}:${frame.atMs}`));if(identities.size!==track.keyframes.length)context.addIssue({code:'custom',message:'A property cannot have duplicate timestamps.'})})
export type MotionTrack=z.infer<typeof motionTrackSchema>
export function upsertKeyframe(track:MotionTrack,keyframe:z.input<typeof motionKeyframeSchema>):MotionTrack{const next=motionKeyframeSchema.parse(keyframe),keyframes=[...track.keyframes.filter(({id})=>id!==next.id),next].sort((a,b)=>a.atMs-b.atMs);return motionTrackSchema.parse({...track,keyframes})}
export function reducedMotionTrack(track:MotionTrack):MotionTrack|null{if(track.reducedMotion==='disable')return null;if(track.reducedMotion==='preserve')return track;const finalByProperty=new Map(track.keyframes.map((frame)=>[frame.property,frame]));return motionTrackSchema.parse({...track,keyframes:[...finalByProperty.values()].map((frame,index)=>({...frame,id:`${frame.id}.reduced`,atMs:index===0?0:1,easing:'linear' as const})).sort((a,b)=>a.atMs-b.atMs)})}
export function serializeMotionTrack(track:MotionTrack){const parsed=motionTrackSchema.parse(track);return JSON.stringify({...parsed,keyframes:[...parsed.keyframes].sort((a,b)=>a.atMs-b.atMs||a.id.localeCompare(b.id))})}
export function parseMotionTrack(value:string){return motionTrackSchema.parse(JSON.parse(value))}
export function motionRoundtripGate(track:MotionTrack){const canonical=serializeMotionTrack(track),roundtrip=serializeMotionTrack(parseMotionTrack(canonical)),reduced=reducedMotionTrack(track);return{passed:canonical===roundtrip&&Boolean(track.reducedMotion==='disable'||reduced),canonical,roundtrip,reducedMotionCovered:track.reducedMotion==='disable'||Boolean(reduced)}}
