import{describe,expect,it,vi}from'vitest';import{PrivacySafeTelemetry,ProviderPolicyGuard,evaluateCloudDeployment,runIntegrationSmoke,telemetryEventSchema,type ProviderExecutionPolicy}from'.'
const at='2026-07-12T00:00:00.000Z';const policy:ProviderExecutionPolicy={protocol:'cutout.provider-policy.v1',providerId:'image.provider',quota:{requestsPerMinute:10,maxConcurrent:2,monthlyCostUsd:20},timeoutMs:30_000,regions:['us','eu'],allowedRegion:'eu',contentSafety:{required:true,blockedCategories:['credential-exfiltration']},telemetry:{enabled:false,includeContent:false,includeCredentials:false}}
describe('production readiness and privacy boundaries',()=>{
 it.each(['github','notion','figma','obsidian','pencil','paper','framer','canva']as const)('returns capability-required for %s without a production host',async(integrationId)=>{expect(await runIntegrationSmoke(integrationId,undefined)).toMatchObject({status:'capability-required',evidence:[]})})
 it('rejects a fake credential-gated smoke pass without a SecretHandle',async()=>{const host={probe:vi.fn(async()=>({status:'passed' as const,evidence:['provider-readback'],message:'ok'}))};await expect(runIntegrationSmoke('github',host)).rejects.toThrow('SecretHandle');expect(await runIntegrationSmoke('github',host,{kind:'secret-handle',id:'opaque.one'})).toMatchObject({status:'passed'})})
 it('enforces region, quota, cost, timeout and content-safety policy before provider execution',()=>{const guard=new ProviderPolicyGuard(policy);expect(guard.authorize({region:'eu',estimatedCostUsd:1,activeRequests:0,contentSafetyPassed:true})).toEqual({timeoutMs:30_000,telemetryEnabled:false});expect(()=>guard.authorize({region:'us',estimatedCostUsd:1,activeRequests:0,contentSafetyPassed:true})).toThrow('region');expect(()=>guard.authorize({region:'eu',estimatedCostUsd:21,activeRequests:0,contentSafetyPassed:true})).toThrow('cost');expect(()=>guard.authorize({region:'eu',estimatedCostUsd:1,activeRequests:2,contentSafetyPassed:true})).toThrow('quota');expect(()=>guard.authorize({region:'eu',estimatedCostUsd:1,activeRequests:0,contentSafetyPassed:false})).toThrow('content-safety')})
 it('keeps telemetry and crash reporting opt-in/off and rejects sensitive property classes',async()=>{const sink={emit:vi.fn(),crash:vi.fn()},off=new PrivacySafeTelemetry({protocol:'cutout.telemetry-policy.v1',enabled:false,crashReporting:false,retentionDays:0,includeContent:false,includeFilePaths:false,includeCredentials:false},sink);expect(await off.emit({})).toBe(false);const on=new PrivacySafeTelemetry({protocol:'cutout.telemetry-policy.v1',enabled:true,crashReporting:true,installationId:'install.opaque',retentionDays:30,includeContent:false,includeFilePaths:false,includeCredentials:false},sink);await on.emit({protocol:'cutout.telemetry-event.v1',name:'integration-smoke',occurredAt:at,properties:{provider:'github',passed:true}});expect(sink.emit).toHaveBeenCalledOnce();expect(()=>telemetryEventSchema.parse({protocol:'cutout.telemetry-event.v1',name:'provider-failure',occurredAt:at,properties:{prompt:'private'}})).toThrow('sensitive')})
 it('blocks cloud deployment until configuration, health, privacy operations and backup restore all pass',async()=>{expect(await evaluateCloudDeployment(undefined,at)).toMatchObject({ready:false,checks:[{id:'cloud-provider'}]});const backend={descriptor:vi.fn(async()=>({protocol:'cutout.cloud-backend.v1' as const,providerId:'cloud.one',environment:'production' as const,region:'eu',endpoints:['https://cloud.example.com'],auth:'host-session' as const,encryptionAtRest:true as const,auditLog:true as const,backupRestoreTestedAt:at,dataDeletionSlaDays:30,status:'configured' as const})),health:vi.fn(async()=>({ok:true,evidence:['health.receipt']})),verifyDeleteExport:vi.fn(async()=>({ok:true,evidence:['privacy.receipt']}))};expect(await evaluateCloudDeployment(backend,at)).toMatchObject({ready:true})})
})
