import{cloudBackendDescriptorSchema,deploymentReadinessSchema,providerExecutionPolicySchema,telemetryEventSchema,telemetryPolicySchema,type CloudBackendDescriptor,type ProviderExecutionPolicy,type TelemetryEvent,type TelemetryPolicy}from'./contracts';import type{SecretHandle}from'@/integration-sdk'
export type ProductionIntegrationId='github'|'notion'|'figma'|'obsidian'|'pencil'|'paper'|'framer'|'canva'
export interface IntegrationSmokeHost{probe(input:{integrationId:ProductionIntegrationId;secretHandle?:SecretHandle;signal:AbortSignal}):Promise<{status:'passed'|'capability-required'|'failed';evidence:readonly string[];message:string}>}
export async function runIntegrationSmoke(integrationId:ProductionIntegrationId,host:IntegrationSmokeHost|undefined,secretHandle?:SecretHandle,signal=new AbortController().signal){if(!host)return{integrationId,status:'capability-required' as const,evidence:[],message:'A production integration host is required.'};const result=await host.probe({integrationId,...(secretHandle?{secretHandle}:{}),signal});if(result.status==='passed'&&!secretHandle&&['github','notion','canva'].includes(integrationId))throw new Error('Credential-gated provider cannot pass smoke without a SecretHandle.');return{integrationId,...result}}
export class ProviderPolicyGuard{readonly policy:ProviderExecutionPolicy;constructor(policy:ProviderExecutionPolicy){this.policy=providerExecutionPolicySchema.parse(policy)}authorize(input:{region:string;estimatedCostUsd:number;activeRequests:number;contentSafetyPassed:boolean}){if(input.region!==this.policy.allowedRegion)throw new Error('Provider region is not approved.');if(input.estimatedCostUsd>this.policy.quota.monthlyCostUsd)throw new Error('Provider cost ceiling exceeded.');if(input.activeRequests>=this.policy.quota.maxConcurrent)throw new Error('Provider concurrency quota exceeded.');if(this.policy.contentSafety.required&&!input.contentSafetyPassed)throw new Error('Provider content-safety check is required.');return{timeoutMs:this.policy.timeoutMs,telemetryEnabled:this.policy.telemetry.enabled}}}
export interface TelemetrySink{emit(event:TelemetryEvent):Promise<void>;crash(event:TelemetryEvent):Promise<void>}
export class PrivacySafeTelemetry{readonly policy:TelemetryPolicy;readonly sink?:TelemetrySink;constructor(policy:TelemetryPolicy,sink?:TelemetrySink){this.policy=telemetryPolicySchema.parse(policy);this.sink=sink}async emit(input:unknown){if(!this.policy.enabled||!this.sink)return false;await this.sink.emit(telemetryEventSchema.parse(input));return true}async crash(input:unknown){if(!this.policy.enabled||!this.policy.crashReporting||!this.sink)return false;const event=telemetryEventSchema.parse(input);if(event.name!=='app-crash')throw new Error('Crash sink accepts app-crash events only.');await this.sink.crash(event);return true}}
export interface RemoteCloudBackend{descriptor():Promise<CloudBackendDescriptor>;health(signal:AbortSignal):Promise<{ok:boolean;evidence:readonly string[]}>;verifyDeleteExport(signal:AbortSignal):Promise<{ok:boolean;evidence:readonly string[]}>}
export async function evaluateCloudDeployment(backend:RemoteCloudBackend|undefined,evaluatedAt:string,signal=new AbortController().signal){if(!backend)return deploymentReadinessSchema.parse({protocol:'cutout.deployment-readiness.v1',ready:false,checks:[{id:'cloud-provider',status:'failed',evidence:[],message:'Remote cloud backend is disabled.'}],evaluatedAt});const descriptor=cloudBackendDescriptorSchema.parse(await backend.descriptor()),health=await backend.health(signal),privacy=await backend.verifyDeleteExport(signal);const checks=[{id:'configured',status:descriptor.status==='configured'?'passed' as const:'failed' as const,evidence:[descriptor.providerId],message:'Backend configuration is explicit.'},{id:'health',status:health.ok?'passed' as const:'failed' as const,evidence:[...health.evidence],message:'Backend health probe completed.'},{id:'privacy-operations',status:privacy.ok?'passed' as const:'failed' as const,evidence:[...privacy.evidence],message:'Delete and export operations were verified.'},{id:'backup-restore',status:descriptor.backupRestoreTestedAt?'passed' as const:'failed' as const,evidence:descriptor.backupRestoreTestedAt?[descriptor.backupRestoreTestedAt]:[],message:'Backup restore requires dated evidence.'}];return deploymentReadinessSchema.parse({protocol:'cutout.deployment-readiness.v1',ready:checks.every((c)=>c.status==='passed'),checks,evaluatedAt})}
