import { useState } from 'react'
import { Check, CheckCircle2, ChevronRight, CircleDashed, PackageCheck, Plus, ReceiptText, ShieldCheck, TriangleAlert } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import type { CompositeDeliveryReceipt, DeliveryPlan, DeliveryTargetKind } from '@/delivery-center'
import { GovernanceSummary } from '@/components/design-governance/GovernanceSummary'
import type { GovernanceReceipt, GovernanceScenario } from '@/design-governance'
import { cn } from '@/lib/utils'
import { projectDeliveryReadiness } from './delivery-readiness'
import { deliveryWorkspaceClasses } from '@/workspace/delivery-workspace-ui'

export interface DeliveryTargetOption { readonly id:string; readonly kind:DeliveryTargetKind; readonly label:string; readonly destinationLabel:string; readonly available:boolean; readonly unavailableReason?:string }
export interface DeliveryCenterViewModel { readonly targets:readonly DeliveryTargetOption[]; readonly plan?:DeliveryPlan; readonly receipt?:CompositeDeliveryReceipt; readonly running?:boolean; readonly governance?:{readonly receipt:GovernanceReceipt;readonly scenarios?:readonly GovernanceScenario[]} }
export interface DeliveryCenterPanelProps { readonly model:DeliveryCenterViewModel; readonly onPreview?:(ids:readonly string[])=>void; readonly onApprove?:(planId:string)=>void; readonly onPrepareMissing?:()=>void; readonly onAddDestination?:()=>void; readonly onRequestGovernanceRepair?:GovernanceSummaryProps['onRequestRepair'] }
type GovernanceSummaryProps=Parameters<typeof GovernanceSummary>[0]

export function DeliveryCenterPanel({model,onPreview,onApprove,onPrepareMissing,onAddDestination,onRequestGovernanceRepair}:DeliveryCenterPanelProps){
  const initial=projectDeliveryReadiness(model)
  const [selectedDeliverables,setSelectedDeliverables]=useState<readonly string[]>(initial.selectedDeliverables)
  const [selectedDestination,setSelectedDestination]=useState<string|undefined>(initial.selectedDestination)
  const projection=projectDeliveryReadiness(model,selectedDeliverables,selectedDestination)
  const hasResult=projection.deliverables.length>0
  const disabled=projection.nextAction.kind==='preview'?!onPreview:projection.nextAction.kind==='prepare'?!onPrepareMissing:!onAddDestination
  const act=()=>projection.nextAction.kind==='preview'?onPreview?.(projection.nextAction.targetIds):projection.nextAction.kind==='prepare'?onPrepareMissing?.():onAddDestination?.()
  return <div className={deliveryWorkspaceClasses.primaryColumn} data-slot="delivery-center">
    <header><h3 className={deliveryWorkspaceClasses.heading}>Deliver results</h3><p className={deliveryWorkspaceClasses.description}>Choose an approved result, confirm its destination, then review the delivery before anything is written.</p></header>
    <section aria-labelledby="delivery-result-heading" className="space-y-3">
      <div><h4 id="delivery-result-heading" className={deliveryWorkspaceClasses.sectionHeading}>Choose a result</h4><p className={deliveryWorkspaceClasses.sectionDescription}>Only approved, versioned project outputs can be delivered.</p></div>
      {hasResult?<div className="grid gap-2 sm:grid-cols-2">{projection.deliverables.map((item)=>{const active=projection.selectedDeliverables.includes(item.id);return <button key={item.id} type="button" disabled={!item.ready} aria-pressed={active} className={cn('min-h-16 min-w-0 rounded-md border border-border/70 px-3 py-2.5 text-left transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed',active?'border-foreground/35 bg-muted/40':'bg-background hover:bg-muted/25')} onClick={()=>{setSelectedDeliverables([item.id]);setSelectedDestination(undefined)}}><span className="block text-sm font-medium">{item.label}</span><span className="mt-0.5 block text-xs leading-5 text-muted-foreground">{item.ready?item.detail:(item.unavailableReason??'This result still needs preparation.')}</span></button>})}</div>:<div className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">No approved deliverables are ready yet.</div>}
    </section>
    <section aria-labelledby="delivery-destination-heading" className="space-y-3">
      <div><h4 id="delivery-destination-heading" className={deliveryWorkspaceClasses.sectionHeading}>Choose a destination</h4><p className={deliveryWorkspaceClasses.sectionDescription}>Local export is recommended until a connected destination is authorized.</p></div>
      {projection.destinations.length?<div role="radiogroup" aria-label="Delivery destination" className="divide-y divide-border rounded-md border border-border/70">{projection.destinations.map((target)=><label key={target.id} className="flex min-h-14 min-w-0 items-center gap-3 px-3 py-2.5 has-[:checked]:bg-muted/35"><input type="radio" name="delivery-destination" className="size-4" checked={projection.selectedDestination===target.id} onChange={()=>setSelectedDestination(target.id)}/><span className="min-w-0 flex-1"><span className="block text-sm font-medium">{target.label}</span><span className="block text-xs text-muted-foreground">{target.kind==='local-folder'?'Local export':'Connected app'}</span></span>{target.id===projection.recommendedDestination?<Badge variant="secondary">Recommended</Badge>:null}</label>)}</div>:<p className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">No destination is available for this result.</p>}
      <details className="group border-b border-border/70 pb-2"><summary className="flex min-h-11 cursor-pointer list-none items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><Plus className="size-4"/>Add destination<span className="ml-auto text-xs">{projection.addDestinations.length?`${projection.addDestinations.length} to connect`:'Manage integrations'}</span><ChevronRight className="size-4 transition-transform group-open:rotate-90"/></summary><div className="pb-2 pt-1"><Button type="button" variant="outline" size="sm" onClick={onAddDestination} disabled={!onAddDestination}>Manage integrations</Button>{projection.addDestinations.length?<ul className="mt-3 space-y-2">{projection.addDestinations.map((target)=><li key={target.id} className="flex items-start justify-between gap-3 text-xs"><span className="font-medium">{target.label}</span><span className="max-w-[65%] text-right text-muted-foreground">Connection required</span></li>)}</ul>:null}</div></details>
    </section>
    <section aria-labelledby="delivery-readiness-heading" className="space-y-2"><h4 id="delivery-readiness-heading" className={deliveryWorkspaceClasses.sectionHeading}>Ready to continue?</h4><div className={deliveryWorkspaceClasses.panel}><ul className="divide-y divide-border/60 text-sm">{projection.checklist.map((item)=><Readiness key={item.id} ready={item.complete} label={item.label}/>)}</ul></div></section>
    {model.plan?<Preview plan={model.plan} running={model.running} onApprove={projection.nextAction.kind==='deliver'?onApprove:undefined}/>:<Button className={cn(deliveryWorkspaceClasses.primaryAction,'min-h-11')} disabled={disabled} onClick={act}>{projection.nextAction.kind==='preview'?<PackageCheck/>:<CircleDashed/>}{projection.nextAction.label}</Button>}
    {model.receipt?<Receipt receipt={model.receipt}/>:null}
    <details className="text-xs text-muted-foreground"><summary className="min-h-11 cursor-pointer py-3">Advanced delivery details</summary><div className="space-y-3 text-foreground">{model.governance?<GovernanceSummary receipt={model.governance.receipt} scenarios={model.governance.scenarios} onRequestRepair={onRequestGovernanceRepair}/>:null}{model.plan?<PlanEvidence plan={model.plan}/>:null}<details><summary className="cursor-pointer font-medium">Unavailable destination evidence</summary><pre className="mt-2 max-w-full overflow-x-auto whitespace-pre-wrap rounded-md border border-border p-2 font-mono text-[10px]">{JSON.stringify(projection.advancedEvidence,null,2)}</pre></details></div></details>
  </div>
}

function Readiness({ready,label}:{readonly ready:boolean;readonly label:string}){return <li className="flex min-h-10 items-center gap-2 py-2">{ready?<Check className="size-4 text-emerald-600"/>:<TriangleAlert className="size-4 text-amber-600"/>}<span>{label}</span></li>}
function Preview({plan,running,onApprove}:{readonly plan:DeliveryPlan;readonly running?:boolean;readonly onApprove?:(id:string)=>void}){const warnings=plan.targets.flatMap((target)=>target.warnings);return <Card size="sm" className="rounded-md" data-slot="delivery-preview"><CardHeader><div className="flex flex-wrap items-start justify-between gap-2"><div><CardTitle>Ready to deliver</CardTitle><CardDescription>{plan.targets.length} selected destination{plan.targets.length===1?'':'s'} reviewed</CardDescription></div>{plan.totalEstimatedCostUsd>0?<Badge variant="outline">Up to ${plan.totalEstimatedCostUsd.toFixed(2)}</Badge>:null}</div></CardHeader><CardContent className="space-y-3">{warnings.length?<p className="text-xs text-amber-700 dark:text-amber-300">{warnings.length} delivery warning{warnings.length===1?'':'s'} need review in Advanced details.</p>:null}<Button className="min-h-11" disabled={!onApprove||running} onClick={()=>onApprove?.(plan.id)}><ShieldCheck/> {running?'Delivering...':'Approve and deliver'}</Button></CardContent></Card>}
function PlanEvidence({plan}:{readonly plan:DeliveryPlan}){return <div className="space-y-2 border-y border-border py-3"><p className="font-medium">Approved preview evidence</p><p className="font-mono text-[10px]">Plan {plan.id}</p><p className="font-mono text-[10px]">Outcome {plan.outcomeId}@{plan.outcomeRevision}</p><p className="font-mono text-[10px]">Design {plan.designRevision.revisionId}</p>{plan.targets.map((target)=><div key={target.targetId} className="border-t border-border pt-2"><p>{label(target.kind)} · {destination(target.destination.kind)}</p>{target.warnings.map((warning)=><p key={warning} className="text-amber-700 dark:text-amber-300">{warning}</p>)}</div>)}</div>}
function Receipt({receipt}:{readonly receipt:CompositeDeliveryReceipt}){const succeeded=receipt.targets.filter((target)=>target.status==='succeeded').length;return <Card size="sm" className="rounded-md" data-slot="composite-delivery-receipt"><CardHeader><div className="flex items-start justify-between gap-2"><div><CardTitle className="flex items-center gap-2"><ReceiptText className="size-4"/> Delivery receipt</CardTitle><CardDescription>{succeeded} of {receipt.targets.length} destinations delivered</CardDescription></div><Badge variant={receipt.status==='succeeded'?'secondary':'destructive'}>{receipt.status==='succeeded'?'Delivered':'Needs attention'}</Badge></div></CardHeader><CardContent><ul className="space-y-1">{receipt.targets.map((target)=><li key={target.targetId} className="flex items-center justify-between gap-2 text-xs"><span className="flex min-w-0 items-center gap-2">{target.status==='succeeded'?<CheckCircle2 className="size-3.5 text-emerald-600"/>:<TriangleAlert className="size-3.5 text-destructive"/>}<span className="truncate">{label(target.kind)}</span></span><span className="text-muted-foreground">{target.status}</span></li>)}</ul><details className="mt-3 text-xs"><summary className="cursor-pointer text-muted-foreground">Receipt evidence</summary><div className="mt-2 space-y-1 break-all border-t border-border pt-2 font-mono text-[10px]"><p>{receipt.id}</p><p>{receipt.designRevision.revisionId}</p><p>{receipt.artifactHashes.length} verified file hashes</p>{receipt.targets.flatMap((target)=>target.quality).map((gate,index)=><p key={`${gate.gate}-${index}`}>{gate.gate}: {gate.status} · {gate.evidenceIds.length} evidence</p>)}</div></details></CardContent></Card>}
function label(kind:DeliveryTargetKind){return ({'brand-kit':'Brand VI Kit','design-system':'Design System Kit','visual-assets':'Visual assets',starter:'Starter project',registry:'Source registry',github:'GitHub',notion:'Notion'} as const)[kind]}
function destination(kind:'managed-export'|'controlled-repository'|'external-publish'){return kind==='managed-export'?'Local export':kind==='controlled-repository'?'Project repository':'Connected app'}
