// @vitest-environment jsdom
import { act, createElement } from 'react'
import { createRoot } from 'react-dom/client'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { DeliveryCenterPanel, type DeliveryCenterViewModel } from './DeliveryCenterPanel'

(globalThis as typeof globalThis & { IS_REACT_ACT_ENVIRONMENT:boolean }).IS_REACT_ACT_ENVIRONMENT=true
let host:HTMLDivElement|undefined;let root:ReturnType<typeof createRoot>|undefined
afterEach(()=>{if(root)act(()=>root?.unmount());host?.remove();host=undefined;root=undefined})
function mount(model:DeliveryCenterViewModel,props:Record<string,unknown>={}){host=document.createElement('div');document.body.append(host);root=createRoot(host);act(()=>root?.render(createElement(DeliveryCenterPanel,{model,...props})));return host}
const targets:DeliveryCenterViewModel['targets']=[{id:'kit',kind:'design-system',label:'Design System Kit',destinationLabel:'Download bundle',available:true},{id:'notion',kind:'notion',label:'Notion',destinationLabel:'Product guidelines',available:false,unavailableReason:'Connect Notion first'}]
const plan={protocol:'cutout.delivery-center.v1' as const,id:'plan.one',requestId:'request.one',outcomeId:'outcome.one',outcomeRevision:'outcome.r1',designRevision:{documentId:'design.one',revisionId:'revision.1',revisionNumber:1},targets:[{targetId:'kit',kind:'design-system' as const,destination:{kind:'managed-export' as const,ref:'exports.design'},effects:['managed-export' as const],estimatedCostUsd:0,currency:'USD' as const,files:[],warnings:[]}],totalEstimatedCostUsd:0,currency:'USD' as const,requiresApproval:true as const,createdAt:'2026-07-12T00:00:00Z'}

describe('DeliveryCenterPanel',()=>{
  it.each([['desktop',1440],['mobile',390]])('keeps the outcome-first selection usable on %s',(_name,width)=>{Object.defineProperty(window,'innerWidth',{configurable:true,value:width});const preview=vi.fn();const view=mount({targets},{onPreview:preview});expect(view.textContent).toContain('Choose an approved result');expect(view.textContent).toContain('Choose a result');expect(view.textContent).toContain('Add destination');expect(view.querySelector('input[aria-label="Deliver Notion"]')).toBeNull();const button=[...view.querySelectorAll('button')].find((node)=>node.textContent?.includes('Preview delivery'))!;expect(button.className).toContain('sm:w-auto');act(()=>button.click());expect(preview).toHaveBeenCalledWith(['kit']);expect(view.querySelector('.sm\\:grid-cols-2')).not.toBeNull()})
  it('shows cost only when necessary, approves once, and keeps evidence in Details',()=>{const approve=vi.fn();const paid={...plan,totalEstimatedCostUsd:1.25,targets:[{...plan.targets[0]!,estimatedCostUsd:1.25,effects:['paid-provider' as const]}]};const view=mount({targets,plan:paid},{onApprove:approve});expect(view.textContent).toContain('Up to $1.25');const button=[...view.querySelectorAll('button')].find((node)=>node.textContent?.includes('Approve and deliver'))!;act(()=>button.click());expect(approve).toHaveBeenCalledWith('plan.one');expect([...view.querySelectorAll('details')].some((node)=>node.textContent?.includes('revision.1'))).toBe(true)})
  it('offers one Agent recovery action when no deliverables exist',()=>{const prepare=vi.fn();const view=mount({targets:[]},{onPrepareMissing:prepare});expect(view.textContent).toContain('No approved deliverables');const button=[...view.querySelectorAll('button')].find((node)=>node.textContent?.includes('Ask Agent to prepare'))!;act(()=>button.click());expect(prepare).toHaveBeenCalledOnce()})
  it('describes unavailable destinations without claiming a remote connection',()=>{const view=mount({targets});expect(view.textContent).toContain('Remote destinations require an authorized host session or installed adapter.');expect(view.textContent).toContain('Not connected');expect(view.textContent).not.toContain('Connected to Notion')})
  it('summarizes partial receipts without claiming success',()=>{const receipt={protocol:'cutout.delivery-receipt.v1' as const,id:'receipt.one',planId:'plan.one',requestId:'request.one',approvalId:'approval.one',outcome:{id:'outcome.one',revision:'outcome.r1'},designRevision:plan.designRevision,status:'completed-with-failures' as const,targets:[{targetId:'notion',kind:'notion' as const,status:'capability-required' as const,destination:{kind:'external-publish' as const,ref:'notion.parent',baseRevision:'remote.r1'},startedAt:'2026-07-12T00:00:00Z',completedAt:'2026-07-12T00:00:01Z',artifacts:[],quality:[],kitManifests:[],error:{code:'capability-required',message:'Connect Notion.'}}],artifactHashes:[],completedAt:'2026-07-12T00:00:01Z'};const view=mount({targets,plan,receipt});expect(view.textContent).toContain('0 of 1 destinations delivered');expect(view.textContent).toContain('Needs attention');expect(view.textContent).not.toContain('Delivered</')})
})
