import type{ModelRouteReceipt,RoutePreferences}from'./capability-router'
const POLICY_KEY='cutout.route-policy.v1',RECEIPT_KEY='cutout.route-receipts.v1'
export interface RoutePolicy{readonly version:'cutout.route-policy.v1';readonly advanced:{readonly priority?:'balanced'|'quality'|'cost'|'speed'};readonly constraints:{readonly dataRegion?:{readonly mode:'cn-mainland-required';readonly source:'privacy'|'organization'}}}
export const defaultRoutePolicy:RoutePolicy={version:'cutout.route-policy.v1',advanced:{},constraints:{}}
export function migrateRoutePolicy(input:unknown):RoutePolicy{if(validPolicy(input))return input;const legacy=input&&typeof input==='object'?input as Record<string,unknown>:{};const priority=isPriority(legacy.priority)?legacy.priority:undefined;return{...defaultRoutePolicy,advanced:priority?{priority}:{}}}
export function loadRoutePolicy(storage?:Pick<Storage,'getItem'>):RoutePolicy{try{const value=(storage??globalThis.document?.defaultView?.localStorage)?.getItem(POLICY_KEY);return value?migrateRoutePolicy(JSON.parse(value)):defaultRoutePolicy}catch{return defaultRoutePolicy}}
export function saveRoutePolicy(policy:RoutePolicy,storage?:Pick<Storage,'setItem'>){const host=storage??globalThis.document?.defaultView?.localStorage;if(!host)throw new Error('Route policy storage host is unavailable.');if(!validPolicy(policy))throw new Error('Invalid route policy.');host.setItem(POLICY_KEY,JSON.stringify(policy))}
export function routePreferencesFromPolicy(policy:RoutePolicy):RoutePreferences{return{priority:policy.advanced.priority??'balanced',...(policy.constraints.dataRegion?{dataRegion:policy.constraints.dataRegion}:{})}}
export function appendRouteReceipts(receipts:readonly ModelRouteReceipt[],storage?:Pick<Storage,'getItem'|'setItem'>){const host=storage??globalThis.document?.defaultView?.localStorage;if(!host)return;let existing:unknown[]=[];try{const parsed=JSON.parse(host.getItem(RECEIPT_KEY)??'[]');if(Array.isArray(parsed))existing=parsed}catch{}host.setItem(RECEIPT_KEY,JSON.stringify([...existing,...receipts].slice(-100)))}
export function loadRouteReceipts(storage?:Pick<Storage,'getItem'>):readonly ModelRouteReceipt[]{try{const parsed=JSON.parse((storage??globalThis.document?.defaultView?.localStorage)?.getItem(RECEIPT_KEY)??'[]');return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function isPriority(value:unknown):value is NonNullable<RoutePolicy['advanced']['priority']>{return['balanced','quality','cost','speed'].includes(String(value))}
function validPolicy(value:unknown):value is RoutePolicy{if(!value||typeof value!=='object'||Array.isArray(value))return false;const root=value as Record<string,unknown>,advanced=root.advanced,constraints=root.constraints;if(root.version!=='cutout.route-policy.v1'||!advanced||typeof advanced!=='object'||Array.isArray(advanced)||!constraints||typeof constraints!=='object'||Array.isArray(constraints))return false;const a=advanced as Record<string,unknown>,c=constraints as Record<string,unknown>;if(Object.keys(a).some(key=>key!=='priority')||Object.keys(c).some(key=>key!=='dataRegion')||(a.priority!==undefined&&!isPriority(a.priority)))return false;if(c.dataRegion===undefined)return true;if(!c.dataRegion||typeof c.dataRegion!=='object'||Array.isArray(c.dataRegion))return false;const region=c.dataRegion as Record<string,unknown>;return Object.keys(region).every(key=>key==='mode'||key==='source')&&region.mode==='cn-mainland-required'&&(region.source==='privacy'||region.source==='organization')}
