import { mkdir, readFile, rename, rm, stat, writeFile } from 'node:fs/promises'
import { join, resolve } from 'node:path'
import { durableEventOutboxSchema, durableToolLedgerSchema, durableToolRequestSchema, recoverLedger, sanitize, sanitizeValue, type DurableToolRequest, type ToolDurabilityStore } from './tool-durability.ts'
export function createNodeToolDurabilityStore(projectRoot: string): ToolDurabilityStore {
  const directory = resolve(projectRoot, '.cutout'), statePath = join(directory, 'tool-runtime.json'), ledgerPath = join(directory, 'tool-requests.json'), outboxPath = join(directory, 'tool-event-outbox.json'), lockPath = join(directory, '.tool-ledger.lock')
  const transaction = async <T>(action: (ledger: any, outbox: any) => Promise<{ ledger: any; outbox: any; value: T }>): Promise<T> => { await mkdir(directory, { recursive: true }); await acquire(lockPath); try { const stored = await readJson(statePath, null); const ledger = durableToolLedgerSchema.parse(stored?.ledger ?? await readJson(ledgerPath, { version: 'cutout.tool-ledger.v1', revision: 0, requests: [] })); const outbox = durableEventOutboxSchema.parse(stored?.outbox ?? await readJson(outboxPath, { version: 'cutout.tool-outbox.v1', events: [] })); const result = await action(ledger, outbox); await atomic(statePath, { version: 'cutout.tool-runtime.v1', ledger: result.ledger, outbox: result.outbox }); await Promise.allSettled([atomic(ledgerPath, result.ledger), atomic(outboxPath, result.outbox)]); return result.value } finally { await rm(lockPath, { recursive: true, force: true }) } }
  const mutate = (id: string, fn: (request: any) => any) => transaction(async (ledger, outbox) => { let value; const requests = ledger.requests.map((request: any) => request.requestId === id ? (value = durableToolRequestSchema.parse(fn(request))) : request); if (!value) throw new Error(`Unknown durable tool request: ${id}`); return { ledger: { ...ledger, revision: ledger.revision + 1, requests }, outbox, value } })
  return {
    recover: () => transaction(async (ledger, outbox) => ({ ledger: recoverLedger(ledger), outbox, value: undefined })),
    get: (id) => transaction(async (ledger, outbox) => ({ ledger, outbox, value: ledger.requests.find((request: any) => request.requestId === id) ?? null })),
    plan: (input) => transaction<{ duplicate: boolean; request: DurableToolRequest }>(async (ledger, outbox) => { const existing = ledger.requests.find((request: any) => request.requestId === input.requestId); if (existing) return { ledger, outbox, value: { duplicate: true, request: existing } }; const { at, ...identity } = input; const request = durableToolRequestSchema.parse({ ...identity, status: 'planned', createdAt: at, updatedAt: at, attempts: [] }); return { ledger: { ...ledger, revision: ledger.revision + 1, requests: [...ledger.requests, request] }, outbox, value: { duplicate: false, request } } }),
    begin: (id, attemptId, at) => mutate(id, (request) => ({ ...request, status: 'in-flight', updatedAt: at, attempts: [...request.attempts, { attemptId, startedAt: at, status: 'in-flight' }] })),
    settle: (id, attemptId, outcome, events) => transaction(async (ledger, outbox) => { let value; const requests = ledger.requests.map((request: any) => request.requestId !== id ? request : (value = durableToolRequestSchema.parse({ ...request, status: outcome.status, updatedAt: outcome.at, attempts: request.attempts.map((attempt: any) => attempt.attemptId === attemptId ? { ...attempt, status: outcome.status, completedAt: outcome.at, ...(outcome.receipt ? { receipt: outcome.receipt } : {}), ...(outcome.error ? { error: sanitize(outcome.error) } : {}) } : attempt) }))); if (!value) throw new Error(`Unknown durable tool request: ${id}`); return { ledger: { ...ledger, revision: ledger.revision + 1, requests }, outbox: { ...outbox, events: [...outbox.events, ...events.map((event) => ({ id: event.eventId, requestId: id, event: sanitizeValue(event) }))] }, value } }),
    drainEvents: (deliver) => transaction(async (ledger, outbox) => { const events = outbox.events.map(({ event }: any) => event); if (events.length) deliver(events); return { ledger, outbox: { ...outbox, events: [] }, value: events.length } }),
  }
}
async function acquire(path: string) { const deadline = Date.now() + 10000; while (true) { try { await mkdir(path); return } catch (error: any) { if (error.code !== 'EEXIST') throw error; const info = await stat(path).catch(() => null); if (info && Date.now() - info.mtimeMs > 30000) await rm(path, { recursive: true, force: true }); if (Date.now() > deadline) throw new Error('Tool ledger is busy.'); await new Promise((r) => setTimeout(r, 20)) } } }
async function readJson(path: string, fallback: unknown) { return JSON.parse(await readFile(path, 'utf8').catch((error: any) => error.code === 'ENOENT' ? JSON.stringify(fallback) : Promise.reject(error))) }
async function atomic(path: string, value: unknown) { const temp = `${path}.${process.pid}.tmp`; await writeFile(temp, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o600 }); await rename(temp, path) }
