import { z } from 'zod'
import type { ProviderConfig } from './provider-types'
import { modelCatalogCacheSchema, type ModelCatalogSource } from './model-catalog'
import { modelCapabilitySchema, modelDescriptorSchema, type ModelCapability, type ModelDescriptor } from './model-capabilities'

export const DEFAULT_MODEL_CATALOG_URL='https://models.dev/api.json'
export interface CatalogHttpResponse{readonly status:number;readonly headers:Readonly<Record<string,string|undefined>>;json():Promise<unknown>}
export interface CatalogHttpClient{get(url:string,options:{signal:AbortSignal;headers:Readonly<Record<string,string>>}):Promise<CatalogHttpResponse>}
export const remoteCatalogSnapshotSchema=z.object({version:z.literal('remote-model-catalog-snapshot.v1'),url:z.string().url(),etag:z.string().optional(),cache:modelCatalogCacheSchema}).strict()
export type RemoteCatalogSnapshot=z.infer<typeof remoteCatalogSnapshotSchema>
export interface RemoteCatalogSnapshotStore{load(url:string):Promise<unknown|null>;save(snapshot:RemoteCatalogSnapshot):Promise<void>}
export interface RuntimeCatalogEnvironment{readonly CUTOUT_MODEL_CATALOG_URL?:string;readonly VITE_CUTOUT_MODEL_CATALOG_URL?:string}
export function resolveModelCatalogUrl(input:{url?:string;environment?:RuntimeCatalogEnvironment}={}):string{const value=input.url??input.environment?.CUTOUT_MODEL_CATALOG_URL??input.environment?.VITE_CUTOUT_MODEL_CATALOG_URL??DEFAULT_MODEL_CATALOG_URL,url=new URL(value);if(url.username||url.password||!['https:','http:'].includes(url.protocol))throw new Error('Model catalog URL must be credential-free HTTP(S).');return url.toString()}
export function createFetchCatalogClient(fetcher:typeof fetch=globalThis.fetch):CatalogHttpClient{return{async get(url,options){const response=await fetcher(url,{method:'GET',headers:options.headers,signal:options.signal});return{status:response.status,headers:{etag:response.headers.get('etag')??undefined},json:()=>response.json()}}}}
export function providerDiscoverySource(provider:ProviderConfig,list:(provider:ProviderConfig)=>Promise<readonly string[]>):ModelCatalogSource{return{id:`provider:${provider.id}`,async load(){return(await list(provider)).map(model=>modelDescriptorSchema.parse({providerId:provider.id,model,capabilities:[],evidence:[],source:'provider'}))}}}
export async function loadRemoteModelCatalog(options:{client:CatalogHttpClient;store:RemoteCatalogSnapshotStore;url?:string;environment?:RuntimeCatalogEnvironment;timeoutMs?:number;ttlMs?:number;now?:()=>string}):Promise<{descriptors:ModelDescriptor[];snapshot:RemoteCatalogSnapshot;origin:'network'|'not-modified'|'offline-snapshot';warning?:string}>{
 const url=resolveModelCatalogUrl(options),now=options.now?.()??new Date().toISOString(),saved=remoteCatalogSnapshotSchema.safeParse(await options.store.load(url)),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),options.timeoutMs??5_000)
 try{const headers:Record<string,string>=saved.success&&saved.data.etag?{'if-none-match':saved.data.etag}:{};const response=await options.client.get(url,{signal:controller.signal,headers});if(response.status===304&&saved.success)return{descriptors:saved.data.cache.descriptors,snapshot:saved.data,origin:'not-modified'};if(response.status<200||response.status>=300)throw new Error(`Catalog HTTP ${response.status}.`);const descriptors=normalizeRemoteCatalog(await response.json(),url,now),cache=modelCatalogCacheSchema.parse({version:'model-catalog-cache.v1',generatedAt:now,expiresAt:new Date(Date.parse(now)+(options.ttlMs??86_400_000)).toISOString(),descriptors}),snapshot=remoteCatalogSnapshotSchema.parse({version:'remote-model-catalog-snapshot.v1',url,etag:response.headers.etag,cache});await options.store.save(snapshot);return{descriptors,snapshot,origin:'network'}}catch(error){if(saved.success)return{descriptors:saved.data.cache.descriptors,snapshot:saved.data,origin:'offline-snapshot',warning:error instanceof Error?error.message:String(error)};throw error}finally{clearTimeout(timer)}
}
export function normalizeRemoteCatalog(input:unknown,reference:string,capturedAt:string):ModelDescriptor[]{const rows:ModelDescriptor[]=[];for(const[providerId,provider]of entries(input)){const models=record(provider)?.models??provider;for(const[modelId,raw]of entries(models)){const value=record(raw);if(!value)continue;const capabilities=declaredCapabilities(value),evidence=capabilities.map(capability=>({capability,sourceId:'models.dev',kind:'declared' as const,capturedAt,reference}));rows.push(modelDescriptorSchema.parse({providerId:String(record(provider)?.id??providerId),model:String(value.id??modelId),capabilities,evidence,source:'remote-catalog',metadata:metadata(value)}))}}return rows}
function declaredCapabilities(value:Record<string,unknown>):ModelCapability[]{const values=new Set<ModelCapability>();const input=stringList(record(value.modalities)?.input??value.input),output=stringList(record(value.modalities)?.output??value.output);if(input.includes('text')||output.includes('text'))values.add('text');if(input.some(v=>v==='image'||v==='video'))values.add('vision');if(output.includes('image'))values.add('image-generation');if(output.includes('audio'))values.add('tts');if(input.includes('audio'))values.add('asr');if(output.includes('video'))values.add('video-generation');if(value.reasoning===true)values.add('reasoning');if(value.tool_call===true||value.toolCall===true||value.tools===true)values.add('tools');if(value.web_search===true||value.webSearch===true)values.add('web-search');for(const item of stringList(value.capabilities)){const parsed=modelCapabilitySchema.safeParse(item);if(parsed.success)values.add(parsed.data)}return[...values].sort()}
function metadata(value:Record<string,unknown>){const context=Number(value.context_window??value.contextWindow??0),inputMediaTypes=stringList(record(value.modalities)?.input??value.input),outputMediaTypes=stringList(record(value.modalities)?.output??value.output);return context>0||inputMediaTypes.length||outputMediaTypes.length?{...(context>0?{contextWindow:context}:{}),inputMediaTypes,outputMediaTypes}:undefined}
function record(value:unknown):Record<string,unknown>|undefined{return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,unknown>:undefined}
function entries(value:unknown):[string,unknown][]{if(Array.isArray(value))return value.map((item,index)=>[String(record(item)?.id??index),item]);return Object.entries(record(value)??{})}
function stringList(value:unknown):string[]{return Array.isArray(value)?value.filter((item):item is string=>typeof item==='string').map(item=>item.toLowerCase()):[]}
