import { z } from 'zod'
import { modelDescriptorSchema,type ModelDescriptor } from './model-capabilities'

export interface ModelCatalogSource{readonly id:string;load():Promise<readonly unknown[]>}
export const modelCatalogCacheSchema=z.object({version:z.literal('model-catalog-cache.v1'),generatedAt:z.string().datetime(),expiresAt:z.string().datetime(),descriptors:z.array(modelDescriptorSchema)}).strict()
export type ModelCatalogCache=z.infer<typeof modelCatalogCacheSchema>
const priority:Record<ModelDescriptor['source'],number>={'legacy-migration':0,'user-declared':1,'remote-catalog':2,'verified-catalog':3,provider:4}
export function mergeModelDescriptors(inputs:readonly unknown[]):ModelDescriptor[]{const groups=new Map<string,ModelDescriptor[]>();for(const input of inputs){const descriptor=modelDescriptorSchema.parse(input),key=`${descriptor.providerId}\0${descriptor.model}`,group=groups.get(key)??[];group.push(descriptor);groups.set(key,group)}return[...groups.values()].map(group=>{const ordered=[...group].sort((a,b)=>priority[b.source]-priority[a.source]),head=ordered[0]!,capabilities=[...new Set(ordered.flatMap(value=>value.capabilities))].sort(),evidence=ordered.flatMap(value=>value.evidence);return modelDescriptorSchema.parse({...head,capabilities,evidence,metadata:mergeMetadata(ordered)})}).sort((a,b)=>`${a.providerId}:${a.model}`.localeCompare(`${b.providerId}:${b.model}`))}
export async function loadModelCatalog(sources:readonly ModelCatalogSource[],options:{now?:()=>string;ttlMs?:number;cache?:unknown}={}):Promise<{descriptors:ModelDescriptor[];cache:ModelCatalogCache;sourceErrors:readonly{sourceId:string;message:string}[];fromCache:boolean}>{const now=options.now?.()??new Date().toISOString(),cached=modelCatalogCacheSchema.safeParse(options.cache);if(cached.success&&Date.parse(cached.data.expiresAt)>Date.parse(now))return{descriptors:cached.data.descriptors,cache:cached.data,sourceErrors:[],fromCache:true};const values:unknown[]=[];const sourceErrors:{sourceId:string;message:string}[]=[];for(const source of sources)try{values.push(...await source.load())}catch(error){sourceErrors.push({sourceId:source.id,message:error instanceof Error?error.message:String(error)})}const descriptors=mergeModelDescriptors(values),cache=modelCatalogCacheSchema.parse({version:'model-catalog-cache.v1',generatedAt:now,expiresAt:new Date(Date.parse(now)+(options.ttlMs??3_600_000)).toISOString(),descriptors});return{descriptors,cache,sourceErrors,fromCache:false}}
function mergeMetadata(values:readonly ModelDescriptor[]){const contextWindow=Math.max(0,...values.map(value=>value.metadata?.contextWindow??0)),inputMediaTypes=[...new Set(values.flatMap(value=>value.metadata?.inputMediaTypes??[]))].sort(),outputMediaTypes=[...new Set(values.flatMap(value=>value.metadata?.outputMediaTypes??[]))].sort();return contextWindow||inputMediaTypes.length||outputMediaTypes.length?{...(contextWindow?{contextWindow}:{}),inputMediaTypes,outputMediaTypes}:undefined}
