import { z } from 'zod'
import { openAIWireProtocolSchema,providerKindSchema,type ProviderConfig } from './provider-types'

export const providerAuthMethodSchema=z.enum(['api-key','oauth2','none'])
export const providerAdapterCapabilitySchema=z.enum(['text','vision','reasoning','tools','web-search','image-generation','image-edit','asr','tts','video-generation','video-edit'])
export const providerIconReferenceSchema=z.object({id:z.string().min(1).max(120),source:z.enum(['openai','fal','simple-icons','cutout']),sourceUrl:z.string().url(),license:z.string().min(1).max(160)}).strict()
export const providerDefinitionSchema=z.object({id:providerKindSchema,label:z.string().min(1).max(160),category:z.enum(['recommended','global','china','gateway','local','speech','media','custom']).default('global'),recommended:z.boolean().default(false),env:z.array(z.string().min(1)).default([]),authMethods:z.array(providerAuthMethodSchema).min(1),defaultBaseUrl:z.string().url().optional(),configurableBaseUrl:z.boolean().default(false),adapterIds:z.array(z.string().min(1).max(120)).default([]),openAIWireProtocols:z.array(z.enum(['responses','chat-completions'])).optional(),defaultOpenAIWireProtocol:z.enum(['responses','chat-completions']).optional(),documentationUrl:z.string().url().optional(),icon:providerIconReferenceSchema.optional()}).strict()
export const providerAdapterDefinitionSchema=z.object({id:z.string().min(1).max(120),providerId:providerKindSchema,capabilities:z.array(providerAdapterCapabilitySchema),implemented:z.literal(true),protocol:z.enum(['anthropic','openai','google','gateway','openai-compatible'])}).strict()
export type ProviderDefinition=z.infer<typeof providerDefinitionSchema>;export type ProviderAdapterDefinition=z.infer<typeof providerAdapterDefinitionSchema>
export class ProviderDefinitionRegistry{private definitions=new Map<string,ProviderDefinition>();private adapters=new Map<string,ProviderAdapterDefinition>();registerDefinition(input:unknown){const value=providerDefinitionSchema.parse(input);if(this.definitions.has(value.id))throw new Error(`Provider definition already registered: ${value.id}.`);this.definitions.set(value.id,value);return value}registerAdapter(input:unknown){const value=providerAdapterDefinitionSchema.parse(input);if(this.adapters.has(value.id))throw new Error(`Provider adapter already registered: ${value.id}.`);if(!this.definitions.has(value.providerId))throw new Error(`Provider definition is missing: ${value.providerId}.`);this.adapters.set(value.id,value);return value}definition(id:string){return this.definitions.get(id)}adapter(id:string){return this.adapters.get(id)}adaptersFor(providerId:string){const definition=this.definition(providerId);return definition?.adapterIds.flatMap(id=>{const adapter=this.adapters.get(id);return adapter?[adapter]:[]})??[]}catalog(){return[...this.definitions.values()].sort((a,b)=>a.label.localeCompare(b.label))}parseConfig(input:unknown):ProviderConfig{return providerConfigWithUnknownSchema.parse(input)}}
const providerConfigWithUnknownSchema=z.object({id:z.string().min(1),kind:providerKindSchema,label:z.string().min(1),baseUrl:z.string().min(1).optional(),wireProtocol:openAIWireProtocolSchema.optional(),defaultModel:z.string().min(1),enabled:z.boolean()})
const defs:[string,string,string,boolean][]=[['openai','OpenAI','https://api.openai.com/v1',false],['anthropic','Anthropic','https://api.anthropic.com/v1',false],['google','Google AI','https://generativelanguage.googleapis.com/v1beta',false],['gateway','AI Gateway','',true],['openai-compatible','OpenAI Compatible','',true],['dashscope','DashScope (Qwen)','https://dashscope.aliyuncs.com/compatible-mode/v1',true],['deepseek','DeepSeek','https://api.deepseek.com/v1',true],['zhipu','Zhipu AI','https://open.bigmodel.cn/api/paas/v4',true],['moonshot','Moonshot AI','https://api.moonshot.cn/v1',true],['volcengine','Volcengine Ark','https://ark.cn-beijing.volces.com/api/v3',true],['tencent-hunyuan','Tencent Hunyuan','',true],['minimax','MiniMax','',true],['siliconflow','SiliconFlow','https://api.siliconflow.cn/v1',true],['openrouter','OpenRouter','https://openrouter.ai/api/v1',true],['together','Together AI','https://api.together.xyz/v1',true],['groq','Groq','https://api.groq.com/openai/v1',true],['fireworks','Fireworks AI','https://api.fireworks.ai/inference/v1',true],['xai','xAI','https://api.x.ai/v1',true],['mistral','Mistral AI','https://api.mistral.ai/v1',true],['ollama','Ollama','http://127.0.0.1:11434/v1',true],['vllm','vLLM','http://127.0.0.1:8000/v1',true],['lm-studio','LM Studio','http://127.0.0.1:1234/v1',true],['elevenlabs','ElevenLabs','https://api.elevenlabs.io/v1',true],['deepgram','Deepgram','https://api.deepgram.com/v1',true],['assemblyai','AssemblyAI','https://api.assemblyai.com/v2',true],['replicate','Replicate','https://api.replicate.com/v1',true],['fal','fal.ai','https://fal.run',true]]
const simpleIconIds:Record<string,string>={anthropic:'anthropic',google:'googlegemini',dashscope:'qwen',deepseek:'deepseek',moonshot:'moonshotai',volcengine:'bytedance',minimax:'minimax',openrouter:'openrouter',mistral:'mistralai',ollama:'ollama',vllm:'vllm','lm-studio':'lmstudio',elevenlabs:'elevenlabs',deepgram:'deepgram',replicate:'replicate'}
function iconReference(id:string):ProviderDefinition['icon']{if(id==='openai')return{id:'openai:logo',source:'openai',sourceUrl:'https://openai.com/brand/',license:'OpenAI brand guidelines and trademark terms'};if(id==='fal')return{id:'fal:logo',source:'fal',sourceUrl:'https://fal.ai',license:'fal.ai brand guidelines and trademark terms'};const simpleId=simpleIconIds[id];if(simpleId)return{id:`simple-icons:${simpleId}`,source:'simple-icons',sourceUrl:`https://simpleicons.org/?q=${simpleId}`,license:'CC0-1.0'};return{id:local.has(id)?'cutout:local':id==='gateway'?'cutout:gateway':id==='openai-compatible'?'cutout:compatible':'cutout:provider',source:'cutout',sourceUrl:'https://github.com/cutout/cutout',license:'Apache-2.0'}}
const compatibleCapabilities:Record<string,ProviderAdapterDefinition['capabilities']>={
  'openai-compatible':['text','vision','tools'],dashscope:['text','vision','reasoning','tools'],deepseek:['text','reasoning','tools'],zhipu:['text','vision','reasoning','tools'],moonshot:['text','vision','reasoning','tools'],volcengine:['text','vision','reasoning','tools'],siliconflow:['text','vision','reasoning','tools'],openrouter:['text','vision','reasoning','tools'],together:['text','vision','reasoning','tools'],groq:['text','vision','reasoning','tools'],fireworks:['text','vision','reasoning','tools'],xai:['text','vision','reasoning','tools'],mistral:['text','vision','reasoning','tools'],ollama:['text','vision','tools'],vllm:['text','vision','tools'],'lm-studio':['text','vision','tools'],
}
const compatibleAdapters:ProviderAdapterDefinition[]=Object.entries(compatibleCapabilities).map(([providerId,capabilities])=>({id:`adapter.${providerId}`,providerId,protocol:'openai-compatible',implemented:true,capabilities}))
const builtinAdapters:ProviderAdapterDefinition[]=[{id:'adapter.openai',providerId:'openai',protocol:'openai',implemented:true,capabilities:['text','vision','reasoning','tools','web-search','image-generation','image-edit']},{id:'adapter.anthropic',providerId:'anthropic',protocol:'anthropic',implemented:true,capabilities:['text','vision','reasoning','tools','web-search']},{id:'adapter.google',providerId:'google',protocol:'google',implemented:true,capabilities:['text','vision','reasoning','tools','web-search','image-generation']},{id:'adapter.gateway',providerId:'gateway',protocol:'gateway',implemented:true,capabilities:['text','vision','reasoning','tools']},...compatibleAdapters]
const china=new Set(['dashscope','deepseek','zhipu','moonshot','volcengine','tencent-hunyuan','minimax','siliconflow']);const local=new Set(['ollama','vllm','lm-studio']);const speech=new Set(['elevenlabs','deepgram','assemblyai']);const media=new Set(['replicate','fal']);const gateways=new Set(['gateway','openrouter','together','groq','fireworks']);const recommended=new Set(['openai','anthropic','google']);
function category(id:string):ProviderDefinition['category']{if(recommended.has(id))return'recommended';if(china.has(id))return'china';if(local.has(id))return'local';if(speech.has(id))return'speech';if(media.has(id))return'media';if(gateways.has(id))return'gateway';if(id==='openai-compatible')return'custom';return'global'}
export function createBuiltinProviderRegistry(){const registry=new ProviderDefinitionRegistry();for(const[id,label,url,configurable]of defs){const adapter=builtinAdapters.find(value=>value.providerId===id),openAIShaped=id==='openai'||compatibleCapabilities[id]!==undefined,custom=id==='openai-compatible';registry.registerDefinition({id,label,category:category(id),recommended:recommended.has(id),env:[],authMethods:[local.has(id)?'none':'api-key'],...(url?{defaultBaseUrl:url}:{}),configurableBaseUrl:configurable,adapterIds:adapter?[adapter.id]:[],...(openAIShaped?{openAIWireProtocols:id==='openai'||custom?['responses','chat-completions'] as const:['chat-completions'] as const,defaultOpenAIWireProtocol:id==='openai'?'responses' as const:'chat-completions' as const}:{}),icon:iconReference(id)})}for(const adapter of builtinAdapters)registry.registerAdapter(adapter);return registry}
