import type { ProviderConfig, ProviderKind } from './provider-types'
import { apiBaseUrl } from './base-url'
import { tauriFetch } from './tauri-fetch'
const KEY='__managed_by_rust__'
export interface AdapterRequestPolicy{readonly auth:'rust-keychain-proxy';readonly headerStrategy:'provider-default'|'openai-compatible';readonly baseURL:string|undefined}
export interface GenerationModelAdapter{readonly kind:ProviderKind;policy(config:ProviderConfig):AdapterRequestPolicy;createModel(config:ProviderConfig,modelId:string):Promise<any>}
export class GenerationAdapterRegistry{readonly #items=new Map<ProviderKind,GenerationModelAdapter>();constructor(items:readonly GenerationModelAdapter[]=[]){items.forEach(item=>this.register(item))}register(item:GenerationModelAdapter){this.#items.set(item.kind,item);return this}adapter(kind:ProviderKind){const item=this.#items.get(kind);if(!item)throw new Error(`capability-required: no generation adapter for ${kind}`);return item}createModel(config:ProviderConfig,modelId:string){return this.adapter(config.kind).createModel(config,modelId)}}
export function createOpenAICompatibleAdapter(input:{kind:ProviderKind;mode:'default'|'chat-completions';headerStrategy:'provider-default'|'openai-compatible'}):GenerationModelAdapter{return{kind:input.kind,policy:config=>({auth:'rust-keychain-proxy',headerStrategy:input.headerStrategy,baseURL:apiBaseUrl(config.kind,config.baseUrl)}),async createModel(config,modelId){const{createOpenAI}=await import('@ai-sdk/openai'),provider=createOpenAI({apiKey:KEY,baseURL:apiBaseUrl(config.kind,config.baseUrl),fetch:tauriFetch(config.id,config.kind)});return input.mode==='chat-completions'?provider.chat(modelId):provider(modelId)}}}
export const OPENAI_COMPATIBLE_GENERATION_KINDS = ['openai-compatible','dashscope','deepseek','zhipu','moonshot','volcengine','siliconflow','openrouter','together','groq','fireworks','xai','mistral','ollama','vllm','lm-studio'] as const
export function createDefaultGenerationAdapterRegistry(){const policy=(config:ProviderConfig):AdapterRequestPolicy=>({auth:'rust-keychain-proxy',headerStrategy:'provider-default',baseURL:apiBaseUrl(config.kind,config.baseUrl)});return new GenerationAdapterRegistry([{kind:'anthropic',policy,async createModel(config,id){const{createAnthropic}=await import('@ai-sdk/anthropic');return createAnthropic({apiKey:KEY,baseURL:apiBaseUrl(config.kind,config.baseUrl),fetch:tauriFetch(config.id,config.kind)})(id)}},createOpenAICompatibleAdapter({kind:'openai',mode:'default',headerStrategy:'provider-default'}),{kind:'google',policy,async createModel(config,id){const{createGoogleGenerativeAI}=await import('@ai-sdk/google');return createGoogleGenerativeAI({apiKey:KEY,baseURL:apiBaseUrl(config.kind,config.baseUrl),fetch:tauriFetch(config.id,config.kind)})(id)}},{kind:'gateway',policy,async createModel(config,id){const{createGatewayProvider}=await import('@ai-sdk/gateway');return createGatewayProvider({apiKey:KEY,baseURL:apiBaseUrl(config.kind,config.baseUrl),fetch:tauriFetch(config.id,config.kind)})(id)}},...OPENAI_COMPATIBLE_GENERATION_KINDS.map(kind=>createOpenAICompatibleAdapter({kind,mode:'chat-completions',headerStrategy:'openai-compatible'}))])}
