import{z}from'zod';import{err,type Result}from'@/services/types'
const id=z.string().min(1).max(160),sha=z.string().regex(/^[a-f0-9]{64}$/),audio=z.string().regex(/^audio\/[a-z0-9.+-]+$/)
export const speechRequestSchema=z.discriminatedUnion('capability',[z.object({protocol:z.literal('cutout.speech-request.v1'),requestId:id,capability:z.literal('asr'),providerId:id,model:id,audio:z.object({mediaType:audio,sha256:sha,bytes:z.instanceof(Uint8Array).refine(v=>v.byteLength>0&&v.byteLength<=100*1024*1024)}).strict(),language:z.string().max(35).optional()}).strict(),z.object({protocol:z.literal('cutout.speech-request.v1'),requestId:id,capability:z.literal('tts'),providerId:id,model:id,text:z.string().min(1).max(100_000),voice:id,outputMediaType:audio}).strict()])
export const speechResponseSchema=z.discriminatedUnion('capability',[z.object({protocol:z.literal('cutout.speech-response.v1'),requestId:id,capability:z.literal('asr'),text:z.string(),language:z.string().max(35).optional(),segments:z.array(z.object({startMs:z.number().int().nonnegative(),endMs:z.number().int().positive(),text:z.string()}).strict()).max(100_000)}).strict(),z.object({protocol:z.literal('cutout.speech-response.v1'),requestId:id,capability:z.literal('tts'),audio:z.object({mediaType:audio,sha256:sha,bytes:z.instanceof(Uint8Array).refine(v=>v.byteLength>0&&v.byteLength<=100*1024*1024)}).strict()}).strict()])
export const speechReceiptSchema=z.object({protocol:z.literal('cutout.speech-receipt.v1'),requestId:id,capability:z.enum(['asr','tts']),providerId:id,model:id,status:z.enum(['succeeded','failed','capability-required']),inputSha256:sha,outputSha256:sha.optional(),startedAt:z.string().datetime(),completedAt:z.string().datetime(),detail:z.string().max(1000).optional()}).strict()
export type SpeechRequest=z.infer<typeof speechRequestSchema>;export type SpeechResponse=z.infer<typeof speechResponseSchema>;export type SpeechReceipt=z.infer<typeof speechReceiptSchema>
export interface SpeechAdapter{readonly providerId:string;readonly capabilities:readonly('asr'|'tts')[];execute(request:SpeechRequest,signal?:AbortSignal):Promise<Result<{response:SpeechResponse;receipt:SpeechReceipt}>>}
export class SpeechAdapterRegistry{readonly #items=new Map<string,SpeechAdapter>();register(adapter:SpeechAdapter){if(this.#items.has(adapter.providerId))throw new Error(`Speech adapter already registered: ${adapter.providerId}.`);this.#items.set(adapter.providerId,adapter);return this}adapter(providerId:string){return this.#items.get(providerId)??new CapabilityRequiredSpeechAdapter(providerId)}execute(request:SpeechRequest,signal?:AbortSignal){return this.adapter(request.providerId).execute(request,signal)}}
export class CapabilityRequiredSpeechAdapter implements SpeechAdapter{readonly providerId:string;readonly capabilities=[] as const;constructor(providerId='unconfigured'){this.providerId=providerId}async execute(request:SpeechRequest):Promise<Result<never>>{return err(`capability-required: ${request.capability} has no authorized runtime adapter`)}}
